### ISSUE TITLE
支持全 hash 模式

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icestark#100]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

框架应用必须用 browserhistory

**What is the expected behavior?**

框架应用和微应用全部使用 hash

**Comment by woaizimmy** [comment]
框架应用和微应用全部使用 hash
这个功能什么时候能支持？

**Comment by ClarkXia** [comment]
简单试了一个 demo，框架应用和微应用均采用 hash 目前应该是支持的

**Comment by ClarkXia** [comment]
### 使用方式
```jsx
const App = () => {
  return (
    <AppRouter>
      <AppRoute
        path="/test"
        title="标题"
        hashType // 配置 hashType，标识子应用以 hash 路由方式接入
        url={['//127.0.0.1:3444/js/index.js']}
      />
      <AppRoute
        path="/" // 兜里路由配置，用来显示框架应用路由
        component={<HashRouter>{/* 渲染框架应用路由 */}</HashRouter>} // 通过 component 方式渲染框架路由，Router 渲染同样使用 hash 模式
      />
    </AppRouter>
  );
}
```

PS：如果框架应用为 icejs 框架，配置 app.js 中 router 项进行开启 hash history，详见[配置](https://ice.work/docs/guide/basic/router#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE)

**Comment by TrumanDu** [comment]
@ClarkXia 全hash 无效,没有任何错误

```
const appConfig = {
  app: {
    rootId: 'icestark-container',
  },
  router: {
    type: 'hash',
  },
  icestark: {
    type: 'framework',
    Layout: FrameworkLayout,
    getApps: async () => {
      const apps = [{
        path: 'kafka',
        title: 'KafkaCenter',
        sandbox: true,
        hashType:true,
        // React app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-seller-react-16
        url: [
          '//localhost:3334/css/index.css',
          '//localhost:3334/js/index.js',
        ],
      }, {
        path: '/waiter',
        title: '小二平台',
        sandbox: true,
        url: [
          // Vue app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-waiter-vue-2
          '//ice.alicdn.com/icestark/child-waiter-vue/app.js',
          '//ice.alicdn.com/icestark/child-waiter-vue/app.css'
        ],
      }, {
        path: '/angular',
        title: 'Angular',
        sandbox: true,
        // Angular app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-common-angular-9 
        entry: '//ice.alicdn.com/icestark/child-common-angular/index.html',
      }];
      return apps;
    },
    appRouter: {
      LoadingComponent: PageLoading,
    },
  },
};
createApp(appConfig);
```

**Comment by TrumanDu** [comment]
> ### 使用方式
> ```js-jsx
> const App = () => {
>   return (
>     <AppRouter>
>       <AppRoute
>         path="/test"
>         title="标题"
>         hashType // 配置 hashType，标识子应用以 hash 路由方式接入
>         url={['//127.0.0.1:3444/js/index.js']}
>       />
>       <AppRoute
>         path="/" // 兜里路由配置，用来显示框架应用路由
>         component={<HashRouter>{/* 渲染框架应用路由 */}</HashRouter>} // 通过 component 方式渲染框架路由，Router 渲染同样使用 hash 模式
>       />
>     </AppRouter>
>   );
> }
> ```
> 
> PS：如果框架应用为 icejs 框架，配置 app.js 中 router 项进行开启 hash history，详见[配置](https://ice.work/docs/guide/basic/router#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE)

这种写法怎么接入到ice.js项目中
