### ISSUE TITLE
支持基本微模块加载渲染能力

### ISSUE THREAD

**Issue by wisdomofgod** [ice-lab/icestark#104]
## 背景
icestark 增加对微模块的支持

## 方案
- AppRoute 增加 modules 参数，用于描述模块数据
- AppRoute render 增加支持 Component
- AppRoute modules 存在时， render props 参数新增 { getModules, mountModule, unmountModel }
- 可在 modules 中描述依赖的模块 mount、unmount，可由子模块导出 mount、unmount 方法，默认使用的 react 子模块渲染 mount、unmount
- 子模块打包时，使用 umd 规范。
- 当子模块使用到 react、react-dom 时，打包时 externals react 与 react-dom 库，由父应用统一引入，挂载在 window 上。

## 待处理问题
- react 多版本兼容

**Comment by ClarkXia** [comment]
## 整体方案

### 微模块标准

模块以 umd 方式打包，并保留模块挂载和卸载的相应生命周期：
 - mount：微模块挂载
 - unmount：微模块卸载

### @ice/stark-module 设计

新增 @ice/stark-module 包，核心支持 API：
- getModules：获取当前挂载的模块信息
- mountModule
  - 执行模块加载
  - 渲染模块到指定 node
  - 如果需要缓存已加载模块信息
- unmountModule：卸载模块

### 模块渲染
- AppRoute 增加 modules 参数，描述当前应用需要加载的模块信息

标准微模块定义:

```js
const apps = [{
  path: '/app',
  title: '微模块',
  // 公共依赖
  url: [
    '//unpkg.com/react.js',
    '//unpkg.com/next.js',
  ],
  // 模块定义
  modules: [{
    name: 'module1',
    url: '//unpkg.com/module1.js',
  }, {
    name: 'module2',
    url: '//unpkg.com/module2.js',
  }],
}]
```

### 微模块使用场景

#### 结合 icestark 框架应用

```jsx
import { getModules, mountModule, unmoutModule } from '@ice/stark-module';
...
<AppRouter>
  <AppRoute
    path="/test" 
    title="微模块加载"
    modules={[
      { name: 'module1', url: '//unpkg.com/module1.js' }
    ]}
    render={() => {
      const renderNode = useRef(null);
      useEffect(() => {
        // 获取当前应用模块信息
        const targetModule = getModules().find(({ name }) => name === 'module1');
        // 渲染当前模块
        mountModule(targetModule, renderNode, {});
        return unmoutModule(renderNode);
      }, []);
      return (<div ref={renderNode}></div>)
    }}
  />
</AppRouter>
```

基于标准的 render 方式可以进一步封装逻辑，提供简单的组件 `MicroModule`

```jsx
import { MicroModule } from '@ice/stark-module';
...
<AppRouter>
  <AppRoute
    path="/test" 
    title="微模块加载"
    modules={[
      { name: 'module1', url: '//unpkg.com/module1.js' }
    ]}
    render={() => {
      return <MicroModule name="module1" />
    }}
  />
</AppRouter>
```

#### 应用中独立加载模块

通过传入需要加载的模块信息，对指定标准微模块进行加载

```jsx
import { mountModule, unmoutModule } from '@ice/icestark-module';

export default function Test() {
  const moduleInfo =  { name: 'module1', url: '//unpkg.com/module1.js' };
  const renderNode = useRef(null);
  useEffect(() => {
    // 渲染目标模块
    mountModule(moduleInfo, renderNode, { openTab });
    return unmoutModule(renderNode);
  }, []);
  return (<div ref={renderNode}></div>)
}
```

**Comment by imsobear** [comment]
### 1. module 场景

使用 module 有三种场景：

1. 在框架应用中使用
2. 在微应用中使用
3. 在单独应用中使用

说明里貌似缺失了 2 这个 case。

### 2. mount/unmount 场景

组件什么时候需要定义这个，可以找几个典型的场景

### 3. modules 跟 AppRoute 关联的必要性

关联必要性是？还是说直接挂到 AppRouter 上然后所有子应用都能用？

**Comment by ClarkXia** [comment]
1. module 场景
应用中独立加载模块对应的其实就是 2、3 的场景，主要分为结合框架应用使用和单独使用 @ice/stark-module 的加载能力两种情况

2. mount/unmount 场景
一般情况下均需要定义对应的周期，因为存在技术栈的差异性，即便是 React 组件也不会直接通过 `<Componet />`  方式挂载，所以需要对用的 mount 和 unmout 方法来执行挂载和卸载
```js
// react  组件 
const mount = (mountNode, props) => {
  ReactDOM.render(<Comp {...props}/>, mountNode);
};
const unmount = (mountNode) => {
  ReactDOM.unmountComponentAtNode(mountNode);
};
```

3. modules 跟 AppRoute 关联的必要性
关联 AppRoute，主要考虑通过子应用生命周期管理模块及其依赖的加载和内存的释放，如果全局的方式管理则需要手动进行对应的管理，同独立使用模块加载的能力

**Comment by wisdomofgod** [comment]
1， 子模块默认导出组件本身
```
function Component() {
  return <div>子模块</div>;
}

export default Component;
```

2, mount/unmount 生命周期约定
mount、unmount 生命周期可由子模块导出，也可由父应用中统一配置。
生命周期优先级：父应用配置>子模块导出>默认 react 生命周期。如果使用默认生命周期将 warning 警告。
```
// 子模块导出
// react  组件 
export const mount = (Comp, mountNode, props) => {
  ReactDOM.render(<Comp {...props}/>, mountNode);
};

export const unmount = (mountNode) => {
  ReactDOM.unmountComponentAtNode(mountNode);
};

// 父应用提供
<AppRouter>
  <AppRoute
    path="/test" 
    title="微模块加载"
    modules={[
      {
        name: 'module1',
        url: '//unpkg.com/module1.js',
        mount: (Comp, mountNode, props) => {
          ReactDOM.render(<Comp {...props}/>, mountNode);
        },
        unmount = (mountNode) => {
          ReactDOM.unmountComponentAtNode(mountNode);
        },
       }
    ]}
    render={() => {
      return <MicroModule name="module1" />
    }}
  />
</AppRouter>
```

**Comment by wisdomofgod** [comment]
unmoutModule(renderNode); 方法也需要传入moundInfo，用来获取匹配 module 上的 unmount 生命周期。

**Comment by eightHundreds** [comment]
有几个疑惑
1. 微模块是通过url加载的，js文件的地址是写死的。那么是否意味着不能使用http缓存(强缓存)？ 
2. 微模块如何感知被哪些应用使用? 在维护微组件时，是希望能了解到修改的影响范围，如果要求开发者去每个微应用仓库搜，那体验太不好了

**Comment by iyanming** [comment]
哪里有demo啊，或者可以用的微模块地址直接调试下

**Comment by iyanming** [comment]
如果用icestark提供的微应用地址（
// const moduleInfo = {
  //   name: 'moduleName',
  //   url: [
  //     'http://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-seller-react/build/js/index.js',
  //     'http://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-seller-react/build/css/index.css',
  //   ],
  // }）
调试，会出现这个报错，VM2072:80 Uncaught (in promise) Error: Current page does not exist <div id="ice-container"></div> element.
