### ISSUE TITLE
通过entry加载react页面不成功

### ISSUE THREAD

**Issue by BLTNever** [ice-lab/icestark#105]
问题描述：
子应用demo在nginx服务器部署成功，单独访问成功，Access-Control-Allow-Origin配置允许跨域。
在框架应用中通过url入口加载子应用demo打包后的CDN文件，加载成功。
在框架应用中通过entry加载子应用demo地址，子应用html 内容插入 icestark 动态创建的节点成功。页面无报错，资源加载成功。子应用root节点未挂载内容。

子应用入口配置：
![image](https://user-images.githubusercontent.com/22739465/78379423-ead51000-7604-11ea-99c9-f78878ef5b9e.png)

子应用html渲染成功：
![image](https://user-images.githubusercontent.com/22739465/78379529-1526cd80-7605-11ea-98b4-d61eb1cf4e8d.png)

子应用资源加载成功：
![image](https://user-images.githubusercontent.com/22739465/78379588-3091d880-7605-11ea-8d33-dea38c5e03ae.png)

子项目地址：https://github.com/LouiseDylan/icestrak-child-demo

**Comment by LouiseDylan** [comment]
之前担心是因为nginx部署的资源路径有问题，导致资源加载问题
![image](https://user-images.githubusercontent.com/22739465/78380603-b2363600-7606-11ea-9cc0-3d2a4aa36c94.png)
在子应用的package里配置了homepage，指定了地址：
![image](https://user-images.githubusercontent.com/22739465/78380666-cda14100-7606-11ea-8527-0f91a58b4049.png)

**Comment by ClarkXia** [comment]
简单试了下开发模式下是可以显示子应用内容的
资源加载路径通过 webpack 的 publicPath 进行设置，可以通过加载后是否出现 404 资源进行确认

**Comment by LouiseDylan** [comment]
@ClarkXia 
![image](https://user-images.githubusercontent.com/22739465/78652072-cecaba80-78f3-11ea-8c7d-0f233c04e2f8.png)
![image](https://user-images.githubusercontent.com/22739465/78652108-dd18d680-78f3-11ea-8355-44cf0a041e1e.png)
资源加载是OK的。

![image](https://user-images.githubusercontent.com/22739465/78656816-84990780-78fa-11ea-9a4f-b291defabe8b.png)
但是同一个项目使用entry跟url加载，加载到的资源数量不同

![image](https://user-images.githubusercontent.com/22739465/78656892-9e3a4f00-78fa-11ea-83d4-b0327e3e0245.png)

@ice/stark版本之前是1.0.1 今天更新了之后还是不行。子项目单独访问也是OK的

**Comment by ClarkXia** [comment]
可以把框架应用和子应用一起提供下个简单 demo
