### ISSUE TITLE
针对老的未使用 registerAppEnter 的微应用打印 warning 提示

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icestark#106]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

no warning

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

warning，当前应用未通过 registerAppEnter 注册，balabala

**Comment by ClarkXia** [comment]
`@ice/stark` 1.5.3 版本已支持
