### ISSUE TITLE
创建出来的模板在IE11 报错, SCRIPT5022: Objects are not valid as a React child

### ISSUE THREAD

**Issue by BestDI** [ice-lab/icestark#108]
主框架运行在IE11中报错且页面白屏， chrome中是正常的，报错内容如下：

所用到的版本信息：
> "build-plugin-icestark": "^1.1.4-alpha.3",
> "@ice/stark-data": "latest"

![image](https://user-images.githubusercontent.com/19953784/78735845-4e04d080-797e-11ea-80af-3ebb3e9fc29d.png)

**Comment by ClarkXia** [comment]
https://github.com/ice-lab/icejs/pull/225 icejs polyfill 导致，今天会发版

**Comment by BestDI** [comment]
@ClarkXia icejs 更新之后的版本是什么?

**Comment by ClarkXia** [comment]
使用 icejs@1.1.5
