### ISSUE TITLE
现在我们想做个微前端，不知道用户登录授权这块要怎么处理

### ISSUE THREAD

**Issue by GitHubForQiuKai** [ice-lab/icestark#109]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by imsobear** [comment]
@GitHubForQiuKai 多给一些信息，这样别人没法帮助你。

**Comment by bigbigbo** [comment]
@imsobear

**Comment by bigbigbo** [comment]
子应用允许独立运行，并且又允许运行在基座应用中，请问：
1. 如何处理子应用独立运行时的登录授权问题？
2. 运行在基座应用的时候，登录授权又是怎么样的呢？

分别讨论子应用和基座应用的两种关系：
1. 运行在同域下
2. 运行在不同域下

**Comment by imsobear** [comment]
@bigbigbo 你们现在单独的 SPA 应用登录授权逻辑大概是怎样的？

**Comment by bigbigbo** [comment]
@imsobear 
现在所有的应用都基于一套统一身份认证平台（IDaaS）实现登录授权。

**Comment by imsobear** [comment]
一般情况下子应用需要独立运行的场景很少，如果需求不是很强烈架构上尽量避免。

然后再说用户鉴权这块：

- 所有的异步接口都走鉴权：必选
- 前端获取用户信息：两种方案二选一
  1. 用户同步访问 html 时后端做鉴权，并将用户信息埋在页面全局变量上，前端可直接获取
  2. 前端渲染时判断是否登录，没登录的话通过异步接口实现登录并拿到用户信息，请求后再渲染

这块我感觉跟子应用是否独立运行没什么关系。

**Comment by bigbigbo** [comment]
@imsobear 感谢回答，我这边先实践一下
