### ISSUE TITLE
现有子项目如何接入。如果本地开发调试。最终各个项目如果打包发布构建

### ISSUE THREAD

**Issue by shiliangL** [ice-lab/icestark#111]
现有子项目如何接入。如果本地开发调试。最终各个项目如果打包发布构建

**Comment by shiliangL** [comment]
子项目主要是使用了vue。
官方文关于 vue项目的本地开发调试。最终各个项目如果打包发布构建等好像没有说明
盼复~

**Comment by ClarkXia** [comment]
可以参考例子：https://github.com/ice-lab/icestark-child-apps/blob/master/child-waiter-vue-2/src/main.js
子应用接入的成本比较低，使用 registerAppEnter 和 registerAppLeave
后续我们优化下官方文档
