### ISSUE TITLE
AppRouter 创建 div 元素导致项目迁移样式调整，是否可支持配置化 Fragment

### ISSUE THREAD

**Issue by fancymo** [ice-lab/icestark#113]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by ClarkXia** [comment]
AppRouter 如果直接引入 Fragment 特性，会对 React 版本有所要求（React 16.2.0+），可以具体看下样式迁移调整集中在哪些方面，后续给出一些实践方案
