### ISSUE TITLE
【求助】Vue项目子工程应该如何部署？

### ISSUE THREAD

**Issue by BestDI** [ice-lab/icestark#116]
Vue子项目应该如何和主项目一同发布？应该怎样用nginx代理？说明文档中说明不是很清楚，谢谢大佬 @ClarkXia @imsobear

**Comment by imsobear** [comment]
子应用只需要把静态资源托管到 Nginx 或者 CDN 上，然后框架应用通过 entry/url 的方式加载子应用即可，发布上框架应用和子应用是不耦合的。
