### ISSUE TITLE
路由跳转到login后子登录页不能渲染，必须刷新页面才能显示

### ISSUE THREAD

**Issue by cabinhero** [ice-lab/icestark#123]
appHistory.push('/login');
路由跳转到login后布局进行了更新，但是登录页不能渲染，必须刷新页面才能显示：
window.location.reload();
这样显得比较有卡顿感。
另外登录后也不能及时渲染home页，显示的还是login的表单，也必须重新加载才行。

**Comment by imsobear** [comment]
大概的代码逻辑写一下

**Comment by cabinhero** [comment]
这个问题描述的是另一个现象：逻辑如下：
在框架应用的app.tsx中的配置如下, 若没登录就通过路由跳转至登录页。现象是：框架布局变成了userlayout，但是显示的子页面还是home页，而登录框无法显示，必须reload一下才行。
icestark: {
    type: 'framework',
    Layout: FrameworkLayout,//isLogin?BasicLayout:UserLayout,
    getApps: async () => {
      let apps =[];
      if (!isLogin){
        appHistory.push('/login');
      }else apps=[
        {
          path: '/waiter',
          title: '小二平台',
          url: [
            // Vue app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-waiter-vue-2
            '//ice.alicdn.com/icestark/child-waiter-vue/app.js',
            '//ice.alicdn.com/icestark/child-waiter-vue/app.css'
          ],
        }, {
          path: '/angular',
          title: 'Angular',
          // Angular app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-common-angular-9
          entry: '//ice.alicdn.com/icestark/child-common-angular/index.html',
        }];
      return apps;
    },

**Comment by cabinhero** [comment]
![image](https://user-images.githubusercontent.com/31085313/81128836-e6d63e00-8f74-11ea-8773-76a5c1974d12.png)

**Comment by cabinhero** [comment]
![image](https://user-images.githubusercontent.com/31085313/81128862-00778580-8f75-11ea-9ac2-b934b02d92a9.png)

**Comment by ClarkXia** [comment]
问题原因：
框架路由会在获取 apps 后初始化 icestark 的 AppRouter，在 getApps 过程中初始化未完成无法，还未完成劫持路由的操作，导致这个时机的 push 失效。

计划通过优化 AppRouter 的初始化时机修复或者增加 apps 属性传入，目前可以通过监听 layout 中 appEnter 属性变化实现跳转

```js
useEffect(() => {
  console.log('== app enter ==', appEnter);
  if (appEnter.path === '/' && !isLogin) {
    ...
  }
}, [appEnter]);
```

**Comment by cabinhero** [comment]
我这样搞定了，流畅多了。  
useEffect(() => {
    if (appEnter.path === '/' && !isLogin) {
      appHistory.push('/login');
    }
    if (appEnter.path === '/' &&isLogin){
      appHistory.push("/")
    }

  }, [appEnter]);
