### ISSUE TITLE
动态更新子应用不起作用

### ISSUE THREAD

**Issue by cabinhero** [ice-lab/icestark#124]
1、app.tsx
![image](https://user-images.githubusercontent.com/31085313/80954601-45de6a80-8e30-11ea-9bba-36cbbd9cffae.png)

2、FramworkLayout修改
![image](https://user-images.githubusercontent.com/31085313/80954382-d7011180-8e2f-11ea-85e0-c60372901aa4.png)

**Comment by imsobear** [comment]
跟 #123 是同一个问题？

**Comment by cabinhero** [comment]
不是同一个问题。这里说的是登录成功后通过updatApps动态注册子应用不起作用。ice.js版本是1.2.1

**Comment by ClarkXia** [comment]
这个问题本质上跟 https://github.com/ice-lab/icestark/issues/123 类似，getApps 方法会 async 执行，给出的 demo 直接在 mount 的时机执行了 updateApp，如果 app 内容是异步获取的应该不会有类似的问题 https://github.com/ice-lab/icejs/blob/55d858cc0d9253bedf5a4bfd09cbe55bfab428da/packages/plugin-icestark/src/module.tsx#L89

**Comment by cabinhero** [comment]
按照这个思路我做了一下修改后能够动态的获取appList。但是系统并没有把应用注册上，比如：用admin登录后应该注册小二平台和angular。控制台也能看到appList里是这两个应用的信息。但是点击左侧响应子应用的菜单却无反应。
后来，改变了登录后的策略如下，本质是重加载了一下才真正注册上了这两个应用。请问有更好的方式吗？
 appHistory.push('/');
      setTimeout(()=>{
          window.location.reload();
      },100)
![image](https://user-images.githubusercontent.com/31085313/81470795-58d1b000-921f-11ea-93cb-c845c4ae8005.png)
![image](https://user-images.githubusercontent.com/31085313/81470808-6b4be980-921f-11ea-9775-b7fa259353c5.png)

**Comment by cabinhero** [comment]
@ClarkXia 
按照这个思路我做了一下修改后能够动态的获取appList。但是系统并没有把应用注册上，比如：用admin登录后应该注册小二平台和angular。控制台也能看到appList里是这两个应用的信息。但是点击左侧响应子应用的菜单却无反应。
![image](https://user-images.githubusercontent.com/31085313/81471174-e4e4d700-9221-11ea-83f1-5e32bd7a58ea.png)

**Comment by ClarkXia** [comment]
可以提供个 demo 排查下

**Comment by cabinhero** [comment]
@ClarkXia 突然明白setApps是不行的：
const [apps, setApps] = useState(null);，
因为setApps只是修改了state。
改成 updateApps(appList)就行了
