### ISSUE TITLE
框架应用如何能注册一个纯静态的html页面

### ISSUE THREAD

**Issue by cabinhero** [ice-lab/icestark#126]
我开发了两个子应用seller和detail。单独运行没问题的,集成到一个index.html里也是没问题的，都能正常显示：
![image](https://user-images.githubusercontent.com/31085313/81496652-a61b5380-92eb-11ea-89ad-e8572a641903.png)
但是当我把上面的index.html注册进框架应用，却只能渲染最后一个detail应用，而不能渲染第一个seller应用。我感觉是挂载点的缘故。请问如何能让把ndex.html挂在到框架应用？
index.html的代码如下：

![A1030287-9958-4065-B3FE-EDDA0E1216C1](https://user-images.githubusercontent.com/31085313/81496867-6b1a1f80-92ed-11ea-9be1-dc8d664bbef6.png)

**Comment by cabinhero** [comment]
@ClarkXia 大侠，给我点建议

**Comment by ClarkXia** [comment]
子应用会通过 `regsiterAppEnter` 生命周期的注册挂载，在框架应用下目前仅支持同时存在一个挂载方法。

类似的场景建议还是做成一个应用，如果两个子应用内部都各自有自己路由逻辑，这样挂载会存在很多问题
