### ISSUE TITLE
icestark and qiankun use same solution?

### ISSUE THREAD

**Issue by lzq920** [ice-lab/icestark#13]
Issue is uniformly managed in [alibaba/ice](https://github.com/alibaba/ice/issues). The issues not in alibaba/ice will be closed directly.

Issue 统一在 [alibaba/ice](https://github.com/alibaba/ice/issues) 仓库管理，不在 alibaba/ice 的 issue 会被直接关闭。

**Comment by daysai** [comment]
> Issue is uniformly managed in [alibaba/ice](https://github.com/alibaba/ice/issues). The issues not in alibaba/ice will be closed directly.
> 
> Issue 统一在 [alibaba/ice](https://github.com/alibaba/ice/issues) 仓库管理，不在 alibaba/ice 的 issue 会被直接关闭。

详见 Issue is uniformly managed in alibaba/ice 。qiankun 底层依赖 single-spa，icestark 做的事情更多是跟 single-spa 同级。整体上还是两个不同的解决方案，icestark 的对外运营文章最快本周，最晚下周三之前会公布，届时会有些具体说明。

**Comment by lzq920** [comment]
两个星期过去了....对外运营文章还没发布嘛?

**Comment by daysai** [comment]
> 两个星期过去了....对外运营文章还没发布嘛?

非常抱歉来晚了这么久~
文章经过几次退回重写~
又经过数次改版~
[面向大型工作台的微前端解决方案 icestark](https://zhuanlan.zhihu.com/p/88449415)
