### ISSUE TITLE
如何避免子应用频繁处理同一事件

### ISSUE THREAD

**Issue by cabinhero** [ice-lab/icestark#132]
问题产生场景：
第一步：框架应用派发事件
 event.emit('frameMessage','change language');
第二步：子应用里注册事件
 event.on('frameMessage', (info) => {
    console.log('detail gets frameMessage',info)
  });
第三步：启动框架应用，并进入集成事件子应用。
第四步：触发框架应用的事件，派发frameMessage事件。在console里可以看到子应用响应了1次事件。
第五步：离开该子应用；
第六步：重新进入第三步的子应用。
第七步：再次触发框架应用的事件，派发frameMessage事件。在console里可以看到子应用响应了2次事件。逻辑开始出错。

若重复5-7步n遍会发现子应用对一次框架应用事件的响应次数程直线上升。
通过检查，事件确实只派发了1次。
尝试多种方法无法解决：

比如在派发的事件里加如时间戳。
let timestamp=Date.parse(new Date());
let info={msg:'change language',timestamp}
event.emit('frameMessage',info);
在事件处理函数里对比时间戳不同才进行事件处理：

  let curtimestamp=null;
  event.on('frameMessage', (info) => {
    let {timestamp}=info;
    if (curtimestamp!=timestamp){
      curtimestamp=timestamp;
      console.log('processing receive event showdetails',info)
       });
}

上述方法依然不能避免事件被多次响应问题。

**Comment by cabinhero** [comment]
@ClarkXia

**Comment by ClarkXia** [comment]
子应用挂载的时候执行了 event.on，卸载的时候应该通过 event.off 移除监听函数

**Comment by cabinhero** [comment]
> 子应用挂载的时候执行了 event.on，卸载的时候应该通过 event.off 移除监听函数

不是太明白，子应用的挂载和卸载侦听是在框架应用的FrameworkLayout里：
 useEffect(() => {
    console.log('== app leave ==', appLeave);
    if (appLeave.path === '/angular' && window.webpackJsonp) {
      // remove webpackJsonp added by Angular app
      delete window.webpackJsonp;
    }
    console.log(`卸载子应用：${appLeave.path}`);
  }, [appLeave]);

在这里怎么调用event.off呀？
另外单页应用的情况下，卸载子应用时移除了事件侦听的话，子应用间就无法通信了。 @ClarkXia

**Comment by cabinhero** [comment]
我在子应用里这么写也不行：
if (isInIcestark()) {
    registerAppEnter(() => {
        event.on('frameMessage', (info) => {
            console.log('seller gets frameMessage',info)
            Message.success('seller gets frameMessage'+info);
        });
        ReactDOM.render(router(), getMountNode());
    });
    registerAppLeave(() => {
        console.log('离开app！')
        event.off('frameMessage',(info)=>{
            console.log('remove  frameMessage register',info)
        });
        ReactDOM.unmountComponentAtNode(getMountNode());
    });
} else {
    ReactDOM.render(router(), document.getElementById('ice-container'));
}

**Comment by cabinhero** [comment]
@ClarkXia

**Comment by ClarkXia** [comment]
```js
const messageEvent = (info) => {
  console.log('seller gets frameMessage',info)
  Message.success('seller gets frameMessage'+info);
};
if (isInIcestark()) {
registerAppEnter(() => {
  event.on('frameMessage', messageEvent);
  ReactDOM.render(router(), getMountNode());
});
registerAppLeave(() => {
  console.log('离开app！')
  event.off('frameMessage', messageEvent);
  ReactDOM.unmountComponentAtNode(getMountNode());
});
} else {
  ReactDOM.render(router(), document.getElementById('ice-container'));
}
```
function 需要是同一个引用
