### ISSUE TITLE
子应用都使用Code Splitting 在切换的时候有一个子应用加载不到全部js文件

### ISSUE THREAD

**Issue by wangbinxinbin** [ice-lab/icestark#134]
问题：子应用都启用代码分割部署以后，在框架应用可以加载一个子应用全部js文件。切换子应用时，第二个子应用js文件加载不到。
![1591340483512](https://user-images.githubusercontent.com/41618771/83846613-74a47500-a73d-11ea-83ae-021e83798742.jpg)

**Comment by ClarkXia** [comment]
子应用都使用 code splitting 的下在应用切换的时候清空下 `window.webpackJsonp` 的内容
