### ISSUE TITLE
为什么没有支持hashchange事件？

### ISSUE THREAD

**Issue by xiaoxudoo** [ice-lab/icestark#141]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
大部分微服务框架都支持了hashchange事件，为什么icestark没有支持？
**What is the expected behavior?**

**Comment by ClarkXia** [comment]
hashchange 事件具体的用法是怎样的？
icestark 支持 hash 路由的模式接入微应用，参考 https://github.com/ice-lab/icestark/issues/100#issuecomment-626122735
