### ISSUE TITLE
import { store } from '@ice/stark-data'  store.set 的数据，在浏览器刷新后消失了,如何才能让它持久化下来呢？

### ISSUE THREAD

**Issue by Dean-ZhenYao-Wang** [ice-lab/icestark#145]
我是在主应用上进行登录的，然后将获取到的jwt数据通过store.set 存储下来，
然后在子应用的代码里用store.get获取
在浏览器未点击刷新按钮前，子应用自己的页面在切换时，这个jwt数据依然存在，当我点击浏览器的刷新按钮时，这个jwt数据消失了，如何才能让它持久化下来呢？

**Comment by ClarkXia** [comment]
持久化本地存储可以结合 localstorage 的能力

**Comment by Dean-ZhenYao-Wang** [comment]
> 持久化本地存储可以结合 localstorage 的能力

谢谢提供的方案，已完美解决。
本人第一次接触纯前端的东西，不懂的太多了。
看文档还以为这个东西就是localstorage的操作封装呢。
