### ISSUE TITLE
webpackJsonp冲突问题

### ISSUE THREAD

**Issue by yuxiuj** [ice-lab/icestark#150]
bug

问题描述：
1. 创建主子应用，主子应用全部为 react 框架编写（最新版本），采用 hook 方式
2. 主应用采用 entry 方式加载子应用
3. 子应用通过 webpack 的 proxy 处理跨域请求问题
4. 子应用抽离三方包或者通过路由按需加载的方式打成多个包（打包成一个的时候不会存在这个问题）

结果：
1. 子应用可以正常访问，主应用不加载子应用也可以正常访问
2. 主应用通过 entry 方式加载子应用会报错崩溃，导致主应用被卸载掉 (removeChild)，页面只显示子应用

个人处理：
在主应用中 onRouteChange 监听到路由变化的时候，手动设置 window.webpackJsonp = []，可以解决当前问题

**Comment by ClarkXia** [comment]
开启 sandbox 后 window 上的变量会隔离，不再需要手动处理 `window.webpackJsonp`

**Comment by yuxiuj** [comment]
@ClarkXia 给 AppRoute 组件添加了 sandbox 属性，依然存在当前的问题

**Comment by yuxiuj** [comment]
https://github.com/yuxiuj/microFrontend 这里是一个 demo

**Comment by ClarkXia** [comment]
主应用和子应用中均存在拆包的情况下（即主应用和子应用均会有自己的 webpackJsonp），需要通过修改 [output.jsonpFuntion](https://webpack.js.org/configuration/output/#outputjsonpfunction) 将同时存在的两个同名变量进行隔离

**Comment by yuxiuj** [comment]
这种情况，无法实现沙箱隔离吗？

**Comment by ClarkXia** [comment]
> 这种情况，无法实现沙箱隔离吗？

嗯 目前沙箱的机制是记录 window 变量的变化，在卸载沙箱的时候会还原 window 变量，对于子应用间可以比较好地进行隔离，但是对于同时存在的主子应用还无法完全隔离，特别是同时依赖一个同名变量的场景

后续我们也会看下如果优化这种场景上的隔离

**Comment by yuxiuj** [comment]
output.jsonpFuntion  可以提供一下 demo 吗？

**Comment by ClarkXia** [comment]
常规 webpack 配置修改方式，参考 https://webpack.js.org/configuration/output/#outputjsonpfunction

```js
// webpack.config.js
module.exports = {
  //...
  output: {
    jsonpFunction: 'frameworkWebpackJsonp'
  }
};
```

如果基于 ice.js 的项目可以参考  https://ice.work/docs/guide/develop/plugin-build 添加自定义插件，插件内容

```js
module.exports = ({ onGetWebpackConfig }, options) => {
  onGetWebpackConfig((config) => {
    config.output.jsonpFunction('frameworkWebpackJsonp')
  });
};
```
