### ISSUE TITLE
AppRouter在框架应用为hashtype时，pathname仍返回browserHistory

### ISSUE THREAD

**Issue by hi-liuyj** [ice-lab/icestark#151]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
onRouterChange(pathname)
这个callback在hash history时返回的是空串

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
直接起个模板，把router->type 置为 hash
**What is the expected behavior?**
返回hash history中的pathname

代码在这里：https://github.com/ice-lab/icestark/blob/master/src/AppRouter.tsx#L250
https://github.com/alibaba/ice/blob/e833cd48c3/packages/plugin-icestark/src/runtime.tsx#L121

看到一个issue，不知道是不是相关，https://github.com/ice-lab/icestark/issues/100

如果有需要，我可以提个PR

**Comment by ClarkXia** [comment]
欢迎 PR

关于 history 类型上，实践上的建议是要么框架应用和主应用均使用 browser，或者统一使用 hash。避免两种模式参数上的不一致而导致的问题

**Comment by ClarkXia** [comment]
返回的 pathname 是解析 url 获取的，同 history 上的 pathname 一致，如果是 router 类型是 hash 可以参考返回的 hash
