### ISSUE TITLE
希望支持子应用的缓存，返回上一个应用时，还原切换前的状态，类似Vue / keep-alive

### ISSUE THREAD

**Issue by rootsli** [ice-lab/icestark#155]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
不支持子应用的缓存
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**
- 支持某个子应用的缓存，切换回上一个子应用时，滚动条位置，tab选中状态，搜索条件等仍然保持切换前状态
- 切换回去时，提供一个回调函数，处理业务逻辑
- 类似Vue 的keep-alive功能

**Comment by ClarkXia** [comment]
目前子应用切换时不会保留子应用相关节点和状态，子应用的 appEnter 在每次匹配到该应用时都会触发
如果时希望保留子应用的页面状态，可以考虑本地持久存储的策略，比如使用 localstorage 进行页面状态的存储，以 icejs 中使用的状态管理方案为例：

```js
export default {
  // 定义 model 的初始 state
  state: {
    name: '',
    id: ''
  },
  reducers: {
    update (prevState, payload) {
      const state = {
       ...prevState,
        ...payload,
      };
      // 每次数据变化都将状态存储到 localStorage
      localStorage.setItem('state', JSON.stringify(state));
      return state;
    },
  },
};
```

每次页面初始化时，在执行 createApp 时都从 localStorage 中检查是否有初始专题数据

```js
import { createApp } from 'ice';

let initialStates =  {};

if (localStorage.getItem('state')) {
  initialStates.state = JSON.parse(localStorage.getItem('state'));
}

const appConfig = {
  store: {
    // 可选，初始化状态
    initialStates,

    // 已废弃
    // 可选，获取初始状态，在 SSR 场景下会将 getInitialData 返回的数据作为入参
    getInitialStates: (initialData) => {
      return initialData;
    };
  }
};

createApp(appConfig);
```

缺陷：需要还原的状态都需要本地存储起来，包括滚动条位置， 在组件挂载的时候读取数据进行初始化
