### ISSUE TITLE
按照文档快速上手搭建的框架应用并接入子应用，部署到nginx上，当访问 主框架域名/子应用路由 时，刷新页面会404

### ISSUE THREAD

**Issue by domsgit** [ice-lab/icestark#157]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
按照文档快速上手搭建的框架应用并接入子应用，部署到nginx上，当访问 主框架域名/子应用路由 时，刷新页面会404。当前使用的是browser模式。而且nginx的配置也配置了：

```
 location / {
        try_files $uri $uri/ /index.html;
 }
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
如上

**What is the expected behavior?**
部署线上nginx上，访问 主框架域名/子应用路由 时，刷新页面能正常路由到期望的界面。

**Comment by ClarkXia** [comment]
先确认 nginx 配置是否正常，如果配置正确，所有的路由都会显示 index.html 的内容
