### ISSUE TITLE
[icestark] please trigger app mount manually via registerAppEnter, app path: 

### ISSUE THREAD

**Issue by ruofeng086** [ice-lab/icestark#158]
![image](https://user-images.githubusercontent.com/14192308/92568437-c1a26500-f2b1-11ea-9949-cbebf1510bc9.png)
![image](https://user-images.githubusercontent.com/14192308/92568475-d3840800-f2b1-11ea-8cf7-e7e08a172ac8.png)
![image](https://user-images.githubusercontent.com/14192308/92568500-da127f80-f2b1-11ea-96df-005778f5798e.png)

**Comment by ruofeng086** [comment]
偶现的bug，请问下是配置不对吗？

**Comment by ruofeng086** [comment]
https://ice.work/docs/guide/advance/icestark
![image](https://user-images.githubusercontent.com/14192308/92577312-17c8d580-f2bd-11ea-88da-e6a6597e8f98.png)

https://ice.work/docs/icestark/guide/framework-app
![image](https://user-images.githubusercontent.com/14192308/92577377-257e5b00-f2bd-11ea-912b-aed39f00ef1c.png)

有两种文档，以那个为准？

**Comment by maoxiaoke** [comment]
引入了 ice，用前者；只引入 @ice/stark，用后者 @ruofeng086

**Comment by ruofeng086** [comment]
@maoxiaoke 那配置没错呢，还是没有找到原因所在，请问怎么解决？

**Comment by ClarkXia** [comment]
@ruofeng086 能提供下复现步骤和 demo 吗？

**Comment by ruofeng086** [comment]
@ClarkXia framework是用ice新搭建的，子项目是react项目改造来的

**Comment by ClarkXia** [comment]
> @ClarkXia framework是用ice新搭建的，子项目是react项目改造来的

提供下简单 demo，不然不好排查
