### ISSUE TITLE
主应用如何同时显示多个子应用的问题

### ISSUE THREAD

**Issue by Dean-ZhenYao-Wang** [ice-lab/icestark#164]
如何在主应用，通过Table选项卡的方式，同时显示多个子应用，或者同一个子应用的多个页面？

**Comment by ClarkXia** [comment]
如果多个子应用同时存在，并且子应用均有自己的路由逻辑时，对于整个路由系统的管理会显得复杂。
存在多应用共存问题时，推荐采用微模块的形式 https://github.com/ice-lab/icestark/tree/master/packages/icestark-module 进行设计
