### ISSUE TITLE
老项目是前后端不分离的， 现在要集成一个Vue的前后端分离的项目到老的项目里面； 这样的能否适用啊？

### ISSUE THREAD

**Issue by gaoquanbing-ausxin** [ice-lab/icestark#165]
老项目是前后端不分离的， 现在要集成一个Vue的前后端分离的项目到老的项目里面； 这样的能否适用啊？
@ClarkXia

**Comment by ClarkXia** [comment]
基本情况都可以适配微前端。主要涉及前端的改造，可以具体看下老项目的具体架构是什么样的
