### ISSUE TITLE
为什么我设置日志级别为none 但是info 却不打印信息到控制台呢?

### ISSUE THREAD

**Issue by liuguojin2017** [ice-lab/icestark#174]
文件路径 Z:\wy-fontweb\src\layouts\FrameworkLayout\index.tsx
useEffect(() => {
        console.log('APP_MODE', APP_MODE);
        console.log(config.logLevel);
        logger.info('info_info_info_info_info_info_info_info_info');
        logger.warn('warn_warn_warn_warn_warn_warn_warn_warn_warn');
        logger.error('error_error');
        console.log('== app leave ==', appLeave);
        if (appLeave.path === '/angular' && window.webpackJsonp) {
            // remove webpackJsonp added by Angular app
                delete window.webpackJsonp;
        }
    }, [appLeave]);

谷歌浏览器输出为

APP_MODE development
index.tsx:17 NONE
index.tsx:19 warn_warn_warn_warn_warn_warn_warn_warn_warn
index.tsx:21 == app leave == {}
index.tsx:29 == app enter == {}

warn 和error都输出了 为什么info没有输出到控制台?

**Comment by imsobear** [comment]
补充下 app.js 的内容

**Comment by liuguojin2017** [comment]
> 补充下 app.js 的内容

import * as React from 'react';
import { createApp, IAppConfig, config } from 'ice';
import { ConfigProvider } from '@alifd/next';
import PageLoading from '@/components/PageLoading';
import FrameworkLayout from '@/layouts/FrameworkLayout';

const appConfig: IAppConfig = {

    app: {

        rootId: 'icestark-container',
        addProvider: ({ children }) => (
            <ConfigProvider prefix="next-icestark-">{children}</ConfigProvider>
        ),
    },

    router: {
        type: 'browser',
    },
    icestark: {
        type: 'framework',
        Layout: FrameworkLayout,
        getApps: async () => {
            const apps = [
                {
                    path: '/seller',
                    title: '商家平台',
                    sandbox: true,//icestark 内置了基于 @ice/sandbox 的沙箱隔离，通过 sandbox 属性开启
                    // React app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-seller-react-16
                    url: [
                        '//ice.alicdn.com/icestark/child-seller-react/index.js',
                        '//ice.alicdn.com/icestark/child-seller-react/index.css',
                    ],
                    logger: {
                        level: config.loglevel,
                    },
                },
                {
                    path: '/waiter',
                    title: '小二平台',
                    sandbox: true,
                    url: [
                        // Vue app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-waiter-vue-2
                        '//ice.alicdn.com/icestark/child-waiter-vue/app.js',
                        '//ice.alicdn.com/icestark/child-waiter-vue/app.css',
                    ],
                },
                {
                    path: '/angular',
                    title: 'Angular',
                    sandbox: true,
                    // Angular app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-common-angular-9
                    entry:
                        '//ice.alicdn.com/icestark/child-common-angular/index.html',
                },
            ];
            return apps;
        },
        appRouter: {
            LoadingComponent: PageLoading,
        },
    },
    logger: {
        level: config.loglevel,
    }
};

createApp(appConfig);

**Comment by imsobear** [comment]
config.loglevel 是什么

**Comment by liuguojin2017** [comment]
> config.loglevel 是什么

NONE

**Comment by imsobear** [comment]
loglevel 的默认值是 warn，因此 info 不会打出来，你可以把 app.js 的 logger.level 改成 'info'

**Comment by liuguojin2017** [comment]
框架日志分为 NONE，DEBUG，INFO，WARN 和 ERROR 5 个级别，别在不同的场景下使用：
logger.trace(msg)：输出一个堆栈跟踪
logger.debug(msg)：输出一个调试日志
logger.info(msg)：输出一个信息日志
logger.warn(msg)：输出一个警告日志
logger.error(msg)：输出一个错误日志
我从设置none级别开始调试的 info以下的级别的都无法输出




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "大果"<notifications@github.com&gt;; 
发送时间: 2020年9月29日(星期二) 晚上7:28
收件人: "ice-lab/icestark"<icestark@noreply.github.com&gt;; 
抄送: "517945135"<517945135@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ice-lab/icestark] 为什么我设置日志级别为none 但是info 却不打印信息到控制台呢? (#174)





 
Closed #174.
 
&mdash;

**Comment by imsobear** [comment]
默认是 WARN，每个值的含义：

- ERROR：显示 error
- WARN：显示 warn&error
- INFO：显示 info&warn&error
- DEBUG：显示 debug&info&warn&error

默认值后续会有一个优化，参考：https://github.com/alibaba/ice/issues/3617

**Comment by liuguojin2017** [comment]
我理解这个设置逻辑 但是 设置为info&nbsp; 谷歌浏览器控制台 也不输出info的信息的....


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ice-lab/icestark"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月30日(星期三) 晚上9:21
收件人:&nbsp;"ice-lab/icestark"<icestark@noreply.github.com&gt;;
抄送:&nbsp;"517945135"<517945135@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ice-lab/icestark] 为什么我设置日志级别为none 但是info 却不打印信息到控制台呢? (#174)





 
默认是 WARN，每个值的含义：
  
ERROR：显示 error
 
WARN：显示 warn&amp;error
 
INFO：显示 info&amp;warn&amp;error
 
DEBUG：显示 debug&amp;info&amp;warn&amp;error
  
默认值后续会有一个优化，参考：alibaba/ice#3617

**Comment by chenbin92** [comment]
@liuguojin2017  文档错误不支持 loglevel 设置为 NONE，详见 [MR](https://github.com/alibaba/ice/pull/3620)

![image](https://user-images.githubusercontent.com/3995814/95545745-51623d00-0a31-11eb-8617-0d05ca90b00e.png)
