### ISSUE TITLE
迁移umi子应用

### ISSUE THREAD

**Issue by raxxarr** [ice-lab/icestark#175]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
在 umijs 子应用[接入教程](https://ice.work/docs/icestark/guide/child-app#UmiJS%20%E5%BA%94%E7%94%A8%E5%A6%82%E4%BD%95%E6%8E%A5%E5%85%A5)中，引入了 `import RouterWrapper from './pages/.umi/router';`
.umi/ 是一个开发环境的运行时文件，在云构建的时候应该不存在的吧？
![image](https://user-images.githubusercontent.com/7265362/94509072-06cd0d80-0246-11eb-8453-c340ad7d7d4f.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by ClarkXia** [comment]
跟 umi 具体的版本相关，如果使用 umi 3.0 可以参考链接中的方式接入 https://github.com/alibaba/ice/blob/docs/icestark-apis/docs/icestark/guide/fap.md#umijs-%E5%BA%94%E7%94%A8%E5%A6%82%E4%BD%95%E6%8E%A5%E5%85%A5

**Comment by LiXinLeLe** [comment]
> 跟 umi 具体的版本相关，如果使用 umi 3.0 可以参考链接中的方式接入 https://github.com/alibaba/ice/blob/docs/icestark-apis/docs/icestark/guide/fap.md#umijs-%E5%BA%94%E7%94%A8%E5%A6%82%E4%BD%95%E6%8E%A5%E5%85%A5

这个链接现在 404 了，有没有别的关于接入 umi 子应用的问答呀

**Comment by LiXinLeLe** [comment]
> > 跟 umi 具体的版本相关，如果使用 umi 3.0 可以参考链接中的方式接入 https://github.com/alibaba/ice/blob/docs/icestark-apis/docs/icestark/guide/fap.md#umijs-%E5%BA%94%E7%94%A8%E5%A6%82%E4%BD%95%E6%8E%A5%E5%85%A5
> 
> 这个链接现在 404 了，有没有别的关于接入 umi 子应用的问答呀

找到了https://ice.work/docs/icestark/guide/faq#UmiJS%20%E5%BA%94%E7%94%A8%E5%A6%82%E4%BD%95%E6%94%B9%E9%80%A0%E4%B8%BA%E5%BE%AE%E5%BA%94%E7%94%A8
