### ISSUE TITLE
本地开发时，框架应用中如何配置子应用的url？

### ISSUE THREAD

**Issue by edc-hui** [ice-lab/icestark#177]
按照icestark文档创建好框架应用和子应用之后，框架应用中的app.tsx文件中icestark配置项，配置子应用的url，该怎么写？（本地开发环境）

**Comment by edc-hui** [comment]
例如：框架应用启动之后是http://192.168.1.196:8000

**Comment by edc-hui** [comment]
例如：框架应用启动之后是http://192.168.1.196:8000。子应用启动之后是：http://192.168.1.196:2000

**Comment by ClarkXia** [comment]
配置子应用的方式可以参考 app.tsx 文件中 icestark 的 [getApps 配置项](https://ice.work/docs/guide/advance/icestark#%E6%A1%86%E6%9E%B6%E5%BA%94%E7%94%A8)
本地开发的时候可以通过一些 utils 方法动态修改加载的 bundle 地址，逻辑上可以参考 [如何进行本地调试](https://ice.work/docs/icestark/guide/child-app#%E5%AD%90%E5%BA%94%E7%94%A8%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91%E5%A6%82%E4%BD%95%E8%B0%83%E8%AF%95%EF%BC%9F)
