### ISSUE TITLE
命令行创建子应用中react版本问题？

### ISSUE THREAD

**Issue by edc-hui** [ice-lab/icestark#179]
通过文档命令行创建出来的react子应用的react版本是16.6.0版本，这个可以自行升级么？会不会有什么不好的影响？

**Comment by ClarkXia** [comment]
react 版本由自己控制，只要 API 层面不存在大的 breakchange 一般不会影响到微前端架构

**Comment by edc-hui** [comment]
我把react升级到16.14.0的时候不会有任何问题，但是升级到react 17.0.1的时候会报找不到react-router。如下图所示：

**Comment by edc-hui** [comment]
我把react升级到16.14.0的时候不会有任何问题，但是升级到react 17.0.1的时候会报找不到react-router。如下图所示：

**Comment by edc-hui** [comment]
<img width="830" alt="6E816D20-4CEB-4E2A-909E-3AD09227D2E8" src="https://user-images.githubusercontent.com/33356467/97128263-d8741c80-1776-11eb-82ef-c2bcce94ec85.png">

**Comment by edc-hui** [comment]
图片传不上来。我把错误信息复制下来。

**Comment by edc-hui** [comment]
图片上传不了 ，我把错误信息直接复制出来。
This dependency was not found:
react-router in ./.ice/runApp.ts
