### ISSUE TITLE
icestark 在拆分包的时候回导致加载不了 拆分的包

### ISSUE THREAD

**Issue by gooddaddy** [ice-lab/icestark#18]
子站点使用了类似的代码 会导致加载不了拆分的包
import React, { Suspense } from "react";

  <Suspense fallback={<PageLoading />}>
                      <Switch>
                        {children.map((routeChild, idx) => {
                          const {
                            redirect,
                            path: childPath,
                            component
                          } = routeChild;
                          return RouteItem({
                            key: `${id}-${idx}`,
                            redirect,
                            path: childPath && path.join(route.path, childPath),
                            component
                          });
                        })}
                      </Switch>
                    </Suspense>

**Comment by daysai** [comment]
Please use https://github.com/alibaba/ice/issues
Issues 相关请按照提示统一在https://github.com/alibaba/ice/issues上面提

**Comment by daysai** [comment]
> 子站点使用了类似的代码 会导致加载不了拆分的包
> import React, { Suspense } from "react";
> 
> <Suspense fallback={}>
> 
> {children.map((routeChild, idx) => {
> const {
> redirect,
> path: childPath,
> component
> } = routeChild;
> return RouteItem({
> key: `${id}-${idx}`,
> redirect,
> path: childPath && path.join(route.path, childPath),
> component
> });
> })}

Please use https://github.com/alibaba/ice/issues
Issues 相关请按照提示统一在 https://github.com/alibaba/ice/issues 上面提
加载不了拆分的包的原因，主要是 https://ice.work/docs/cli/config/config#publicPath 的配置问题。简单理解就是，因为子应用是嵌入式加载，因此域名是复用了框架应用的域名，需要修正相关的 publicPath
