### ISSUE TITLE
sandbox 属性开启报错

### ISSUE THREAD

**Issue by tiannengyu** [ice-lab/icestark#190]
> https://ice.work/docs/icestark/guide/sandbox#%E5%9F%BA%E4%BA%8E%20Proxy%20%E7%9A%84%E8%BF%90%E8%A1%8C%E6%B2%99%E7%AE%B1 通过 sandbox 属性开启即可
只需要在<AppRoute>中加一个属性就行了吗，不需要其他的操作吗？
我按文档加了
` <AppRoute
                            exact
                            sandbox
                            key={item.key}
                            path={allPath}
                            basename={item.path}
                            title={item.title}
                            entry={item.url}
                        />`

但报了错
`VM7529:379 Uncaught TypeError: Cannot set property 'source' of undefined
    at eval (eval at Sandbox.execScriptInSandbox (index.js?dd7b:197), <anonymous>:379:250619)
    at r (eval at Sandbox.execScriptInSandbox (index.js?dd7b:197), <anonymous>:10:195985)
    at eval (eval at Sandbox.execScriptInSandbox (index.js?dd7b:197), <anonymous>:10:196215)
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (eval at Sandbox.execScriptInSandbox (index.js?dd7b:197), <anonymous>:10:196185)
    at L (eval at Sandbox.execScriptInSandbox (index.js?dd7b:197), <anonymous>:10:197172)
    at eval (eval at Sandbox.execScriptInSandbox (index.js?dd7b:197), <anonymous>:10:197435)
    at Object.confirmTransitionTo (eval at Sandbox.execScriptInSandbox (index.js?dd7b:197), <anonymous>:10:195924)
    at D (eval at Sandbox.execScriptInSandbox (index.js?dd7b:197), <anonymous>:10:197390)
    at Object.E (eval at Sandbox.execScriptInSandbox (index.js?dd7b:197), <anonymous>:10:197309`

_Originally posted by @tiannengyu in https://github.com/ice-lab/icestark/issues/189#issuecomment-723904534_

**Comment by ClarkXia** [comment]
确认下不开启 sandbox 的情况下是否正常运行，如果正常麻烦提供下子应用 demo 以便复现

**Comment by tiannengyu** [comment]
> 确认下不开启 sandbox 的情况下是否正常运行，如果正常麻烦提供下子应用 demo 以便复现
不开启没有问题，这是我的入口文件
`import React from 'react'
import ReactDOM from 'react-dom'
import { Provider } from 'react-redux'
import { isInIcestark, getMountNode, registerAppEnter, registerAppLeave, getBasename } from '@ice/stark-app'
import { BrowserRouter as Router } from 'react-router-dom'
import axios from 'axios'
import { createBrowserHistory } from 'history'
import store from 'framework/store'
import RootRoutesView from '@/components/root'
import dialog from './dialog'

// 初始化工程
const projectInit = function (oContainer, callback = () => {}) {
    const history = createBrowserHistory()
    /*
     * 触发方式
     * 1. 引入import { Prompt } from 'framework/Util'
     * 2. 在路由组件内部渲染此组件<Prompt message="此API尚未发布，请确认是否离开?" when={whenFlag} />
     */
    const getConfirmation = (msg, cb) => {
        dialog.confirm({
            content: <div>{msg}</div>,
            ok(){
                cb(true)
                dialog.hide()
            },
            cancel(){
                cb(false)
                dialog.hide()
            }
        })
    }

    history.listen(() => {
        const { CancelToken } = axios
        window.projectConf.source = CancelToken.source()
    })

    const dom = () => (
        <Provider store={store}>
            <Router basename={getBasename()} browserHistory={history} getUserConfirmation={getConfirmation}>
                <RootRoutesView />
            </Router>
        </Provider>
    )

    if (isInIcestark()) {
        registerAppEnter(() => {
            ReactDOM.render(dom(), getMountNode(), callback)
        })
        registerAppLeave(() => {
            ReactDOM.unmountComponentAtNode(getMountNode())
        })
    } else {
        ReactDOM.render(
            dom(),
            oContainer,
            callback
        )
    }
}

export default projectInit
`
这是父应用的版本
`    "@ice/sandbox": {
      "version": "1.0.6",
    },
    "@ice/stark": {
      "version": "1.5.6",`
}
这是子应用的版本
`    "@ice/stark-app": {
      "version": "1.2.0",
    },
    "@ice/stark-data": {
      "version": "0.1.2",
    },`

**Comment by ClarkXia** [comment]
贴个 demo 的 github 地址吧，代码不全复现成本太高了
