### ISSUE TITLE
Vue项目改造后接入主框架（hashType），资源访问成功，但页面会自动跳转回首页'/'

### ISSUE THREAD

**Issue by woaizimmy** [ice-lab/icestark#198]
### Vue项目改造后接入主框架（hashType），资源访问成功，但页面会自动跳转回首页'/'

为了确保资源访问成功，修改了webpack配置，把css和js都构建到同一目录下，整个dist目录结构如下：

├── dist/
│   └── fonts/
│   └── img/
│   └── js/
│       ├── [0~20].js   # 0.js, 1.js,  ... 20.js, 一共21个js
│       ├── app.css
│       ├── app.js
├── favicon.ico
└── index.html

主框架注册了app.js和app.css两个url，打开子应用页面时，页面加载了app.js、app.css和20.js三个文件，Status Code都是200 OK，但页面会自动跳转回首页'/'。

不知道哪里出了问题，特来求助。

**Comment by ClarkXia** [comment]
可以从两个方面进行排查：
1. 页面跳转回首页的情况可以查看下是不是因为路由没有匹配的情况下跳回了首页，确认下主框架路由配置和子应用路由配置
2. 主应用的路由配置中确认下是否已添加获取 basename 的逻辑，可以参考 https://github.com/ice-lab/icestark-child-apps/blob/master/child-waiter-vue-2/src/router.js#L11

**Comment by woaizimmy** [comment]
感谢！
问题解决了。
或许是因为main.js中的 `new Vue` 配置不对，又或许是路由配置中缺少了`mode: 'history',`，但改成和child-waiter-vue-2的一致就OK了。

**Comment by woaizimmy** [comment]
确认了，路由配置中的 `mode: 'history',`不能缺少。
