### ISSUE TITLE
已有 jsp 项目能否使用 url 或 entry 方式接入主框架？

### ISSUE THREAD

**Issue by woaizimmy** [ice-lab/icestark#199]
如果可以的话，具体需要如何设置？

**Comment by ClarkXia** [comment]
按文档 https://ice.work/docs/icestark/guide/framework-app#%E5%AD%90%E5%BA%94%E7%94%A8%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5 进行配置即可
接入遇到问题，可以就问题再具体查看
