### ISSUE TITLE
主框架自身的页面，能否独立于BasicLayout之外？

### ISSUE THREAD

**Issue by woaizimmy** [ice-lab/icestark#200]
例如登录注册找回密码页面，往往是独立的页面，不需要嵌入layout中。
而目前的主框架，好像所有的页面都默认嵌入layout里了。
有没有办法让开发者把某个页面独立出来，当打开这个页面的时候，layout不加载，等路由调转到使用了layout的页面之后，再加载？

**Comment by ClarkXia** [comment]
参考下 https://github.com/alibaba-fusion/materials/blob/master/scaffolds/ice-stark-layout/src/layouts/FrameworkLayout/index.tsx#L13
