### ISSUE TITLE
[RFC] @ice/stark-module支持加载本地模块，以及支持模块替换

### ISSUE THREAD

**Issue by xyeric** [ice-lab/icestark#205]
## 目标
- 微模块框架支持加载 / 替换本地模块。
## 核心应用场景
1. 提供大型应用在多业务场景下的动态编排（业务定制）能力。
2. 页面局部模块的替换能力，平台应用预置的模块可被二、三方业务自定义实现。
## API 变化
- 增强 registerModules API，支持注册本地模块；增加options参数，支持通过options.force来强制覆盖已注册模块（用于远程模块覆盖本地模块的场景）。
- 增强 MicroModule，如果同一个 name 同时注册了本地模块和远程模块，优先加载远程模块。
### registerModules
注册微模块
```typescript
import { MicroModule, registerModules } from '@ice/stark-module';
import LocalModule from './components/LocalModule';
import AnotherLocalModule from './components/AnotherLocalModule';
registerModules([
  {
    render: () => <LocalModule />,
    name: 'module-a',
  },
  {
    render: () => <AnotherLocalModule />,
    name: 'module-b',
  },
  {
    url: 'https://localhost/another-remote-module.js',
    name: 'module-c',
  },
]);

// 通过加参数 force: true 强制替换已注册模块
registerModules([
{
    url: 'https://localhost/remote-module.js',
    name: 'module-a',
  }
], {
  force: true
});
```
### MicroModule
加载微模块
```typescript
const App = () => {
  // after registerMdoules, use micro module by specify module name
  return (
    <div>
      <!--  the remote-module will be loaded -->
      <MicroModule moduleName="module-a" />
      <!--  the AnotherLocalModule will be loaded -->
      <MicroModule moduleName="module-b" />
      <!--  the another-remote-module will be loaded -->
      <MicroModule moduleName="module-c" />
    </div>
  );
}
```
## 实现思路
- 模块注册：更新 registerModules 函数，支持解析 本地模块注册协议。
- 模块加载：更新 MicroModule 加载逻辑，优先加载远程模块，如只注册了本地模块，则直接渲染。
### 基于服务端配置驱动的模块编排
场景描述：设想有一个项目管理平台，预置了若干项目的管理流程节点，支持动态配置流程节点及加载二三方自定义节点。

![1607083658007-2b4cdbbc-426a-4f24-82e8-748dfb49f3a4](https://user-images.githubusercontent.com/5102113/101657767-3a66b800-3a7f-11eb-8c27-84a443c805a7.png)

代码实现：
```typescript
import { registerModules } from '@ice/stark';
import ProjectCreateForm from './components/ProjectCreateForm';
import ProjectConfigForm from './components/ProjectConfigForm';
// 注册需要动态编排/替换的本地模块
registerModules([
  {
    render: () => <ProjectCreateForm />,
    name: 'project-create-form',
  },
  {
    render: () => <ProjectConfigForm />,
    name: 'project-config-form',
  },
]);
/*
业务自行约定的服务端编排配置协议
const defaultConfig = {
  tabs: [{
    title: '创建项目',
    moduleName: 'roject-create-form',
    // ...other configs
   }, {
    title: '项目拆解',
    moduleName: 'roject-config-form',
   }, {
    title: '人员配置',
    url: '//remote-module-url',
   }],
};
*/
const remoteConfig = fetch('//remote-config-url');
// 解析编排配置，并注册远程模块
const remoteModules = remoteConfig.tabs.filter(i => i.url).map(({ url, moduleName }) => { url, name: moduleName });
registerMoudles(remoteModules, { force: true });

// 根据编排协议动态渲染模块
const App = () => {
  return (
    <Step>
      {finalConfig.tabs.map(({ title, moduleName, ...otherProps }) => {
        <Step.Item title={title}>
          <MicroModule name={moduleName} {...otherProps } />
        </Step.Item>
      })}
    </Step>
  );
}
```
## 补充优化方案
业务代码中直接引入微模块存在以下缺点：
- 业务侵入性较高，代码语义较差。
- 微模块源码不可索引、跳转，研发体验比较差。

在模块替换的场景下，优化方案的思路是：

本地开发直接引入/渲染本地模块，构建时通过babel插件将本地模块替换为微模块。

注：该方案只在远程模块和主应用采用相同React运行时环境的场景下实验通过，当远程模块和主应用采用不同的运行时环境是可能存在意想不到的问题，比如远程模块不能实时根据 props 变化重新渲染等。

本地开发示例：
```typescript
import { registerModules } from '@ice/stark';
import LocalModule from './components/LocalModule';
import ProjectCreateForm from './components/ProjectCreateForm';
import ProjectConfigForm from './components/ProjectConfigForm';
// 拉取并注册远程模块，可在应用入口中实现，降低侵入性。
const remoteModules = fetch('//remote-config-url');
registerModules([ ...remoteModules ], { force: true });
// 注意下面本地模块的加载方式
const App = () => {
  return (
    <Step>
      <Step.Item title="项目创建">
        <ProjectCreateForm mciro-module="project-create-form" {...props} />
      </Step.Item>
      <Step.Item title="项目拆解">
        <ProjectConfigForm mciro-module="project-config-form" {...props} />
      </Step.Item>
    </Step>
  );
}
```
构建后的代码：
```typescript
import { registerModules, MicroModule } from '@ice/stark';
import LocalModule from './components/LocalModule';
import AnotherLocalModule from './components/AnotherLocalModule';
// 自动注入本地模块注册代码
registerModules([
  {
    render: () => <ProjectCreateForm />,
    name: 'project-create-form',
  },
  {
    render: () => <ProjectConfigForm />,
    name: 'project-config-form',
  },
]);
const remoteModules = fetch('//remote-config-url');
registerModules([ ...remoteModules ], { force: true });
const App = () => {
  return (
    <Step>
      <Step.Item title="项目创建">
            <!-- 自动替换本地模块为微模块 -->
        <MicroModule mciro-module="project-create-form" {...props} />
      </Step.Item>
      <Step.Item title="项目拆解">
        <MicroModule mciro-module="project-config-form" {...props} />
      </Step.Item>
    </Step>
  );
}
```
Babel插件关键代码实现：
```typescript
const MICRO_MODULE = 'MicroModule';
const MICRO_MODULE_NAME_PROPS = 'micro-module';

const visitor = {
  Program: {
    exit(path, state) {
      if (injectMap[state.filename]) {
        const importDec = t.importDeclaration(
          [
            t.importSpecifier(t.identifier(MICRO_MODULE), t.identifier(MICRO_MODULE)),
          ],
          t.stringLiteral('@ice/stark-module'),
        );
        path.node.body.unshift(importDec);
      }
    },
  },
  JSXElement: {
    enter(path, state) {

      const openingElement = path.get('openingElement');
      if (!openingElement) return;
      const attrs = openingElement.node.attributes || [];
      if (!attrs.length) return;
      const opts = state.opts || {};
      const injectProps = attrs.filter((attr) => matchAttribute(attr, MICRO_MODULE_NAME_PROPS));
      if (!injectProps.length) return;
      injectProps[0].name = t.jsxIdentifier('name');
      if (openingElement.node.name.type === 'MemberExpression') {
        const componentName = openingElement.node.name.object.name;
        const componentNameProp = openingElement.node.name.property.name;
        const componentNameObj = t.memberExpression(t.Identifier(componentName), t.Identifier(MICRO_MODULE_NAME_PROPS));
        const componentNameAttr = t.jsxAttribute(t.jsxIdentifier('component'), t.jsxExpressionContainer(componentNameObj));
        attrs.push(componentNameAttr);
      } else if (openingElement.node.name.type === 'JSXIdentifier') {
        const componentName = openingElement.node.name.name;
        const componentNameAttr = t.jsxAttribute(t.jsxIdentifier('component'), t.jsxExpressionContainer(t.identifier(componentName)));
        attrs.push(componentNameAttr);
      }
      const wrapperOpeningElement = t.jsxOpeningElement(
        t.jsxIdentifier(MICRO_MODULE),
        attrs,
      );
      const wrapperClosingElement = t.jsxClosingElement(
        t.jsxIdentifier(MICRO_MODULE),
      );
      const { children } = path.node;
      const wrapperJsxElement = t.jsxElement(wrapperOpeningElement, wrapperClosingElement, children);
      path.replaceWith(t.inherits(wrapperJsxElement, path.node));
      injectMap[state.filename] = true;
    },
  },
};
```

**Comment by ClarkXia** [comment]
本地调试的方案中，会存在一些渲染逻辑的差异，微模块是以 ReactDOM 独立渲染的方式挂载以及默认创建一个 html 节点作为模块容器

**Comment by ylfeng250** [comment]
微模块的替换是否可以考虑加入React.Node类型，这样可以在低代码平台接入的时候可以降低组件替换的成本。

**Comment by xyeric** [comment]
> 本地调试的方案中，会存在一些渲染逻辑的差异，微模块是以 ReactDOM 独立渲染的方式挂载以及默认创建一个 html 节点作为模块容器


对于加了micro-module的模块，本地调试和构建发布后的逻辑是会保持一致的，即使是开发调试阶段，本地模块也是会被转换成微模块进行渲染的。

上述的差异主要体现在加了micro-module的模块和不加micro-module的模块之间。采用这个方案的前提就是要清楚，加了micro-module 就代表模块会被转换成微模块。

本地调试的方案主要还是想提供一个开发体验优化的思路，官方的方案里可以不提供转换的插件，如果觉得在具体的场景下这个方案能够带来开发体验的提升，并且不介意上述渲染逻辑的差异，可以基于这个思路自行实现一个babel 插件。

**Comment by xyeric** [comment]
@ylfeng250 不太清楚具体的使用场景，可以把思路和设计方案贴一下

**Comment by ylfeng250** [comment]
除了local、remote之外加一个node
```
interface IComponentConfig<P> {
  /**
   * 替换组件的名称
   */
  name: string;
  /**
   * 本地组件替换
   */
  local?: React.ComponentType<P>;
  /**
   * 远程 umd bundel替换
   */
  remote?: string;
  /**
   * 本地 reactnode
   */
  node?: JSX.Element;
}
```
remote加载的umdbundle使用ice-strak-module加载，local直接是React.createElement，reactnode类型直接返回
```
if (config?.remote) {
    const moduleInfo = {
      name: name,
      url: [config.remote],
      mount: (RemoteComponent: React.ComponentType, mountNode: Element | DocumentFragment | null) => {
        ReactDOM.render(<RemoteComponent {...otherProps}>{children}</RemoteComponent>, mountNode);
      },
      unmount: (targetNode: Element | DocumentFragment) => {
        ReactDOM.unmountComponentAtNode(targetNode);
      },
    };

    return <MicroModule moduleInfo={moduleInfo} />;
  }

  if (config?.local) {
    return React.createElement(config.local, otherProps, children);
  }
  if (config?.node) {
    return config?.node;
  }
```
增加node 的好处是在低代码平台导入的时候，在外层组件通过props暴露可以替换的组件，这样就可以天然使用低代码的方式搭建出一个可替换的模块。

**Comment by iyanming** [comment]
这个已经上线了吗，没看到是哪个版本的啊

**Comment by iyanming** [comment]
求子模块例子，一直报错，SyntaxError: Unexpected token '<'

**Comment by maoxiaoke** [comment]
@iyanming 报错的项目可以贴一下吗？目前这个功能正在 beta 中

**Comment by iyanming** [comment]
**主入口：也就是引用微模块的入口文件**
`import React from 'react';
import { Link } from 'ice';
import { MicroModule, registerModules, getModules } from '@ice/stark-module';
import LocalModule from '@/components/LocalModule/index';

registerModules([
  {
    render: () => <LocalModule />,
    name: 'module-a',
    mount: (ModuleComponent, mountNode) => {
      console.log('custom mount',ModuleComponent,mountNode);
      ReactDOM.render(<ModuleComponent />, mountNode);
    },
  },
]);

const About = () => {
  return (
    <div>
      <h1>About page</h1>
      <div><Link to="/">Home</Link></div>
      <MicroModule moduleName="module-a" />
      <div><Link to="/seller/list">sellerlist</Link></div>
    </div>
  );
};

export default About;
`
**本地微模块代码：**
`import React from 'react';

const LocalModule = () => {
    console.log('111');
    return <div style={{ paddingTop: 200, textAlign: 'center' }}>
            111
        </div>;
};

// mount function will be trigger when mount micro module
export function mount(ModuleComponent, targetNode, props) {
    ReactDOM.render(<ModuleComponent {...props} />, targetNode);
}

// unmount function will be trigger when unmount micro module
export function unmount(targetNode) {
    ReactDOM.unmountComponentAtNode(targetNode);
}

export default LocalModule`

**报错信息如下：**
![截屏2021-03-23 16 31 04](https://user-images.githubusercontent.com/23701391/112116390-35281600-8bf5-11eb-819e-e35e911af808.png)

项目由官方脚手架创建， npm init ice icestark-layout @icedesign/stark-layout-scaffold
但是由于微应用与路由耦合，故想用微模块，实现多个页面在同一路由下展示。
自己新安装依赖，"@ice/stark-module": "^1.3.0"
就有了上面问题，感谢大佬帮忙查看～
@maoxiaoke @xyeric

**Comment by maoxiaoke** [comment]
@iyanming  @ice/stark-module@1.4.0-1 目前这个功能在 beta 中，用这边版本试用下

**Comment by iyanming** [comment]
@maoxiaoke  这个版本可以了，你们这个大概什么时候上线啊

**Comment by iyanming** [comment]
还有这个react、vue版的微模块都可以支持吗

**Comment by maoxiaoke** [comment]
@iyanming 预计这周可以上线

**Comment by maoxiaoke** [comment]
@iyanming 支持

**Comment by iyanming** [comment]
@maoxiaoke  可以提供个这样的微模块url地址提供我们调试吗
```
registerModules([
  {
    url: 'https://localhost/module-a.js',
    name: 'module-a',
  },
  {
    url: 'https://localhost/module-b.js',
    name: 'module-b',
  },
]);
```
里面的url参数

**Comment by iyanming** [comment]
希望得到加载远程微模块的更多细节和文档，远程微模块如何打包之类的

**Comment by maoxiaoke** [comment]
@iyanming 暂时可以参考下 https://github.com/ice-lab/icestark/tree/master/packages/icestark-module 这里，近期 ice 官网会上线详细文档

**Comment by maoxiaoke** [comment]
@ice/stark-module 1.4.0 support this feature.

**Comment by iyanming** [comment]
ice 官网大概什么上线详细 文档啊～  @maoxiaoke   新版本已经看到了，已更新，但是目前用umd打包出来的组件，使用微模块加载进来的话会报错  
index.js:1 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by iyanming** [comment]
看到官网已经更新文档了，但是用这个命令安装会报错，麻烦看下。
npx iceworks init component @icedesign/template-icestark-module 
![截屏2021-03-26 17 02 35](https://user-images.githubusercontent.com/23701391/112608737-a5cd6d80-8e55-11eb-905e-6a1d78663be2.png)

**Comment by maoxiaoke** [comment]
@iyanming 需要周一发布下了 https://github.com/ice-lab/material-templates/pull/53，我这边先提供一个 demo 给你 
[icestark-module.zip](https://github.com/ice-lab/icestark/files/6212128/icestark-module.zip)

**Comment by iyanming** [comment]
是不是还没有发布啊  @maoxiaoke

**Comment by iyanming** [comment]
请问微模块可以用vue写吗，或者已有项目如何改造成一个微模块供其他地方使用
