### ISSUE TITLE
icestark 应用资源加载生命周期

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/icestark#208]
icestark 提供了 onAppEnter 和 onAppLeave 等应用渲染和卸载相关的生命周期。
但基于一些资源加载性能和监控的需求，是否需要提供一些便捷的钩子来处理资源加载前和资源加载后的一些处理

**Comment by skyFi** [comment]
举个例子：人为干预window加载事件：在某些情况下，先加载了shell层，然后再window.onload之后加载子应用的资源，此时，子应用中可能存在部分逻辑在window.onload中，这种情况下这部分逻辑就永远不会走到，如果能知道子应用资源加载完成时间，可以通过手动触发onload事件来执行这部分逻辑

**Comment by maoxiaoke** [comment]
@skyFi 请使用 icestark 2.x，2.x 版本提供了 onLoadingApp 和 onFinishLoading 勾子可用于处理资源加载前后
