### ISSUE TITLE
采用加载 html 资源的方式，如何处理缓存

### ISSUE THREAD

**Issue by yuxiuj** [ice-lab/icestark#213]
采用加载 html 资源的方式加载子应用

当子应用更新时，因为 disk cache 的缓存策略，无法获取到最新的 html 资源

期望子应用变化的时候，主应用可以加载最新的 html 资源

**Comment by maoxiaoke** [comment]
@yuxiuj 打开 开发工具 -> 网络 -> 开启 Disable cache

**Comment by yuxiuj** [comment]
@maoxiaoke 这种方法对于非开发者不是很友好，设置 html 文件的<meta http-equiv="Cache-control" content="no-cache"> 头部是否有效呢？

**Comment by yuxiuj** [comment]
设置 meta 标签的 Cache-control 为 no-cache

**Comment by yuxiuj** [comment]
@maoxiaoke 感觉这个解决办法对非开发人员是不友好的，是否可以在 fetch 发起请求 html 资源的时候，设置 "Cache-control": "no-cache"，不去缓存资源？

**Comment by maoxiaoke** [comment]
@yuxiuj 这个需要资源服务器上设置
