### ISSUE TITLE
手动加载微应用时，切换路由子应用不加载

### ISSUE THREAD

**Issue by linshaoye12345** [ice-lab/icestark#222]
手动加载微应用时，刷新浏览器时可加载微应用，切换路由时不能加子应用。

[主应用dmo.zip](https://github.com/ice-lab/icestark/files/5780699/dmo.zip)
[子应用dmoicestark-child.zip](https://github.com/ice-lab/icestark/files/5780701/dmoicestark-child.zip)

**Comment by maoxiaoke** [comment]
使用官方项目执行 createMicroApp 会有一点问题，我们会尽快修复 @linshaoye12345
