### ISSUE TITLE
使用已有react项目改造微应用，注册到框架应用后子应用页面空白，资源加载正常，微应用按照文档改造

### ISSUE THREAD

**Issue by leiyily** [ice-lab/icestark#224]
使用已有react项目改造微应用
注册到框架应用后子应用页面空白，
资源加载正常，
微应用按照文档改造
框架应用sh是code 里面的 gt-umacweb
子应用是tyc-web
[code.zip](https://github.com/ice-lab/icestark/files/5786435/code.zip)

**Comment by maoxiaoke** [comment]
@leiyily 子项目进行了 splitChunk，需要移除掉 splitchunk 设置，或将 chunks 文件添加到主应用的 url 中

**Comment by maoxiaoke** [comment]
add an example for you. https://github.com/maoxiaoke/icestark-demos/tree/master/cra-api-umd/react16-child @leiyily
