### ISSUE TITLE
vue子应用可以渲染但无法成功显示（icestark-loading display=none）

### ISSUE THREAD

**Issue by YimingXieUSC** [ice-lab/icestark#229]
**Do you want to request a *feature* or report a *bug*?**
使用icestark layout连接子应用时浏览器内可以成功渲染资源，但因为一个叫做icestark-loading的parent node的display设置成了none，导致页面一直显示loading，无法显示子应用界面。
![icestark子应用](https://user-images.githubusercontent.com/68513408/104584126-080f3280-569d-11eb-9fc4-ec4cbd382476.png)
![icestark-layout截图](https://user-images.githubusercontent.com/68513408/104584144-11000400-569d-11eb-8aba-e02aafc14e2e.png)

**Comment by maoxiaoke** [comment]
@YimingXieUSC  icestark-loading 这个，在哪里声明的？方便提供 vue 子应用 demo 吗？

**Comment by maoxiaoke** [comment]
Anyway feel free to feedback

**Comment by YimingXieUSC** [comment]
[webpack-vue.zip](https://github.com/ice-lab/icestark/files/5864198/webpack-vue.zip)
这个是vue的子应用，icestark-loading并没有声明，注册之后主应用自行显示的。
