### ISSUE TITLE
支持应用之间通信方案

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icestark#23]
## 背景

- 子应用之间通信（补充具体 case）

- 子应用与框架应用通信（补充具体 case）

## 方案

提供统一的数据流转中心，事件监听，回调函数设置等基础逻辑的封装

```javascript
import { store, event } from '@ice/stark-data';

// 初始化
store.set('status', '')

// 获取数据
const status = store.get('status')

// 更新数据
store.set('status', 'newStatus')

// 监听数据变化
store.on('status', data => {
  console.log(data);
}, true)


// 触发事件执行，可传递任意个参数
event.emit('event', 'test', 'test2')

const listener = (a, b) => {
    // do something
    console.log(a) // 'test'
    console.log(b) // 'test2'
}
// 监听事件
event.on('event', listener)

// 移除监听
event.off('event', listener)
// 移除该事件的所有监听器
event.off('event')

// 检查某个事件是否被监听
event.has('event')
```

## 场景分析

- 子应用页面切换参数流转

```javascript
import { store, event } from '@ice/stark-data';

// 子应用A设置信息
store.set('from', 'A');
store.set('current', 0);

// 子应用B读取信息
const from  = store.get('from');
const current = store.get('current');
```

- 中英文切换，切换按钮在框架应用，监听事件在子应用
- 登录信息前端互通，子应用确认框架应用登录后，前端不再重复发起登录请求相关逻辑；登录用户信息保存在框架应用中，子应用获取用户数据
- 框架应用顶部有 ”消息“ 展示入口，子应用内有阅读消息的能力，阅读完消息后需要通知框架应用刷新“消息”展示信息

```javascript
import { store, event } from '@ice/stark-data';

// 框架应用

store.set('language', 'CH'); // 设置语言
store.set('user', currentUser); // 设置登录后当前用户信息
event.on('message', () => { // 监听刷新信息事件
     // 调用刷新信息接口
});


// 子应用

// 监听语言变化
store.on('language', language => {
      console.log(language);
      // 切换成中文回调
      // ...
}, true);

// 获取当前用户
const currentUser = store.get('user');

// 触发刷新信息
event.emit('message');
```

**Comment by daysai** [comment]
### 关于是否保留 event 的想法
有关 event 和 store 都有 on 的注册事件实现回调的机制，考虑是否删除 event ，只保留 store 方法。
#### 优势
- 单一 api 能进一步降低理解成本和使用成本
#### 差异
后面考虑 event.on 和 store.on 注册事件的方式还是有差异的：
- event.on 是主动注册事件，并先定好回调函数，等待调用。**如例子中的框架应用事先注册好刷新“消息”事件，等待子应用调用**。
- store.on 是发起监听某个全局变量的变化，自行根据变量值处理自己逻辑。**如例子中的框架应用切换语言，不同子应用监听语言变化，自行处理自己的回调逻辑**。
#### 暂定保留

**Comment by imsobear** [comment]
事件这块可以考虑直接用这个库：https://github.com/developit/mitt 挺有意思的

**Comment by imsobear** [comment]
另外，按照这个实现的话，感觉这个包都可以作为一个通用包了，跟之前说的 iframe 那个一样。。。

**Comment by daysai** [comment]
icestark-app 代码已实现，详见：[分支: release/1.1.1](https://github.com/ice-lab/icestark/tree/release/1.1.1)
