### ISSUE TITLE
使用history跳转，布局组件没有渲染，手动刷新后出来

### ISSUE THREAD

**Issue by leiyily** [ice-lab/icestark#234]
[demo.zip](https://github.com/ice-lab/icestark/files/5835055/demo.zip)
详见代码，login页面点击登陆就可以复现

**Comment by maoxiaoke** [comment]
代码没有复现 @leiyily

**Comment by leiyily** [comment]
[demo1.zip](https://github.com/ice-lab/icestark/files/5835587/demo1.zip)
您重新试下，点完登陆是
![image](https://user-images.githubusercontent.com/30883546/105029794-c4963900-5a8d-11eb-9a7e-fc82adfb549a.png)
刷新一下会这样
![image](https://user-images.githubusercontent.com/30883546/105029979-0d4df200-5a8e-11eb-977a-9142cb749f19.png)
期望是点击登陆后就这样

**Comment by leiyily** [comment]
@maoxiaoke 应该是这块的问题，history切换路由后，没有监测到路由变化去更新渲染的布局组件
![image](https://user-images.githubusercontent.com/30883546/105113605-34dda280-5b00-11eb-86cd-7beaa3f90295.png)

**Comment by leiyily** [comment]
@maoxiaoke 我用官方的demo试了下，从登陆页面跳转到首页这两个布局组件切换也有这个问题，BasicLayout没有正常渲染
