### ISSUE TITLE
支持基本 js 隔离、js 内存回收

### ISSUE THREAD

**Issue by daysai** [ice-lab/icestark#24]
## 背景

- 当前浏览器环境下，完善的 js 间隔离的方案还没有。worker进程、iframe都有各自的缺陷
- icestark 作为不同应用的容器承载，应当具备基本的隔离能力，也是多方的共同需求

## 方案

插件机制支持快照功能
1. hijack window.addEventListener/window.removeEventListener
2. hijack window.setInterval/window.setTimeout
3. hijack window.history.listen

**Comment by daysai** [comment]
计划 1.1.1 版本迭代

**Comment by daysai** [comment]
调研了集团内的 “iframe” 方案
#### 优势
- 隔离效果较好，通过复用 iframe 的运行时环境，而不是直接运行在 iframe 中
- 因为没有直接运行 iframe 中，没有复用链接池问题，性能相比直接粗暴的iframe方案有优化
#### 缺点
- 需要进行js、css资源 fetch 化改造，fetch 就会有跨域等问题，非 icestark 理想的运行方式
- 整个隔离方案较重。隔离代码量比 @ice/stark 主包都要重
- 对目前一些通信等方案都需要改造
#### 结论
暂定使用较浅的隔离方案，针对部分全局变量进行劫持

**Comment by wufeng87** [comment]
@daysai 请问下，您说的较浅的隔离方案能支持ie11吗？您说的是只针对那些全局变量进行劫持？

**Comment by ClarkXia** [comment]
1.5.0 版本已支持基于 Proxy 的沙箱执行环境
