### ISSUE TITLE
子应用配置不需要通过 umd: true 显示区分

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/icestark#240]
icestark 2.0 支持 umd 和 非 umd 的子应用接入，目前在使用上会造成一些困惑。比如：如果子应用是 umd 方式加载，需要在主应用中指定 umd: true，容易产生一些认知成本和使用成本。

**Comment by imsobear** [comment]
icestark 1.x 也是这个逻辑哈

**Comment by maoxiaoke** [comment]
产生差异点分析：

目前 umd 方式加载是推荐的方式，但是示例项目中，使用的是非 umd 加载的方式；同时子应用项目是使用 umd 打包，所以产生一些 gap。

措施一：修改官方示例项目，保持方式统一
措施二：通过加载资源的方式，判断资源的加载类型。改动点，通过 getGlobalProp 来判断加载后是否是 umd 的方式

**Comment by ClarkXia** [comment]
目前通过 loadMode 判断的结果通过 console.warn 输出，比较容易忽略，错误信息建议直接显示在页面中

**Comment by imsobear** [comment]
什么时候先提个 RFC？

**Comment by maoxiaoke** [comment]
针对上述问题以及讨论，修改方案如下：

1. 官方示例项目均修改为使用推荐的 umd 方式加载：修改 [脚手架模板](https://github.com/alibaba-fusion/materials/tree/master/scaffolds/ice-stark-layout) 

2. 通过 loadMode 的判断结果通过 error 输出

**Comment by imsobear** [comment]
有没有可能做到不需要配置 umd: true ？

**Comment by maoxiaoke** [comment]
@imsobear https://github.com/ice-lab/icestark/issues/240#issuecomment-773933687 这里措施二，提供了一个可行的策略。方案下需要将所有通过 jsonp 获取资源的方式，通过 fetch 的方式获取，会产生 break change，可能导致的影响是：

- 之前不跨域的应用，可能产生跨域
- ie 应用由于不支持 fetch，会造成应用崩溃

**Comment by maoxiaoke** [comment]
# 子应用配置不需要通过 umd: true 显示区分

## 背景


## 方案设计
#### 方案变更
目前 icestark js资源获取混合 JSONP 和主动 fetch 两种方式。逻辑如下：
![jsonp](https://user-images.githubusercontent.com/13417006/108818375-3bc26e00-75f4-11eb-9194-2f1a299584a2.jpg)



改逻辑变更如下


- 当 `umd` 显示指定为 true/false，保持目前加载方式不变
- 当 `umd` 未显示指定（同时未开启沙箱模式），框架使用 JSONP 的方式加载 js 资源



逻辑如下：

![umd](https://user-images.githubusercontent.com/13417006/108818322-26e5da80-75f4-11eb-8c3f-df526cf6287b.jpg)



在使用 icestark 中，我们推荐不设置 umd


### api 变更
#### @ice/stark-app 新增 setLibraryName 和 getLibraryName 方法


在方法用于在加载子应用时指定 umd 资源挂载到 window 的变量
```javascript
// 子应用
import { setLibraryName } from '@ice/stark-app';

setLibraryName('seller');

export function  mount () {
	...
}
  
 export function unmount () {
 	...
 }
```


#### umd 加入 @deprecated


#### 其他

1. 修改官方 demo，移除 umd 设置
1. 修改 build-plugin-icestark，默认为 ice 体系用于注入 library name
