### ISSUE TITLE
主应用和子应用都基于Vue技术栈，使用hash模式无效

### ISSUE THREAD

**Issue by vincentSea** [ice-lab/icestark#264]
目前主应用和子应用都基于Vue技术栈，使用hash模式无效，其中router也已经设置hash模式，主要配置文件如下：
![image](https://user-images.githubusercontent.com/16203604/110470556-f59dfc00-8115-11eb-9777-4f09f76db31f.png)

**Comment by maoxiaoke** [comment]
@vincentSea 可以提供下 demo 复现下，你也可以通过下面的途径进行基本的排查：

1. 子应用是否加载
2. 若子应用正常加载，子应用路由是否正确匹配

**Comment by maoxiaoke** [comment]
pleased to reopen if you are still in trouble.

**Comment by jieliu** [comment]
@maoxiaoke 你好，vue主应用开启hash模式后，子应用点击后没有响应，页面右侧空白，控制台没有错误信息

下面是我的项目创建方式

1.  npm init ice icestark-layout @vue-materials/icestark-layout-app 创建vue主应用

2. 修改 router的路由模式
const router = new VueRouter({
  **mode: 'hash',**
  routes: [
    {
      path: '/',
      name: 'home',
      component: Home
    },
    {
      path: '/about',
      name: 'about',
      component: About,
    },
    {
      path: '/login',
      name: 'login',
      component: Login,
    },
    {
      path: '*',
      name: 'notfound',
      component: NotFound,
    }
  ]
})

3. 修改子应用路由模式
  mounted() {
    const container = document.getElementById('container');
    registerMicroApps([
      {
        name: 'seller',
        activePath: '/seller',
        title: '商家平台',
        sandbox: true,
        **hashType: true,**
        // React app demo: https://github.com/alibaba-fusion/materials/tree/master/scaffolds/ice-stark-child
        url: [
          'https://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-seller-react/build/js/index.js',
          'https://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-seller-react/build/css/index.css',
        ],
        container,
      }, {
        name: 'waiter',
        activePath: '/waiter',
        title: '小二平台',
        sandbox: true,
        **hashType: true,**
        // Vue app demo: https://github.com/ice-lab/vue-materials/tree/master/scaffolds/icestark-child-app
        url: [
          'https://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-waiter-vue/dist/js/app.js',
          'https://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-waiter-vue/dist/css/app.css',
        ],
        container,
      }, {
        // TODO: Angular
        name: 'angular',
        activePath: '/angular',
        title: 'Angular',
        sandbox: true,
        **hashType: true,**
        // Angular app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-common-angular
        entry: 'https://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-common-angular/index.html',
      }
    ]);

**Comment by maoxiaoke** [comment]
@jieliu 页面空白，但是控制台没有错误信息，通常是微应用路由没有匹配上
