### ISSUE TITLE
@ice/stark-data如何处理子应用未初始化on的情况

### ISSUE THREAD

**Issue by xmsz** [ice-lab/icestark#270]
流程
- 父应用触发emit
- 但是由于子应用还没加载完或者其他情况，导致显示
```
event.emit: no callback is called for history
```

需求
- 如何优雅的处理这种情况
- 希望可以拦截这个错误，例如我可以直接tryCatch下来错误然后延迟执行，但是现在不行，拦截不到错误
-

**Comment by maoxiaoke** [comment]
可以在子应用的 onFinishLoading 时机，该时机为：子应用加载完成。可在该时机标记应用加载状态。

**Comment by maoxiaoke** [comment]
pleased to reopen if you are still in trouble.

**Comment by xmsz** [comment]
> 可以在子应用的 onFinishLoading 时机，该时机为：子应用加载完成。可在该时机标记应用加载状态。

这样是可以 但是有点变麻烦了 子应用还需要记录状态并且还需要改动到原有代码

然后希望的是，比如至少可以catch到错误，或者能传个失败回调啥的，这样比较简单而且符合原则

或者emit可以是个Promise，或者传递一个重试参数啥的

当然有更优雅的方式更好哈


不过我现在先用延时+重试也行 影响不大 就是有点傻
