### ISSUE TITLE
fetch polyfill 支持

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/icestark#279]
icestark 内部使用 fetch，fetch 目前在 ie11 以下浏览器均不支持。改进措施:

<del>1. build-plugin-icestark 提供 `fetchPolyfill` 字段，默认关闭。开启时，追加 fetch 的 polyfill </del>
2. 文档优化

**Comment by imsobear** [comment]
「开启时，追加 fetch 的 polyfill」要实现这个功能吗？感觉不太合理。

**Comment by imsobear** [comment]
添加 polyfill 需要的话可以作为 icejs 通用的能力，单点的 icestark 插件做这个事情不合理。

**Comment by maoxiaoke** [comment]
@ClarkXia icejs 有支持 polyfill 的能力吗？

**Comment by maoxiaoke** [comment]
有关 icestark 支持 ie 浏览的相关问题，请参考官方文档 https://ice-lab.github.io/icestark/faq#%E5%85%BC%E5%AE%B9-ie-%E6%B5%8F%E8%A7%88%E5%99%A8
