### ISSUE TITLE
README 中文版本

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icestark#28]
## 问题描述

点击「简体中文」是去到了官网文档，有点懵逼的感觉，不符合 GitHub 上常见 README 的组织方式，而下面也还有个 Website docs 的链接。

![image](https://user-images.githubusercontent.com/3995814/68272596-2217b300-009f-11ea-8a52-7f82ea2a5196.png)

## 个人建议

「English | 简体中文」 中的「简体中文」应该对应的是当前 README 英文的中文翻译

**Comment by daysai** [comment]
此问题非紧急问题，安排在 release 1.1.2 （20191122）迭代中优化
