### ISSUE TITLE
IE11下子应用js经常加载失败（偶现非必现），Chrome下正常

### ISSUE THREAD

**Issue by rootsli** [ice-lab/icestark#280]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
最近在做IE兼容性适配，参考https://github.com/alibaba/ice/issues/3661#issuecomment-736217375进行升级，依赖包版本如下：
1.whatwg-fetch使用3.6.2
2.build-plugin-icestark使用1.7.2-2，依赖icestark版本为："@ice/stark": "1.6.0-2"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
升级后，Chrome下页面均正常，但IE11下测试发现，进行子应用切换时，经常报ChunkLoadError错误，相同路由刷新页面后正常。如下截图：

![image](https://user-images.githubusercontent.com/4099803/112568258-21f78f00-8e1d-11eb-9562-ff2c159700ce.png)

![image](https://user-images.githubusercontent.com/4099803/112568288-2ae86080-8e1d-11eb-8804-e2b88a14b80f.png)

![image](https://user-images.githubusercontent.com/4099803/112568308-363b8c00-8e1d-11eb-98ce-eaaad4fa30c3.png)

**What is the expected behavior?**
期望ie11下正常访问

**Comment by rootsli** [comment]
补充：Chrome下快速在2个子应用间切换，也会出现ChunkLoadError问题。不知道是和引入whatwg-fetch有个，还是build-plugin-icestark使用1.7.2-2有关。没引入whatwg-fetch，build-plugin-icestark使用1.7.2，快速切换也能正常加载

**Comment by maoxiaoke** [comment]
@rootsli 子应用使用了分包加载？

**Comment by rootsli** [comment]
> @rootsli 子应用使用了分包加载？

同一子应用内不同页面切换好像出现上面的问题概率较低。但是在react和vue子应用间频繁切换的时候，出现概率很高。react子应用使用了lazy(() => import的按需加载方式加载页面和打包 @maoxiaoke

**Comment by maoxiaoke** [comment]
@rootsli 是否可以 react 应用不进行分包，先判断是否是有由于 react 分包导致

**Comment by maoxiaoke** [comment]
it's pleased to reopen if you are still in trouble
