### ISSUE TITLE
@ice/stark-data数据持久化

### ISSUE THREAD

**Issue by liqupan** [ice-lab/icestark#286]
report a bug

为什么@ice/stark-data store或者event 在页面刷新的时候，数据会丢失，注册监听的回调事件也会丢失？

**Comment by maoxiaoke** [comment]
@liqupan 持久化状态数据实际的需求场景是什么？

**Comment by liqupan** [comment]
> @liqupan持久化状态数据实际的需求场景是什么？

用户信息被修改的时候，想通知重新拿用户数据写Cookies，获取成功后通知用到用户信息的地方重新拿cookies....😑

**Comment by maoxiaoke** [comment]
@liqupan 建议还是通过 localstorage 等手段进行存储
