### ISSUE TITLE
icestark 仓库的目录组织

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icestark#29]
## 问题描述

如下图，核心代码分为了 `packages/icestark-app` 和根目录下的源代码两块，分为对应 `@ice/stark-app` 和 `@ice/stark` 两个包，从目录组织和包命名看着有些奇怪，不知是怎么考虑的。

![image](https://user-images.githubusercontent.com/3995814/68272112-b1bc6200-009d-11ea-9a0d-9825ecd06bfa.png)

## 个人建议

1. 既然是单独的包，可以按照 lerna 的方式进行组织都在 `packages` 下；
2. `@ice/stark-app` 和 `@ice/stark` 两个包从命名上看很难区分其含义，感觉不是很直观，看了下文档，建议考虑将 `@ice/stark-app` 命名为 `@ice/stark-child-app`，或者其他更符合语义的包名

**Comment by daysai** [comment]
- 从包的数量上考虑，暂无打算使用 lerna 这类较重的管理方案
- @ice/stark-app 也是从包的命名简洁性上考虑
- packages 组织方式更多受到 lerna 影响，但并未形成公约形式，暂不修改
