### ISSUE TITLE
子应用如果是使用react.lazy做懒加载的 spa应用，那么在子应用内跳转到懒加载路由时，加载失败的问题

### ISSUE THREAD

**Issue by yangdm2015** [ice-lab/icestark#293]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
子应用内跳转到懒加载路由时，加载失败。
比如主应用起在3022，子应用起在3023，子应用跳到懒加载的页面，network显示请求了http://localhost:3022/js/0.j ，这不对

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
步骤
1.使用脚手架创建子应用和主应用，启动主子应用。
2.将主应用的本地地址配置在主应用的apps中（配置了sandbox），并在菜单中配置链接。
3.在子应用中的列表和详情中增加互相跳转的链接，单独起子应用，互相跳转ok
4.子应用中新增一个懒加载的页面，在子应用中的列表和详情中增加跳转到这个懒加载页面的链接  单独起子应用，互相跳转ok
5.在主应用中打开子应用，点击非跳转到懒加载页面的链接，跳转正常
6.在主应用中打开子应用，点击跳转到懒加载页面，报加载失败.
**What is the expected behavior?**
期望第6步正常加载

**Comment by yangdm2015** [comment]
补充：子应用的build.json中配置publicPath和devPublicPath.  在主应用中点击懒加载的子应用的地址，network显示的请求地址符合预期，但还是报请求failed（但看起来是执行报错）

**Comment by yangdm2015** [comment]
[image](https://github.com/yangdm2015/documents/blob/main/E542B593-0CCA-40B2-96D6-2929F43AD962.png?raw=true)

**Comment by yangdm2015** [comment]
![image](https://github.com/yangdm2015/documents/blob/main/E542B593-0CCA-40B2-96D6-2929F43AD962.png)

**Comment by yangdm2015** [comment]
![image](https://github.com/yangdm2015/documents/blob/main/E542B593-0CCA-40B2-96D6-2929F43AD962.png?raw=true)

**Comment by ClarkXia** [comment]
先确认下是否是 [文档](https://ice-lab.github.io/icestark/faq#%E5%BA%94%E7%94%A8%E5%90%AF%E7%94%A8-lazy-%E5%90%8E%EF%BC%8Cchunk-%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5) 中提到的 lazy 加载失败的情况，如果不是提供下主子应用的 demo

**Comment by maoxiaoke** [comment]
@yangdm2015 暂时先不开启 sandbox 能力，这个我们排查下

**Comment by yangdm2015** [comment]
> @yangdm2015 暂时先不开启 sandbox 能力，这个我们排查下

关闭了相应子应用的sandbox能力后，没有问题了。但这应该也是个bug，估计是你们沙箱出问题了
