### ISSUE TITLE
能否支持next微应用接入，有相关文档吗

### ISSUE THREAD

**Issue by sea-xh** [ice-lab/icestark#294]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by maoxiaoke** [comment]
可以参考 react 的接入方式  https://micro-frontends.ice.work/guide/use-layout/react，也欢迎给我们提供 next 的接入文档

**Comment by yukinami** [comment]
next.js应用不需要改造添加`mount/unmount`生命周期函数吗？

**Comment by guanweiwang** [comment]
接入后报错  Cannot read properties of null (reading 'textContent')，此时 __NEXT_DATA__  并没有找到
