### ISSUE TITLE
@ice/stark-data能否支持Symbol值

### ISSUE THREAD

**Issue by xmsz** [ice-lab/icestark#298]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

- 无法使用Symbol值

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

![image](https://user-images.githubusercontent.com/5879146/118219473-1b47d880-b4ac-11eb-9d38-4a3310b2e8b5.png)

**What is the expected behavior?**

- 可以使用Symbol值，目的是避免不要的key重复

**Comment by maoxiaoke** [comment]
欢迎提供 pr 支持

**Comment by chuifengji** [comment]
ice/stark-data 不是用来全局通信，共享状态的吗，要 symbol 有啥用，不理解是想避免什么 key 值冲突。

**Comment by maoxiaoke** [comment]
@chuifengji symbol 在这里的最大用处就是避免 key 值冲突

**Comment by chuifengji** [comment]
好吧，我还是没明白冲突点在哪里，store 不是挂在 `window.[namespace]` 上的吗，也不是直接挂在 window 上呀。应用之间要通信肯定要有约定好的 key，所以？会出现子应用单独使用 store 上某个状态不共享的情况？

**Comment by chuifengji** [comment]
好吧，我还是没明白冲突点在哪里，store 不是挂在 window[namespace] 上的吗，也不是直接挂在 window 上呀。应用之间要通信肯定要有约定好的 key，所以？会出现子应用单独使用 store 上某个状态不共享的情况？

**Comment by maoxiaoke** [comment]
> > @chuifengji symbol 在这里的最大用处就是避免 key 值冲突
> 
> 好吧，我还是没明白冲突点在哪里，store 不是挂在 window[namespace] 上的吗，也不是直接挂在 window 上呀。应用之间要通信肯定要有约定好的 key，所以？会出现子应用单独使用 store 上某个状态不共享的情况？

在某些大型协作场景下，基于约定的效率会越来越低。但是对于微应用这种场景，我们并不推荐相互之间有过多的通信，这有违微前端的设计初衷。

**Comment by maoxiaoke** [comment]
@ice/stark  2.4.0 已支持该能力，更多能力介绍可以参考 https://micro-frontends.ice.work/blog/00-icestark-2-4-0/
