### ISSUE TITLE
[RFC]  AppRoute、AppRouter 与 registerMicroApps 参数对齐

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/icestark#299]
## 概述
AppRoute、AppRouter 与 registerMicroApps 参数对齐

## 背景
目前 [AppRoute、AppRouter 接收的参数](https://micro-frontends.ice.work/api/wrapper#approuter) 和 [通过 api 方式](https://micro-frontends.ice.work/api/core) 有部分参数存在未对齐的地方，对用户的使用造成困扰。

### [AppRouter](https://micro-frontends.ice.work/api/wrapper#approuter) 缺失的参数

1. [onLoadingApp](https://micro-frontends.ice.work/api/core#onloadingapp)
2. [onFinishLoading](https://micro-frontends.ice.work/api/core#onfinishloading)
3. onError
<del>4. [onActiveApps](https://micro-frontends.ice.work/api/core#onactiveapps)</del>

以上参数均在 AppRouter 中新增

### [start](https://micro-frontends.ice.work/api/core#start) 缺失的全局配置

1. [basename](https://micro-frontends.ice.work/api/wrapper#basename)
start 新增 basename 参数

###  [AppRoute](https://micro-frontends.ice.work/api/wrapper#approute) 和 [appConfig](https://micro-frontends.ice.work/api/core#registermicroapps) 不一致的参数

1. [path](https://micro-frontends.ice.work/api/wrapper#path)
path 字段标记为 deprecated，推荐使用 activePath。activePath 的类型如下：

```ts
activePath?: string | string[] | PathData[] | MatchOptions[] | ActiveFn;
```

兼容模式下：

+ 若 activePath 不为函数，取 activePath 为应用 name （同以前的逻辑）
+ 若 activePath 为函数，则需明确提供 name 字段用于标记应用，否则 error 提示

在 activePath 存在匹配多个微应用的场景，兼容模式下：

+ 若微应用未提供 container 字段，则默认命中第一个匹配的应用

<del> 2. basename </del>
<del> 标记为 deprecated，推荐使用 `activePath: ActiveFn` 实现。</del>

```js
<AppRoute
 // old way
  path=['/seller', '/watier']
  basename="ice"
 // new way
  activePath={ () => return ['/seller', '/watier'].addPrefix('ice') }
/>
```

### build-plugin-icestark 使用

onLoadingApp、onFinishLoading、onError、onActiveApps 均可在 Framework 获取。

## 其他

相关 issue + 文档更新

#297 
#209

**Comment by ClarkXia** [comment]
部分 API 最好看下使用场景，比如 AppRouter 上提供 onActiveApps 是不是没必要，目前默认应该只会渲染一个 App，用 onAppEnter 的周期是否就可以满足

**Comment by maoxiaoke** [comment]
1. path 改成 activePath 需要还需要额外标记 key
2. activePath 匹配多个微应用

**Comment by maoxiaoke** [comment]
更新：
+ AppConfig 应用 basename 为自定义向微应用传递的 Router 的 basename，该自定需要保留，并在 api 字段中新增
