### ISSUE TITLE
支持直接解析 html 获取相关配置

### ISSUE THREAD

**Issue by daysai** [ice-lab/icestark#30]
## 背景

icestark 在针对 kissy、jQuery 等旧技术栈的兼容成本高，支持直接解析 html 能简化旧技术栈的成本，同时进一步简化 jsBundle 的配置成本。

## 方案

支持直接通过 htmlUrl 解析，获取 html 的 body 的具体内容，同时解析出外链的 js、css 配置到 url 中

**Comment by daysai** [comment]
已完成 @ice/stark-html 的插件开发，还需要进一步优化，预计 11.22 前能正常完成

**Comment by cabinhero** [comment]
能提供个demo不
