### ISSUE TITLE
微模块引入三方npm包，npm包中依赖antd组件样式没有打包进来

### ISSUE THREAD

**Issue by PYDebug** [ice-lab/icestark#300]
背景描述：
1. 三方npm包peer依赖antd
2. ice微模块引入三方npm包，同时微模块本身没有引入npm包中依赖的antd组件
3. 微模块打包生成的样式中没有包含npm包中依赖的antd组件的样式

**Comment by maoxiaoke** [comment]
需要在项目下安装 antd，并引入样式文件。具体请参考 https://ant.design/docs/react/introduce-cn。如果使用 ice 框架，请参考 https://ice.work/docs/guide/advance/antd

**Comment by PYDebug** [comment]
那还是需要手动引入样式文件，三方npm包的样式文件（lib/style.js）不可以直接被编译进来吗？微应用是可以的，但是微模块不可以

**Comment by ClarkXia** [comment]
@maoxiaoke 微模块构建任务中缺少 webpack-plugin-import 自动引入业务组件的 style.js

**Comment by maoxiaoke** [comment]
fixed in [build-plugin-stark-module@2.0.3](https://www.npmjs.com/package/build-plugin-stark-module/v/2.0.3)
