### ISSUE TITLE
样式丢失

### ISSUE THREAD

**Issue by DevilLeven** [ice-lab/icestark#303]
**Do you want to request a *feature* or report a *bug*?**
【bug】

主应用vue2.6，配置组件按需加载
![image](https://user-images.githubusercontent.com/21081386/118743307-b6fa8f80-b884-11eb-9f78-bbc2d465a74b.png)

子应用为示例应用 
[https://icestark-vue.surge.sh/waiter](https://icestark-vue.surge.sh/waiter)

主子应用切换时，会随机出现主应用样式被卸载
![image](https://user-images.githubusercontent.com/21081386/118743497-0640c000-b885-11eb-8348-3e41842f53a4.png)

![image](https://user-images.githubusercontent.com/21081386/118743475-ffb24880-b884-11eb-9262-6a727a861165.png)

```
// 通过打印
shouldAssetsRemove(assetUrl,element){
        console.log(assetUrl);
        console.log(element);
        return true;
      }
```
![image](https://user-images.githubusercontent.com/21081386/118745252-5d945f80-b888-11eb-93e8-e704259d68c1.png)

**Comment by maoxiaoke** [comment]
建议主应用暂时不要开启按需加载，我们会尽快修复这个问题

**Comment by maoxiaoke** [comment]
@DevilLeven 你这边同时也配置了页面的按需加载？
