### ISSUE TITLE
[RFC] script 支持自定义 attribute

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/icestark#307]
## 概述

支持 script 标签自定义 attribute。

## 背景

1. 对于 script error 错误这些问题，提供手段支持 crossorigin https://github.com/ice-lab/icestark/issues/276 [🔗](https://help.aliyun.com/document_detail/88579.html)
2. 借机对 esm 的支持提供扩展 https://github.com/ice-lab/icestark/issues/260

## 方案

新增 `scriptAttributes` 字段：为 script 标签新增的 attribute 属性

```jsx
interface AppConfig {
	...
  scriptAttributes: string[] | (url: string) => string[],
}
```

使用方式：

```js
<AppRouter>
  <AppRoute
    name="seller",
    path="/seller",
    url={['https://xxx.js']}
    scriptAttributes={['crossorigin=annoymous', 'type=module'， ‘customAttribute=test']}
</AppRouter />
```

1. 以下属性修改无效，开发环境下 error 提示，线上环境 warn 提示。
  + icestark - 内部使用
  + src： 不允许修改
  + async: false

2. 能否设置 defer 属性
可以。

## 其他

1. 一个更简单支持的方案，默认提供 crossorigin=annoymous。

2. css 是否要支持

**Comment by maoxiaoke** [comment]
Closes for https://github.com/ice-lab/icestark/pull/306

**Comment by skillnull** [comment]
希望提供对 async 的支持
