### ISSUE TITLE
对所有请求或者响应进行拦截配置似乎不生效问题

### ISSUE THREAD

**Issue by EstablishCheng** [ice-lab/icestark#310]
我已经根据文档在appConfig做了如下配置：
`request: {
    withFullResponse: true,
    interceptors: {
      request: {
        onConfig: (config) => {
          config.headers = {a: 1};
          return config;
        }
      },
      response: {
        onConfig: (response) => {
          debugger
          // 请求成功：可以做全局的 toast 展示，或者对 response 做一些格式化
          if (response.data.status !== 1) {
            alert('请求失败');
          }
          return response;
        },
        onError: (error) => {
          // 请求出错：服务端返回错误状态码
          console.log(error.response.data);
          console.log(error.response.status);
          console.log(error.response.headers);
          return Promise.reject(error);
        }
      }
    }
  }`
但是在发起请求时不会做出任何打印日志的问题，也不会进入debugger。
我在menuConfig.ts下加了一段代码：
`import { request } from 'ice';

const getToken = async () => {
  return await request('/oauth/check_token?token=123456');
}

const token = getToken();
console.log(token);`
可以打印响应结果：
![image](https://user-images.githubusercontent.com/33605354/119854562-bd9f9b80-bf43-11eb-9246-80d7d1978f26.png)
请问还需要哪里做一些配置或者更改才能使拦截生效？

**Comment by EstablishCheng** [comment]
加载该请求和拦截配置是同时加载的，估计应该是这个时候拦截器未生效导致的

**Comment by imsobear** [comment]
提到这个仓库里：https://github.com/alibaba/ice/issues
