### ISSUE TITLE
appHistory.push不适用页面间的跳转嘛

### ISSUE THREAD

**Issue by sea-xh** [ice-lab/icestark#319]
从列表跳转详情页url拼接cid
appHistory.push(`xxx/detail?cid=${cid}`);
在detail页面把cid取出来，在useEffect中依赖cid请求
useEffect(() => {
     const res: any = fetchDetails({ cid });
}, [cid]);
结果每次取到的cid都是一样的（实际列表每个cid都不同），是因为有缓存嘛，用location.href就没问题

**Comment by maoxiaoke** [comment]
列表页和detail 页是同属一个应用吗？

**Comment by sea-xh** [comment]
> 可以详细描述下：
> 
> 1. 详情和列表页是否同属同微应用
> 2. 详细如何取得cid

1.属同微应用
2.cid放在redux中，初始化没有dispatch，是我取的有问题
