### ISSUE TITLE
支持白名单资源的持久化问题

### ISSUE THREAD

**Issue by jixiangac** [ice-lab/icestark#32]
## 背景

有这样场景，需要外挂widgets的模式，比如各种问答机器人的组件。跟当前主应用本身无关的内容。
使用这些外挂的组件的时候，外挂组件也存在构造js/css进行动态添加的能力，添加的资源可能比icestark的标记时机要慢，这样导致的结果是当发生切换时候，外挂的部分资源可能会被清理掉而导致外挂组件无法work.

## 需求

支持以『白名单』的模式设置部分资源持久化，不需要进行清理。

**Comment by daysai** [comment]
需求已明确，看下怎么设计这个 api 比较好～

**Comment by daysai** [comment]
考虑在 AppRouter 层增加 shouldAssetsRemove，形式是 (assteUrl) => boolean 。每次资源卸载前会调用一次 shouldAssetsRemove ：true -> 默认同意删除; false -> 该资源需要保留

**Comment by imsobear** [comment]
已支持
