### ISSUE TITLE
React版基础语言选择

### ISSUE THREAD

**Issue by hioak** [ice-lab/icestark#321]
icesstart脚手架有没有js版？ts语言感觉很麻烦。

**Comment by maoxiaoke** [comment]
将所有 ts/tsx 文件转成 js/jsx，并移除代码中的类型即可得到 js 版的框架。欢迎给我们提供这样的一个版本，我们会在官网上进行展示。

**Comment by imsobear** [comment]
ts 里可以完全使用 js 语法，目前没有精力维护这么多模板。
