### ISSUE TITLE
vue vite 工程 如何引入子应用

### ISSUE THREAD

**Issue by S112** [ice-lab/icestark#322]
![image](https://user-images.githubusercontent.com/7778864/122315957-9db13580-cf4d-11eb-99b4-07815248f384.png)
现在项目使用的是vite，怎样配置output.library （webpack 工程配置的 output.library）

**Comment by maoxiaoke** [comment]
目前 icestark 暂不支持 esm 的打包资源，我们预计会尽快支持该能力，详见 #260 。

目前，可通过 Vite 的 [Lib Mode](https://cn.vitejs.dev/guide/build.html#library-mode) 打包成 umd 资源，参考配置如下：

```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  build: {
    minify: false,
    lib: {
      entry: './src/main.ts',
      name: 'xiaoke',
      fileName: 'xiaoke-2'
    },
    rollupOptions: {
      // 请确保外部化那些你的库中不需要的依赖
      external: ['vue'],
      output: {
        // 在 UMD 构建模式下为这些外部化的依赖提供一个全局变量
        globals: {
          vue: 'Vue'
        }
      }
    }
  }
})
```
以适配 icestark 支持的 umd 模块规范。

**Comment by S112** [comment]
> 目前 icestark 暂不支持 esm 的打包资源，我们预计会尽快支持该能力，详见 #260 。
> 
> 目前，可通过 Vite 的 [Lib Mode](https://cn.vitejs.dev/guide/build.html#library-mode) 打包成 umd 资源，参考配置如下：
> 
> ```js
> import { defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [vue()],
>   build: {
>     minify: false,
>     lib: {
>       entry: './src/main.ts',
>       name: 'xiaoke',
>       fileName: 'xiaoke-2'
>     },
>     rollupOptions: {
>       // 请确保外部化那些你的库中不需要的依赖
>       external: ['vue'],
>       output: {
>         // 在 UMD 构建模式下为这些外部化的依赖提供一个全局变量
>         globals: {
>           vue: 'Vue'
>         }
>       }
>     }
>   }
> })
> ```
> 
> 以适配 icestark 支持的 umd 模块规范。

你好，an zhao

**Comment by S112** [comment]
你好，@maoxiaoke 
按照你说的配置，主应用还是无法引入微应用，这是为何呢？
下面是我的配置和报错内容
微应用配置：
![image](https://user-images.githubusercontent.com/7778864/122415134-3c737b80-cfba-11eb-9a38-4289abf91434.png)  
![image](https://user-images.githubusercontent.com/7778864/122415223-51500f00-cfba-11eb-9188-be7ffc8945ca.png)
主应用配置：
![image](https://user-images.githubusercontent.com/7778864/122415432-7fcdea00-cfba-11eb-99c5-f2c9720604b8.png)
报错内容：
![image](https://user-images.githubusercontent.com/7778864/122416090-0a164e00-cfbb-11eb-95be-160ab6459817.png)
![image](https://user-images.githubusercontent.com/7778864/122416213-21553b80-cfbb-11eb-8ca3-882af7bd7964.png)

麻烦帮我看一下，谢谢

**Comment by maoxiaoke** [comment]
@S112 嗯嗯，我这边试了下，感觉 vite 打包出来的 umd 有点问题

**Comment by maoxiaoke** [comment]
https://micro-frontends.ice.work/guide/use-child/vue 请参考这里，以及主应用接入 https://micro-frontends.ice.work/guide/use-layout/vue#%E5%B7%B2%E6%9C%89%E5%BA%94%E7%94%A8%E6%94%B9%E9%80%A0 的配置

**Comment by maoxiaoke** [comment]
https://github.com/maoxiaoke/icestark-vite-vue3
