### ISSUE TITLE
[bug] 快速路由切换时可能会存在资源无法清理的问题 

### ISSUE THREAD

**Issue by jixiangac** [ice-lab/icestark#33]
RT...

**Comment by imsobear** [comment]
描述具体点？

**Comment by daysai** [comment]
因为小二工作台的场景，会频繁触发 AppRouter 的 unmount / mount 事件（这一块需要小儿工作台优化），但是这种现象确实有可能会导致部分资源没有被 icestark 正确卸载。因此 1.2.0 版本对资源处理上会增加一些容错等的优化

**Comment by daysai** [comment]
1.2.0 版本已修复问题
