### ISSUE TITLE
vue定义基准路由

### ISSUE THREAD

**Issue by zlqxk** [ice-lab/icestark#334]
![image](https://user-images.githubusercontent.com/51911583/125201829-61020100-e2a3-11eb-9f64-cd7e4246eb99.png)
vue微应用接入，定义基准路由这里也要从lib包里引入吧

**Comment by maoxiaoke** [comment]
是的，对于 Vue 应用，建议从 `@ice/stark-app/lib/getBasename` 引入，文档会修改一下。
