### ISSUE TITLE
[RFC] 支持 es module 类型微应用

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/icestark#346]
## 背景

随着浏览器的发展，越来越来越多的应用开始使用原生 es module 构建微应用。因此，在可见的未来，会有越来越多的 es module 微应用接入的诉求。目前，icestark 核心提供微应用运行时能力，对各类模块格式的资源均可扩展支持。

以下，均以目前较为流行的 [vite](https://vitejs.dev/) 为例，并介绍了 vite 项目接入 icestark。

## vite 项目打包成 umd 资源

icestark 2.x 推荐使用 [umd](https://micro-frontends.ice.work/docs/guide/concept/child#%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F) 的方式接入。同时，Vite 同样支持 [lib 方式](https://vitejs.dev/guide/build.html#library-mode) 方式，将应用打包成 umd 资源导出，即可支持 icestark 接入。

`vite.config.ts` 的配置如下：

```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  build: {
    minify: false,
    lib: {                                   //  vite lib 模式
      entry: './src/main.ts',      // 应用入口
      formats: ['umd'],            // 打包为 umd
      name: 'microapp',           // 挂载全局变量
      fileName: 'index',            // 文件名
    }
  }
})
```

应用入口 `main.ts` 添加如下内容：

```diff 
import { createApp } from 'vue'
+ import type { App as Root } from 'vue';
import App from './App.vue'
+ import isInIcestark from '@ice/stark-app/lib/isInIcestark';
+ import setLibraryName from '@ice/stark-app/lib/setLibraryName';

+ let vue: Root<Element> | null = null;

+ if (!isInIcestark ()) {
  createApp(App).mount('#app')
+ }

// 注意：`setLibraryName` 的入参需要 vite.config.js 的 lib.name 保持一致
+ setLibraryName('microapp')

+ export function mount({ container }: { container: Element}) {
  + vue = createApp(App);
  + vue.mount(container);
+ }

+ export function unmount() {
  + if (vue) {
    + vue.unmount();
  + }
+ }
```

## 将 vite 项目打包成 es module 资源

默认设置下，vite 将打包出 es module 资源。icestark 通过 [`dynamic import`](https://github.com/tc39/proposal-dynamic-import) 加载资源，并获取导出的生命周期（推荐的 mount、unmount）函数。

方案要点：

### dynamic Import 的浏览器支持
![image](https://user-images.githubusercontent.com/13417006/126735387-af27430e-de0c-49a3-841b-fc70d2e1c91b.png)

[dynamic import polyfill](https://github.com/GoogleChromeLabs/dynamic-import-polyfill) 需要得到静态 import 的支持，其浏览兼容性如下：
![image](https://user-images.githubusercontent.com/13417006/126735706-63ca9e84-d404-476d-9aa9-ef0968864c4e.png)

因此基本认为，在 > chrome 60 的浏览器支持良好。

### @ice/stark 提供 es module 脚本

@ice/stark 及其相关包打包出 esnext 资源供给项目使用。打包结果目录为：

```text
- lib
- esnext
```

`package.json` 支持 `module` 以及 `exports` 字段。

### 微应用接入

入口文件配置生命周期函数：

```main.ts
import { createApp } from 'vue'
import type { App as Root} from 'vue';
import App from './App.vue'
import isInIcestark from '@ice/stark-app/lib/isInIcestark';
// import setLibraryName from '@ice/stark-app/lib/setLibraryName';

let vue: Root<Element> | null = null;

if (!isInIcestark ()) {
  createApp(App).mount('#app')
}

// setLibraryName('microapp')  不再需要

export function mount({ container }: { container: Element}) {
  vue = createApp(App);
  vue.mount(container);
}

export function unmount() {
  if (vue) {
    vue.unmount();
  }
}
```

主应用配置：

```js
{
  name: 'microapp',
  activePath: '/seller',
  scriptAttributes: ["type=module"], // 生命 esmoudle 资源
  url: [
      'http://abc.com/index.js', // 只需入口 js 文件,
      'http://abc.com/inde.css' // 和其他样式文件
  ]
}
```

可能存在的缺陷：
1. `["type=module"]` 设置下，url 会通过 dynamic import 加载，而非 `<script />` 标签加载，是否存在歧义？
2. url 字段中只能保留唯一一个 js，来保证正确加载到入口文件。

### 使用 registerAppEnter 的另一种途径

若通过使用 `registerAppEnter` 和 `registerAppLeave` 来注册生命周期，则可直接使用 <script /> 来加载 es module 资源。微应用配置如下：

```js
import { createApp } from 'vue'
import type { App as Root} from 'vue';
import App from './App.vue'
import isInIcestark from '@ice/stark-app/isInIcestark';
import registerAppEnter from '@ice/stark-app/lib/registerAppEnter';
import registerAppLeave from '@ice/stark-app/lib/registerAppLeave';

let vue: Root<Element> | null = null;

if (!isInIcestark ()) {
  createApp(App).mount('#app')
}

registerAppEnter(() => {
  vue = createApp(App);
  vue.mount(container);
})

registerAppLeave(() => {
  if (vue) {
    vue.unmount();
  }
})
```

## 其他

1. webpack 打包的转义

若通过 dynamic import 通过 webpack 打包，会被转换为 __webpack_require__。若是要求生命周期通过 `mount`/`unmount` 导出，则主应用也必须支持 es moudle 规范 
 
2. 入口导出生命周期的问题

详见 https://github.com/vitejs/vite/issues/4359

**Comment by imsobear** [comment]
@ice/stark 提供 es module 脚本，这个貌似关系不大？提供个跟现在业务组件一样的 `es/` 配合 pkg.module 就可以了？

**Comment by imsobear** [comment]
这里为什么用 dynamic import 没介绍，现在已经有两种 fetch&eval / getScript 了，是再加一种？

**Comment by imsobear** [comment]
vite 打包的产物格式默认是什么？我们要将 ta 变成什么？上面提到 umd 和 esmodule 这两个是冲突的。

**Comment by maoxiaoke** [comment]
> vite 打包的产物格式默认是什么？我们要将 ta 变成什么？上面提到 umd 和 esmodule 这两个是冲突的。

vite 默认是  es module 打包结果，但是也支持打包成其他结果。https://vitejs.dev/config/#build-lib

+ 如果是直接打包成 umd，用现行的方式接入
+ 如果打包成 es module，就需要额外支持

**Comment by maoxiaoke** [comment]
> @ice/stark 提供 es module 脚本，这个貌似关系不大？提供个跟现在业务组件一样的 `es/` 配合 pkg.module 就可以了？

是的

**Comment by imsobear** [comment]
> > vite 打包的产物格式默认是什么？我们要将 ta 变成什么？上面提到 umd 和 esmodule 这两个是冲突的。
> 
> vite 默认是 es module 打包结果，但是也支持打包成其他结果。https://vitejs.dev/config/#build-lib
> 
> * 如果是直接打包成 umd，用现行的方式接入
> * 如果打包成 es module，就需要额外支持

我们的选择是？

**Comment by maoxiaoke** [comment]
> 这里为什么用 dynamic import 没介绍，现在已经有两种 fetch&eval / getScript 了，是再加一种？

使用 dynamic import 是为了支持现行的 mount/unmount 生命周期的导出方式。通过 `<script type="module" />` 无法获取到这一信息。

**Comment by maoxiaoke** [comment]
> > > vite 打包的产物格式默认是什么？我们要将 ta 变成什么？上面提到 umd 和 esmodule 这两个是冲突的。
> > 
> > 
> > vite 默认是 es module 打包结果，但是也支持打包成其他结果。https://vitejs.dev/config/#build-lib
> > 
> > * 如果是直接打包成 umd，用现行的方式接入
> > * 如果打包成 es module，就需要额外支持
> 
> 我们的选择是？

两者均需要支持

**Comment by maoxiaoke** [comment]
vite.config.js 的配置如下：

```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  server: {
    cors: true,
  },
  build: {
    minify: false,
    lib: {
      entry: './src/main.ts',
      formats: ['es'],
      fileName: 'index'
    },
    rollupOptions: {
      preserveEntrySignatures: 'exports-only'
    }
  },
})
```

其中有几个点：
1. 需要设置为 lib 模式，并增加 rollup 配置 preserveEntrySignatures，否则入口文件不会导出 export (其中 为何还需要设置为 lib 模式还需要确认)

2. start 模式下

```html
  | <!DOCTYPE html>
  | <html lang="en">
  | <head>
  | <script type="module" src="/@vite/client"></script>
  | <meta charset="UTF-8" />
  | <link rel="icon" href="/favicon.ico" />
  | <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  | <title>Vite App</title>
  | </head>
  | <body>
  | <div id="app"></div>
  | <script type="module" src="/src/main.ts"></script>
  | </body>
  | </html>
  | 
```

**Comment by maoxiaoke** [comment]
接下来待处理的问题：

- [ ] 适配 ice.js vite 模式
- [ ] 社区宣传

**Comment by liuhui677** [comment]
使用umd模式打包会出现错误
![image](https://github.com/ice-lab/icestark/assets/55862169/749b95fe-4782-43c3-aee8-6663b26ca1cf)
![image](https://github.com/ice-lab/icestark/assets/55862169/499aef74-fd1a-47d4-bf58-123b83fe7b1d)

**Comment by wisdomofgod** [comment]
邮件已收到~~
