### ISSUE TITLE
框架会导致浏览器缓存页面吗，每次部署最新代码需要无痕或者清除历史记录才能看到最新改动

### ISSUE THREAD

**Issue by sea-xh** [ice-lab/icestark#352]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by maoxiaoke** [comment]
应该是浏览器缓存导致的，在开发中，可以开启 [disable cache](https://www.webinstinct.com/faq/how-to-disable-browser-cache) 功能来禁用浏览器缓存
