### ISSUE TITLE
优化问题：子应用加载较慢，且存在更新缓存问题

### ISSUE THREAD

**Issue by lemon19930205** [ice-lab/icestark#356]
先感谢飞冰团队做了一个这么优秀的微前端框架，刚好适用我们公司的场景，且基本功能较完善。
不过我们发现两个重要不紧急问题(ps:有可能是我没用好，希望能指点下)：
    1. 子应用加载较慢，打包出来的 js 文件有好几M，至少要等 3s 以上，有明显的停顿感
        配置截图：
              ![image](https://user-images.githubusercontent.com/26914453/128965394-f369efcc-f2b2-43c3-92e5-5cca2546995a.png)
              ![image](https://user-images.githubusercontent.com/26914453/128965515-aead4e6f-0727-4a02-ba00-45d4bd4e53ed.png)
        建议：能给子应用的打包结果做分包等处理，或者能给加个 loading
    2. 子应用文件会被本地缓存，每次部署更新后需要清缓存才能使用最新版
        建议：这个好像无解，除非要求主子应用同时打包生成 hash，只更新子应用的话就不行；如果所有子应用都起服务是能解决，但是有需要同时维护多个服务

希望能一起探讨下上面问题，祝好~

**Comment by maoxiaoke** [comment]
可以参考下 [性能优化](https://micro-frontends.ice.work/docs/guide/advanced/performance) 这一章节的内容，同时 icestark 也支持传统的比如按需加载等优化手段。

目前，建议从以下几个角度来优化加载性能：

1. 优化子应用
可以适当分析子应用的打包体积，移除一些无用依赖、或按需加载一些依赖。比如：
+ 组件库按需打包
+ 页面进行 [dynamic import](https://webpack.js.org/guides/code-splitting/#dynamic-imports)
+ 依赖外置

2. 添加 prefetch 
优化非首屏渲染的微应用的时间

**Comment by maoxiaoke** [comment]
对于第二个问题，有以下一些方案：

1. 子应用资源添加 hash 后缀。缺点：可能需要一个服务托管微应用资源，因为每次发布 hash 时刻在变化
2. 资源末尾添加时间戳。缺点：无法使用浏览器缓存
3. 使用 nocache 等策略。缺点：可能需要服务端配合执行相应的缓存策略。
