### ISSUE TITLE
调用 createMicroApp 会报找不到 react 的错误

### ISSUE THREAD

**Issue by Pochodaydayup** [ice-lab/icestark#362]
在非 react 项目里面调用 createMicroApp 会报找不到 react 的错误

![image](https://user-images.githubusercontent.com/22768639/129388354-e0856b2e-87ec-4671-bf8e-108f4fb36c20.png)

**Comment by imsobear** [comment]
https://github.com/ice-lab/icestark/issues/281

**Comment by maoxiaoke** [comment]
https://micro-frontends.ice.work/docs/api/core

**Comment by jieliu** [comment]
文档打不开呢 @maoxiaoke

**Comment by jieliu** [comment]
https://micro-frontends.ice.work/docs/api/core 文档打不开呢 @maoxiaoke

**Comment by maoxiaoke** [comment]
@jieliu https://micro-frontends.ice.work/docs/api/ice-stark  文档有修改
