### ISSUE TITLE
老工程是多页面应用，使用kissy@1.4.1，怎么接入作为子应用呢？

### ISSUE THREAD

**Issue by 957739315** [ice-lab/icestark#364]
老工程配置：
       技术栈 KISSY： 1.4.1
       打包 @ali/builder-xcake

打包后是一些js css文件，然后后端通过html模板进行渲染。请问这种情况，应该怎么改造老工程为微应用呢？

**Comment by maoxiaoke** [comment]
https://micro-frontends.ice.work/docs/guide/concept/child#%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F

目前 2.x 我们是推荐通过将资源打包成 umd 类型来接入，参考下[这里](https://micro-frontends.ice.work/docs/guide/use-child/react#%E5%B7%B2%E6%9C%89-react-%E9%A1%B9%E7%9B%AE%E6%94%B9%E9%80%A0%E4%B8%BA%E5%BE%AE%E5%BA%94%E7%94%A8)

如果 builder 不太进行统一修改，也可以用  [registerAppEnter/registerAppLeave](https://micro-frontends.ice.work/docs/guide/concept/child#1-registerappenterregisterappleave) 的方式接入

**Comment by maoxiaoke** [comment]
内部同学可以单独找下我
