### ISSUE TITLE
子应用渲染节点的配置希望能更灵活，支持class

### ISSUE THREAD

**Issue by fangqi5** [ice-lab/icestark#366]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
只支持有id属性的dom
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**
支持class类型的渲染节点

**Comment by maoxiaoke** [comment]
具体是怎样的渲染节点，可以用代码简单描述一下吗？ @fangqi5

**Comment by fangqi5** [comment]
> 具体是怎样的渲染节点，可以用代码简单描述一下吗？ @fangqi5

<div className="cgdpl-content">
          <div className="cgdpl-body"></div>
        </div>

**Comment by fangqi5** [comment]
<div className="cgdpl-content">
          <div className="cgdpl-body"></div>
        </div>

**Comment by fangqi5** [comment]
'<div className="cgdpl-content">
          <div className="cgdpl-body"></div>
        </div>'

**Comment by fangqi5** [comment]
`<div className="cgdpl-content">
          <div className="cgdpl-body"></div>
        </div>`

**Comment by maoxiaoke** [comment]
可以通过简单的 HoC 来实现这一功能，比如通过 ice.js 来创建的应用：

```js
import { AppRoute } from '@ice/stark';

const HocAppRoute = (props) => {
  return (
    <div classname="starkLoading">
      <AppRoute  {...props} />
    </div>
  )
} 

const appConfig: IAppConfig = {
  icestark: {
    type: 'framework',
    Layout: React.memo(FrameworkLayout),
    getApps: async () => { },
    appRouter: {
    },
    AppRoute: HocAppRoute
  },
};

runApp(appConfig);
```
