### ISSUE TITLE
[bug] AppLeave 实现优化建议

### ISSUE THREAD

**Issue by jixiangac** [ice-lab/icestark#38]
![image](https://user-images.githubusercontent.com/1684563/69342090-c6a41280-0ca5-11ea-99ad-da0c790e0e83.png)

当AppRoute是以unmount/mount的方式重新渲染时，onAppLeave钩子不会生效，就会导致leave事件失效

![image](https://user-images.githubusercontent.com/1684563/69342240-11258f00-0ca6-11ea-9c80-10b851e70ca9.png)

建议：以队列的方式实现leave事件

**Comment by daysai** [comment]
AppRoute 正常不会经过 unmount/unmount 周期，而是 update；触发 unmount 的背景也是 AppRouter 上层被 unmount 掉了；预计 11.22 发布 1.1.1 版本增加  AppRoute unmount 时触发应用卸载的逻辑

**Comment by daysai** [comment]
1.1.1 正式版本已发布～
