### ISSUE TITLE
子应用内部路由跳转是否可以进行拦截处理，并可进行统一在跳转的地址中添加query等参数操作

### ISSUE THREAD

**Issue by Winter1141151662** [ice-lab/icestark#390]
背景：项目为hash路由模式的微前端构建，路由地址大致为，例：//a.b.c?e=5&f=6#/page， 其中//a.b.c?e=5中的**e=5**为主应用处理的逻辑，可以决定全局工作环境的作用。现需要修改成browser路由模式。
若改成browser路由形式则需要改成//a.b.c/page?e=5 形式，但是在子应用中若是内部每次跳转都需要携带该query，但是原先的子应用中的跳转没有携带该query。是否可以在子应用中提供一个api可以控制该子应用中内部的每次跳转。

**Comment by maoxiaoke** [comment]
从设计的角度来说，建议在每次加载微应用的时候，微应用消费这个数据。微应用在内部跳转的时候，携带这个参数。比如，访问  //a.b.c.com?e=5 访问到 A 微应用，在 A 应用的入口处消费这个 query 参数：

```js
// 微应用入口
const search = window.location.search

// 在其他内部跳转的地方
<Link to={"/f" + search} >跳转内部路由</Link>
```

**Comment by Winter1141151662** [comment]
目前维护的代码库代码量过大， 如果在每个微应用的每次内部跳转上都添加消费query参数的逻辑， 修改的地方很多，会出现修改、测试等成本过高的问题。那在微应用中有没有统一去做消费query的方法。

**Comment by maoxiaoke** [comment]
> 目前维护的代码库代码量过大， 如果在每个微应用的每次内部跳转上都添加消费query参数的逻辑， 修改的地方很多，会出现修改、测试等成本过高的问题。那在微应用中有没有统一去做消费query的方法。

想要避免大量修改，尝试在微应用劫持 history.pushState 和 history.replaceState，来统一消费 query 信息

```js
const hijackHistory = (): void => {
  window.history.pushState = (state: any, title: string, url?: string, ...rest) => {
    // 在这里消费信息
    originalPush.apply(window.history, [state, title, url, ...rest]);
  };

  window.history.replaceState = (state: any, title: string, url?: string, ...rest) => {
    // 在这里消费 query 信息
    originalReplace.apply(window.history, [state, title, url, ...rest]);
  };
};
```

并在离开应用时卸载监听器
