### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by murongg** [ice-lab/icestark#393]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

通过官网文档创建基于 Vue 的主应用
`npm init ice icestark-layout @vue-materials/icestark-layout-app`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

通过上述命令创建项目后，进入应用。

当路由为 `/seller/detail` 时
例：http://localhost:8080/seller/detail
刷新后抛出错误，并网页不能正常访问
```
Uncaught SyntaxError: Unexpected token '<'
```

当路由为 `/seller` 时
例：http://localhost:8080/seller
刷新后不会抛错，并可以正常访问

**What is the expected behavior?**

**Comment by maoxiaoke** [comment]
这是因为 `vue.config.js` 中配置了

```js
publicPath: './'
```

当访问 /seller/detail 时，vue 框架应用请求的是 `abc.com/seller/app.js` 错误资源，框架应用修改成：

```js
publicPath: '/'
```

即可。
