### ISSUE TITLE
针对各服务间公共方法的封装有什么解决方案

### ISSUE THREAD

**Issue by murongg** [ice-lab/icestark#401]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by maoxiaoke** [comment]
微应用相互之间应该尽量较少耦合，各服务间共享公共方法感觉并不是一个好的设计。常见的方式比如 npm 包，会是更稳定的方式。可以详细描述下具体的场景，看下我们能提供什么帮助

**Comment by murongg** [comment]
> 微应用相互之间应该尽量较少耦合，各服务间共享公共方法感觉并不是一个好的设计。常见的方式比如 npm 包，会是更稳定的方式。可以详细描述下具体的场景，看下我们能提供什么帮助

比如各服务间都会统一使用一个http请求方法

**Comment by maoxiaoke** [comment]
@murongg 两个思路：

1. 抽象成  npm 包提供到框架应用 + 微应用使用
2. 在框架应用统一注册，通过 icestark 的 [通信方案](https://micro-frontends.ice.work/docs/guide/advanced/communication)  让微应用调用

**Comment by murongg** [comment]
@maoxiaoke 我目前的解决方案是单独创建一个文件夹，里面存放共享代码，通过 rollup 打包，在微应用内通过 `npm` 的方式将本地包安装的 `package.json` 内，类似于您说的第一种方式，只不过我没有发不到 npm

**Comment by maoxiaoke** [comment]
@murongg 单独创建一个文件夹，代码又怎么共享到其他微应用的呢

**Comment by murongg** [comment]
@maoxiaoke 比如：
1. micro-app-login
2. micro-app-main
3. micro-app-shared
这三个应用在同一文件夹内，它们之间是平级的
![image](https://user-images.githubusercontent.com/38655613/134872028-da4dc27d-6f2b-41e7-a454-ecc844a16bb1.png)
`micro-app-shared` 存放的是共享的代码，通过rollup打包成 commonjs 与 es module 支持的代码。

![image](https://user-images.githubusercontent.com/38655613/134872193-22b8beca-a8bf-45d5-9e6b-d1c886bb5d57.png)

在微应用里，使用 `yarn add file:../micro-app-shared` 或 `npm install file:../micro-app-shared` 命令安装到微应用内，这样就可以直接在微应用代码里面引用了，应用方式和 npm 包一模一样。

**Comment by maoxiaoke** [comment]
@murongg 也就是所有微应用其实是个 monorepo

**Comment by murongg** [comment]
@maoxiaoke 类似于这个东西

**Comment by murongg** [comment]
@maoxiaoke 但是没有用lerna那种东西，因为我觉得没啥必要😂

**Comment by maoxiaoke** [comment]
@murongg 嗯嗯，这也是一个不错的思路

**Comment by murongg** [comment]
@maoxiaoke 目前我们不会跨团队，如果跨团队，还是您说的第一种方式比较合适
