### ISSUE TITLE
子应用部署问题

### ISSUE THREAD

**Issue by explorefit** [ice-lab/icestark#415]
**Do you want to request a *feature* or report a *bug*?**
在nginx中部署应用后，通过主应用进入后，在主应用中，点击子应用的菜单可以正常跳转，如果直接在浏览器中请求子应用的路由地址，就失败了
![image](https://user-images.githubusercontent.com/24665389/136882524-db4ad64e-137c-405d-957d-fc17548bfc52.png)

![image](https://user-images.githubusercontent.com/24665389/136882550-ae617f84-82e9-4f62-8270-1dc586452822.png)

**What is the current behavior?**

**这个 /aitms/tel  是子应用的路由，直接在浏览器中输入后，主应用的框架没有运行**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by maoxiaoke** [comment]
1. 怎么确认主应用的框架没有运行？
2. 控制台有错误吗？
3. network 中的资源加载是否成功？
4. 是否有复现的 demo

**Comment by explorefit** [comment]
> 1. 怎么确认主应用的框架没有运行？
> 2. 控制台有错误吗？
> 3. network 中的资源加载是否成功？
> 4. 是否有复现的 demo
> 
> @explorefit

1.通过主应用进入子应用的路由，
![image](https://user-images.githubusercontent.com/24665389/136886422-0f104107-d51d-4668-8c0b-3239e2e49e7c.png)

可以正常浏览，在浏览器直接刷新后，就是我上面提到的问题了
2.控制台没有错误
3.资源只加载了 子应用的 js和css资源

**Comment by maoxiaoke** [comment]
@explorefit 如果说只加载了子应用的样式，看下是否 ngix 返回了子应用的 document，而非框架应用的 document

**Comment by maoxiaoke** [comment]
@explorefit 这个跟 spa 应用的配置类似，其他所有路由都重定向到 root 目录下的 index.html

**Comment by explorefit** [comment]
> @explorefit 这个跟 spa 应用的配置类似，其他所有路由都重定向到 root 目录下的 index.html

谢谢你了，这个问题解决了，nginx中配置的路径和子应用的js路径冲突导致找不到对应的资源，现在js换为其他的可以正常加载了

**Comment by zhtx8090** [comment]
> > @explorefit 这个跟 spa 应用的配置类似，其他所有路由都重定向到 root 目录下的 index.html
> 
> 谢谢你了，这个问题解决了，nginx中配置的路径和子应用的js路径冲突导致找不到对应的资源，现在js换为其他的可以正常加载了

你好，我也遇到了同样的问题，主子应用在同一个域名下，刷新后就跳转到了子应用了，且无法返回主应用。
请问下你的主子应用怎么部署的，我这边是主应用和子应用都是单独部署nginx

**Comment by explorefit** [comment]
> > > @explorefit 这个跟 spa 应用的配置类似，其他所有路由都重定向到 root 目录下的 index.html
> > 
> > 
> > 谢谢你了，这个问题解决了，nginx中配置的路径和子应用的js路径冲突导致找不到对应的资源，现在js换为其他的可以正常加载了
> 
> 你好，我也遇到了同样的问题，主子应用在同一个域名下，刷新后就跳转到了子应用了，且无法返回主应用。 请问下你的主子应用怎么部署的，我这边是主应用和子应用都是单独部署nginx

子应用的js，css文件需要加载到，我这边是统一在一个nginx下，访问子应用的地址，都是跳转到主应用的nginx下，根据不同的子应用的基础前缀名字，来访问子应用。
