### ISSUE TITLE
框架应用支持非 React 体系

### ISSUE THREAD

**Issue by daysai** [ice-lab/icestark#42]
### 背景
目前 icestark 主要 API 设计偏向 react 体系，虽然子应用不受限制，但限制框架应用使用 react 体系；但考虑社区 vue 占比很高，考虑针对不同体系对出对应的设计方案

### 解决方案
@ice/stark-vue、@ice/stark-angular

**Comment by imsobear** [comment]
优先级不太高，后面看社区反馈再做评估。

**Comment by woaizimmy** [comment]
icestark是否有html的接入方式？

**Comment by imsobear** [comment]
https://ice.work/docs/icestark/guide/framework-app#%E5%AD%90%E5%BA%94%E7%94%A8%E5%85%A5%E5%8F%A3%20entry/url/entryContent @woaizimmy

**Comment by woaizimmy** [comment]
> https://ice.work/docs/icestark/guide/framework-app#%E5%AD%90%E5%BA%94%E7%94%A8%E5%85%A5%E5%8F%A3%20entry/url/entryContent @woaizimmy

参照实现了，感谢！

**Comment by woaizimmy** [comment]
有个问题想咨询：qiankun有资源预加载机制，icestark有没有类似的机制呢？

**Comment by upcwangying** [comment]
@daysai qiankun支持react Vue
