### ISSUE TITLE
icestark 官方文档 搜索框使用白屏

### ISSUE THREAD

**Issue by star-singer** [ice-lab/icestark#420]
点击搜索框，在不输入文本的情况下按方向键↑，页面白屏

**Comment by maoxiaoke** [comment]
@unseenstar 没有复现，是因为资源没加载完全？

**Comment by maoxiaoke** [comment]
@unseenstar 是个奇怪的现象，而且只发现在搜索框没有搜索记录时出现问题

**Comment by maoxiaoke** [comment]
给 docsearch 提了个 issue。因为这个暂时不影响使用，issue 先关了，后续请关注 docsearch  https://github.com/algolia/docsearch/issues/1057 的进展
