### ISSUE TITLE
切换微应用的路由时，微应用的样式加载不到，手动刷新后样式又加载到了

### ISSUE THREAD

**Issue by tooann** [ice-lab/icestark#444]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by tooann** [comment]
切换微应用路由时：
![image](https://user-images.githubusercontent.com/24756263/140281196-2f49b8df-2abe-442b-a24c-80b57bb1a056.png)
手动刷新后：
![image](https://user-images.githubusercontent.com/24756263/140281261-43b5138f-5454-4fb6-9ffe-9f8bec853979.png)

**Comment by maoxiaoke** [comment]
@tooann 看上是主应用的样式丢失在切换时丢失了，而子应用正常？

**Comment by tooann** [comment]
我检查了元素，发现子应用的元素样式找不到了
![image](https://user-images.githubusercontent.com/24756263/140283375-645512ad-eecb-4f09-b72c-511449d0d23c.png)
手动刷新后又找到了
![image](https://user-images.githubusercontent.com/24756263/140283467-978e2d18-85a6-4bbc-b79f-2b1a54e8dd87.png)

**Comment by maoxiaoke** [comment]
这是在 dev 开发时的问题？子应用通过菜单第一次加载就会出现问题，还是二次加载出现的问题？

**Comment by tooann** [comment]
你好，我找到问题的解决方案了，谢谢

**Comment by hyuanyuanlisiwei** [comment]
> 你好，我找到问题的解决方案了，谢谢

亲 怎么解决的啊

**Comment by huangyungeng** [comment]
> **Do you want to request a _feature_ or report a _bug_?**
> 
> **What is the current behavior?**
> 
> **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
> 
> **What is the expected behavior?**



> > 你好，我找到问题的解决方案了，谢谢
> 
> 亲 怎么解决的啊

路由多次跳转，路由地址写完整就好，我是这样的
