### ISSUE TITLE
build-plugin-stark-module 几个能力支持

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/icestark#449]
1. 支持 cors，本地开发时跨域访问不报错

2. 支持模块 externals 规则

模块支持一种提供多版本隔离的 [externals 方案](https://micro-frontends.ice.work/docs/guide/micro-module#%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96)，该模式会生成一份 runtime.json。现在目的是支持常规的 externals 的用法

**Comment by xmsz** [comment]
externals可以单独设置吗
我的需求
- 不希望加载一些库，因为外部已经已经提供，会导致重复加载
- 不希望把某些库打包进来
