### ISSUE TITLE
主应用能否提供公有方法供各个子应用之间调用？

### ISSUE THREAD

**Issue by liqupan** [ice-lab/icestark#450]
在主应用请求拦截中配置了对token的校验和续租等工作，想在所有的子应用请求之前也执行和主应用相同的校验操作（因为主应用和子应用之前请求隔离开的），所以想将校验写成函数放在主应用中，提供给各个子应用使用。

**Comment by maoxiaoke** [comment]
可以参考下一下方式：

1. 将通用方法抽离成 npm 包
2. 通过[主子应用通信](https://micro-frontends.ice.work/docs/guide/advanced/communication)的手段，三种方式中，更推荐 [props](https://micro-frontends.ice.work/docs/guide/advanced/communication/#props-) 的方式进行传递

**Comment by liqupan** [comment]
感谢，我应该尝试一下的，props传递一个函数提供给子应用使用。
