### ISSUE TITLE
ice init只创建了一个package,.json文件

### ISSUE THREAD

**Issue by pengwangpengwang** [ice-lab/icestark#451]
npm init ice icestark-layout @icedesign/stark-layout-scaffold
![image](https://user-images.githubusercontent.com/29265420/141425432-f92cde7f-02fd-4264-8923-44503515d15d.png)

**Comment by pengwangpengwang** [comment]
![image](https://user-images.githubusercontent.com/29265420/141425356-044378ce-b23e-49aa-a813-e3612f64a75e.png)

**Comment by maoxiaoke** [comment]
node 版本是多少？

**Comment by pengwangpengwang** [comment]
> node 版本是多少？

不好意思，node版本有问题，弄好了
