### ISSUE TITLE
Entry场景下，沙箱执行微应用js可能会报错

### ISSUE THREAD

**Issue by fangqi5** [ice-lab/icestark#452]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
主应用页面通过script引用了polyfill，同时引入了ErrorBoundary；子应用中同样使用script引用polyfill，在沙箱中执行js时polyfill报错不能同时存在多份实例，触发ErrorBoundary。
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**
由于浏览器沙箱会共享主应用实例，并不能做到完全隔离，是否可以考虑解析子应用js时，如果是script加载的资源，使用isAssetExist(handleAssets.ts中现有方法)判断下主应用里是否有同样的依赖，如果有则不重复执行；

**Comment by maoxiaoke** [comment]
参考[图例](https://micro-frontends.ice.work/docs/guide/concept/workflow#%E5%9B%BE%E7%A4%BA)，icestark 通过 sandbox 执行的代码会通过 `window.fetch` 来访问资源。若开启沙箱，会隔离对全局变量的修改。

可以复现个通过沙箱执行导致 polyfill 失败的最小 case
