### ISSUE TITLE
如何在各个独立子应用之间主动跳转到其他的子应用进行路由跳转

### ISSUE THREAD

**Issue by liqupan** [ice-lab/icestark#456]
子应用A：http://xxxxxxxx/a/page/home
子应用B：http://xxxxxxxx/b/page/home
如果在应用A中有一个按钮点击跳转history.push('/b/page/home');
这个时候跳转路径就会变成 http://xxxxxxxx/a/b/page/home，还会附带我当前子应用的activePath，就不会跳转到想去的页面。
这个问题如何解决呀。

**Comment by maoxiaoke** [comment]
应用间跳转使用 [appHistory](https://micro-frontends.ice.work/docs/api/ice-stark-app/#apphistory) api
