### ISSUE TITLE
请问一下主应用支持Vue3嘛

### ISSUE THREAD

**Issue by lemonly14** [ice-lab/icestark#458]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by maoxiaoke** [comment]
支持的~ 我们正准备将官方的 [Vue 主应用升级](https://github.com/ice-lab/vue-materials/tree/master/scaffolds/icestark-framework-app)为 Vue3。欢迎给我们提 pr

**Comment by lemonly14** [comment]
我一直找不到相关的例子  大佬能提供一下嘛

**Comment by maoxiaoke** [comment]
@lemonly14 好的，我这两天处理一下~

**Comment by lemonly14** [comment]
> @lemonly14 好的，我这两天处理一下~

好的  感谢大佬~

**Comment by maoxiaoke** [comment]
参考这个 Demo https://github.com/maoxiaoke/icestark-framework-vue3.x

或通过 https://micro-frontends.ice.work/docs/guide/use-layout/vue 命令生成（官方脚手架已替换成 Vue3.x）。

**Comment by maoxiaoke** [comment]
参考官方脚手架：https://micro-frontends.ice.work/docs/guide/use-layout/vue 命令生成（官方脚手架已替换成 Vue3.x）。

```shell
npm init ice icestark-layout @vue-materials/icestark-layout-app
```
