### ISSUE TITLE
使用ice2.x版本新生成的子应用无法通过entry的方式对接老的主应用

### ISSUE THREAD

**Issue by mzgwork** [ice-lab/icestark#461]
主应用ice版本为1.18.5
子应用是通过ice的官方模板自动生成的，未做任何修改，ice版本为2.2.3
在主应用中通过entry的方式接入新拉的子应用，会报错：
`Cannot use import statement outside a module`
主应用中的接入代码为
```
{
    path: '/test',
    title: 'ice子应用',
    sandbox: true,
    entry: 'http://localhost:3335',
  },
```
> 备注：使用ice版本为1.x可以用相同方式将子应用接入主应用

**Comment by maoxiaoke** [comment]
@mzgwork 官方微应用模板已切换为 [Vite （ESM）应用开发模式](https://micro-frontends.ice.work/docs/guide/use-child/others#vite-%E5%BA%94%E7%94%A8)。

1. 若要支持 ESM 应用接入，可开启 [loadScriptMode: import](https://micro-frontends.ice.work/docs/guide/use-child/others#vite-%E5%BA%94%E7%94%A8)

2. 或者微应用移除 Vite 模式，进行降级

**Comment by mzgwork** [comment]
已解决，谢谢
