### ISSUE TITLE
使用官网创建子应用命令创建出来的子应用，从主应用加载之后报错

### ISSUE THREAD

**Issue by edc-hui** [ice-lab/icestark#464]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
![image](https://user-images.githubusercontent.com/33356467/144017073-67ab096d-2517-4690-952c-98a90645b104.png)

报错如图所示
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**
不报错，寻求解决思路

**Comment by edc-hui** [comment]
官网命令：npm init ice icestark-child @icedesign/stark-child-scaffold

**Comment by maoxiaoke** [comment]
这个 [issue](https://github.com/alibaba/ice/issues/4980) 的关联
