### ISSUE TITLE
使用已有react项目改造微应用，注册到框架应用后子应用页面Failed to fetch

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [ice-lab/icestark#470]
浏览器报错如下:

<img width="1284" alt="截屏2021-12-05 下午5 11 04" src="https://user-images.githubusercontent.com/11502089/144740590-400420be-868c-423c-9b73-d75ec18ee6ba.png">

**Comment by hyuanyuanlisiwei** [comment]
![截屏2021-12-05 下午9 16 54](https://user-images.githubusercontent.com/11502089/144748159-5c716994-b182-4856-8db8-55ace6de199f.png)
这个entryContent 该怎么用啊

**Comment by hyuanyuanlisiwei** [comment]
或者  怎么才能让 该 html url 支持 fetch

**Comment by maoxiaoke** [comment]
@hyuanyuanlisiwei

跨域问题
https://stackoverflow.com/questions/31602697/webpack-dev-server-cors-issue

可通过 webpack-dev-server 进行跨域配置，参考 https://micro-frontends.ice.work/docs/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E5%BC%80%E5%8F%91%E6%97%B6%E8%AF%B7%E6%B1%82%E6%9C%AC%E5%9C%B0-mock-%E6%8E%A5%E5%8F%A3
