### ISSUE TITLE
通过脚手架创建的主应用和子应用没办法挂载

### ISSUE THREAD

**Issue by xcore-oss** [ice-lab/icestark#471]
通过脚手架创建的主应用和子应用没办法挂载
修改主应用配置为：
`
        path: '/seller',
        title: '商家平台',
        loadScriptMode: 'import',
        // React app demo: https://github.com/ice-lab/react-materials/tree/master/scaffolds/icestark-child
        url: [
          '//localhost:4001/build/js/app.js',
          '//localhost:4001/build/css/app.css',
        ],
`
页面输出：Cannot read properties of null (reading 'mount')
控制台输出：[@ice/stark] microapp should export mount/unmout or register registerAppEnter/registerAppLeave.
没有修改其他任何内容

**Comment by maoxiaoke** [comment]
@xcore-oss 建议通过 [entry](https://micro-frontends.ice.work/docs/guide/use-child/others#%E4%B8%BB%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD-vite-%E5%BA%94%E7%94%A8) 方式来加载。

因为在 vite dev 模式下，入口文件并非 serve 在 `build/js/app.js`。直接修改成：

```js
// url: [ '//localhost:4001/build/js/app.js', '//localhost:4001/build/css/app.css', ]，这一行移除
entry: 'https://localhost:4001'
```

**Comment by xcore-oss** [comment]
[
      "build-plugin-icestark",
      {
        "type": "child"
      }
    ],
build.json这句会导致浏览器报Not allowed to load local resource: file://

**Comment by maoxiaoke** [comment]
@xcore-oss 报错具体截图看下

**Comment by xcore-oss** [comment]
![image](https://user-images.githubusercontent.com/44192818/144981986-f982455d-09d9-48a7-b51e-505509e42d89.png)
![image](https://user-images.githubusercontent.com/44192818/144982037-c0094123-a1a9-4422-af7e-e12801c70a79.png)
删除后不报错，但是主应用就没法找到了
![image](https://user-images.githubusercontent.com/44192818/144982163-aa0ad252-da54-4ddf-9b9f-0a6c0e3172f9.png)
![image](https://user-images.githubusercontent.com/44192818/144982189-06bd5f99-a81c-47e9-8aaa-0712e31d9ff1.png)

**Comment by xcore-oss** [comment]
![image](https://user-images.githubusercontent.com/44192818/144983329-7259f42d-de63-4085-93fe-71aba517b318.png)
![image](https://user-images.githubusercontent.com/44192818/144984858-127f9dee-92a0-4f1f-ba8b-ad08738d0c67.png)
删除loadScriptMode: 'import',后
![image](https://user-images.githubusercontent.com/44192818/144984917-ef07f72e-a4ac-463f-b81b-e3b072ddb25b.png)
![image](https://user-images.githubusercontent.com/44192818/144984962-bc24d229-7951-4ad1-adf7-ea2200d31204.png)

**Comment by maoxiaoke** [comment]
@xcore-oss 应该是zhe这个问题导致的
![image](https://user-images.githubusercontent.com/13417006/145005282-e100129d-f4d4-4309-bc4a-133533a3872f.png)

返回的 HTML 的内容贴一下

**Comment by xcore-oss** [comment]
![image](https://user-images.githubusercontent.com/44192818/145130318-ed59b385-d46f-4679-9edc-141ad6c02241.png)
确实多了个module

**Comment by maoxiaoke** [comment]
@xcore-oss 最后 script 的 src 确认是有问题的，方便提供一个 demo 给我看下构建的 html 为啥不正确吗

**Comment by xcore-oss** [comment]
[system.zip](https://github.com/ice-lab/icestark/files/7673097/system.zip)
就是模板生成的啥也没动，试过在其他项目添加插件也是一模一样的问题

**Comment by xcore-oss** [comment]
也试过把所有包手动升级到最新版也没用

**Comment by maoxiaoke** [comment]
@xcore-oss

**Comment by xcore-oss** [comment]
问题好像越来越严重了
Internal server error: entry.includes is not a function
![image](https://user-images.githubusercontent.com/44192818/146700063-85ad0a8a-2da4-42a5-b004-2eb361c2d3b1.png)
![image](https://user-images.githubusercontent.com/44192818/146700092-8d3df034-8dbe-4f86-af2e-9cafdf6f6add.png)

**Comment by maoxiaoke** [comment]
@xcore-oss 有更新下依赖吗？

**Comment by xcore-oss** [comment]
更新了  不更新就不会又这个错误了

**Comment by maoxiaoke** [comment]
@xcore-oss 我这边试了下，是没有报错的~ 

package.json 和 build.json 发一下，是不是某个包版本依赖锁住了导致。

**Comment by maoxiaoke** [comment]
因为代码里其实没有 entry.includes 这个代码，而是 _entry.includes 

vite-plugin-index-html 的版本是多少？

**Comment by xcore-oss** [comment]
我把node_modules都删除重新下载了还是一样
vite-plugin-index-html版本还是2.0.0
![image](https://user-images.githubusercontent.com/44192818/146706166-cb0752c3-006c-40a3-83ce-22bc7196982a.png)

**Comment by maoxiaoke** [comment]
https://www.npmjs.com/package/vite-plugin-index-html/v/2.0.1 @xcore-oss 应该这个版本才对

**Comment by maoxiaoke** [comment]
用的什么源呢，导致没下载正确的包

**Comment by xcore-oss** [comment]
是啊  我看到你发布了2.0.1的  可是我本地重新下载的还是2.0.0

**Comment by xcore-oss** [comment]
https://registry.npm.taobao.org/

**Comment by xcore-oss** [comment]
![image](https://user-images.githubusercontent.com/44192818/146706595-1f1673c3-5841-46e9-8888-34bd2285f1c1.png)
你发布了新版本但是你没改插件版本

**Comment by maoxiaoke** [comment]
`^` 的语义是会自动升级的~ 
是不是有 lock 文件？

**Comment by xcore-oss** [comment]
现在可以了  感谢
