### ISSUE TITLE
子应用在主应用中调试遇到403

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [ice-lab/icestark#472]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
主应用端口3333   子应用端口个8000
子应用更改 axios baseUrl  解决了跨域问题.
但是出现403

<img width="1046" alt="截屏2021-12-06 上午11 38 28" src="https://user-images.githubusercontent.com/11502089/144783360-76ff90c1-fbd8-44ff-abaa-6483440e3498.png">
<img width="1033" alt="截屏2021-12-06 上午11 38 34" src="https://user-images.githubusercontent.com/11502089/144783368-6bcf0f6f-e341-46ff-a366-c877c4b9a438.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**
期望能在本地主应用里边正常调试微应用

**Comment by maoxiaoke** [comment]
@hyuanyuanlisiwei authentication 这个 api 是哪个应用的。而且资源跨域也不建议通过 axios 的 baseur 来处理

**Comment by hyuanyuanlisiwei** [comment]
> 。

微应用的

**Comment by hyuanyuanlisiwei** [comment]
> @hyuanyuanlisiwei authentication 这个 api 是哪个应用的。而且资源跨域也不建议通过 axios 的 baseur 来处理

点击哪个登录接口 报的403

**Comment by hyuanyuanlisiwei** [comment]
> @hyuanyuanlisiwei authentication 这个 api 是哪个应用的。而且资源跨域也不建议通过 axios 的 baseur 来处理

啥是资源跨域啊

**Comment by maoxiaoke** [comment]
@hyuanyuanlisiwei 403 状态码标识没有权限~ 和你们后端对接下
