### ISSUE TITLE
本地应用加载脚手架创建的微模块, 怎么设置url

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [ice-lab/icestark#473]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
微模块的地址是: http://localhost:3334/
本地应用怎么引入微模块的url 这样写,  没有效果
<img width="659" alt="截屏2021-12-06 下午2 53 03" src="https://user-images.githubusercontent.com/11502089/144801027-06929df3-1109-4632-9760-5eb4872fa3a6.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by hyuanyuanlisiwei** [comment]
> **Do you want to request a _feature_ or report a _bug_?**
> 
> **What is the current behavior?** 微模块的地址是: http://localhost:3334/ 本地应用怎么引入微模块的url 这样写, 没有效果 <img alt="截屏2021-12-06 下午2 53 03" width="659" src="https://user-images.githubusercontent.com/11502089/144801027-06929df3-1109-4632-9760-5eb4872fa3a6.png">
> 
> **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
> 
> **What is the expected behavior?**

改成这样也不对: 
const moduleInfo = {
  name: 'moduleName',
  url: 'http://localhost:3334/app.js',
}

**Comment by maoxiaoke** [comment]
@hyuanyuanlisiwei 微模块用什么项目启动的

**Comment by hyuanyuanlisiwei** [comment]
> @hyuanyuanlisiwei 微模块用什么项目启动的
就是用icestark官方脚手架创建 然后npm start

**Comment by maoxiaoke** [comment]
@hyuanyuanlisiwei   应该在 http://localhost:host/index/index.js 可以访问到吧

**Comment by maoxiaoke** [comment]
升级 build-plugin-stark-module 插件。详见 [pr](https://github.com/alibaba/ice/commit/a9af9598812fa21b1eed1e48df0110d956938484)
