### ISSUE TITLE
子应用的html中有个polyfill.js的引入,  导致第二次进入该子应用报错

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [ice-lab/icestark#474]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
主应用中第一次加载子应用正确,  切换到子应用, 再回到该子应用 白屏, 控制台报错
<img width="946" alt="截屏2021-12-06 下午3 26 46" src="https://user-images.githubusercontent.com/11502089/144805051-0aef72a1-4c3d-44c2-9b50-07969dec8457.png">
<img width="1181" alt="截屏2021-12-06 下午3 26 59" src="https://user-images.githubusercontent.com/11502089/144805074-23c90ff2-0057-4257-9ca8-f1bb0951d0cb.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by maoxiaoke** [comment]
@hyuanyuanlisiwei 有些资源不支持多实例，目前可选择的方案

1. 主应用来消费这个资源
2. 引入执行沙箱
