### ISSUE TITLE
entry方式启动的实例，如果启动两个同样的entry，第二个会把第一个干掉吗

### ISSUE THREAD

**Issue by nigelXia** [ice-lab/icestark#481]

**Comment by maoxiaoke** [comment]
指的是下面这种方式：

```js
[{
  name: 'a'
  activePath: ['/a'],
  entry: www.same.com
}, {
{
 name: 'b'
  activePath: ['/b'],
  entry: www.same.com
}
}]
```

这样是不会的，因为 icestark 会将其识别为不同的应用。不过建议如下使用：

```js
[{
  name: 'a'
  activePath: ['/a', '/b'],
  entry: www.same.com
},]
```

**Comment by nigelXia** [comment]
![image](https://user-images.githubusercontent.com/80448030/145525347-67872724-d770-4200-8ece-23697a471585.png)
![image](https://user-images.githubusercontent.com/80448030/145525417-7b79ace4-fed6-4cb7-bdfa-f3e7ea4205e2.png)
同一个实体，打开了两个不同的路径，打开第二个的时候第一个子应用的实体不见了。

**Comment by nigelXia** [comment]
用的官方demo

**Comment by maoxiaoke** [comment]
@nigelXia 改成 url 的方式呢？

**Comment by nigelXia** [comment]
@maoxiaoke 效果和entry的一样

**Comment by maoxiaoke** [comment]
@nigelXia https://github.com/maoxiaoke/icestark-multi-tabs/blob/176a44ce4e8693e5f45a53b134c4e62d62df4b41/src/layouts/BasicLayout/menuConfig.tsx#L55 官方的 case 也使用的是同一份资源

**Comment by nigelXia** [comment]
@maoxiaoke 
![image](https://user-images.githubusercontent.com/80448030/145739586-f5bee594-5541-46c0-9dac-3cec345af227.png)
我这边也是用的同一个子应用，但是我们的子应用是vue的。

**Comment by maoxiaoke** [comment]
@nigelXia icestark 通过 name 来标识不同的应用，正常情况下就算是两个应用脚本完全一致，相互之间也不会有冲突
