### ISSUE TITLE
angular框架子应用没法使用

### ISSUE THREAD

**Issue by zhangjianweibj** [ice-lab/icestark#485]
基座使用的是vue框架，按照文档说明。子应用是angular 8项目。子应用加载不出来，各种异常。angular框架是否能够支持？

**Comment by maoxiaoke** [comment]
@zhangjianweibj https://micro-frontends.ice.work/docs/guide/use-child/others#angular-%E5%BA%94%E7%94%A8 有参考这里的接入方式吗

**Comment by zhangjianweibj** [comment]
是的，只有这个地方有接入说明。试了多个angular项目，没一个能成功的。

**Comment by maoxiaoke** [comment]
https://github.com/maoxiaoke/icestark-angular-12 @zhangjianweibj 官方提供了 angular 12 的示例

**Comment by zhangjianweibj** [comment]
应了angular7以及angular8的项目，页面都加载不出来。严重怀疑这个框架不支持angular

**Comment by maoxiaoke** [comment]
@zhangjianweibj Angular 对 icestark 这总导出生命周期的框架并不友好。你可以提供下简单的 demo，我这边试着运行下

**Comment by maoxiaoke** [comment]
Closed for https://github.com/ice-lab/icestark/issues/553
