### ISSUE TITLE
主应用路由切换，子应用页面没有变化

### ISSUE THREAD

**Issue by JimmyZDD** [ice-lab/icestark#488]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
主应用路由切换，子应用页面没有变化
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
ice.js 2.x 主应用，vite + vue3 子应用；
首次进入子应用： 主应用路由切换，子应用页面预期变化
第二次进入vue3子应用：主应用路由切换，子应用页面没有变化
**What is the expected behavior?**
主应用路由切换，子应用页面预期变化

**Comment by maoxiaoke** [comment]
@JimmyZDD 页面有哪些具体的报错信息吗？

**Comment by JimmyZDD** [comment]
没有报错信息
1、主应用路由 pathname log 正常
2、子应用没响应
子应用挂载方法
```
{
  name: 'vue',
  path: '/vue',
  loadScriptMode: 'import',
  entry: 'http://localhost:3335',
}
```

**Comment by JimmyZDD** [comment]
[icestark-demo.zip](https://github.com/ice-lab/icestark/files/7762498/icestark-demo.zip)

**Comment by maoxiaoke** [comment]
@JimmyZDD https://github.com/maoxiaoke/icestark-vite-vue/commit/855e1387d75dd8db0338a4658d818f63d5e933c0 模板更新了，看一下我的修改

这个问题的原因是：esm 资源加载时，不会重复执行已经执行过的代码。因此 routes 在第二次加载的时候已经变化了，需要每次都重建实例。
