### ISSUE TITLE
vite子应用的资源引入问题

### ISSUE THREAD

**Issue by winljm001** [ice-lab/icestark#489]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
vite子应用图片资源路径有问题，不能正常显示
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
主应用按照文档中react主应用脚手架生成，子应用使用vite+react的hello world,然后根据其他框架接入微应用中的Vite 应用改造
![image](https://user-images.githubusercontent.com/26362957/146865316-9a566b6d-a3bb-4f08-b8ec-1e0185be8c0d.png)
子应用单独跑能正常显示
![image](https://user-images.githubusercontent.com/26362957/146866593-3ed90cf9-064e-4638-b62f-eb6b542e21b9.png)

**What is the expected behavior?**
子应用图片正常显示

**Comment by maoxiaoke** [comment]
建议通过  [__webpack_public_path__](https://webpack.js.org/api/module-variables/#__webpack_public_path__-webpack-specific) 进行 publicPath 补全。

在文件入口处：

```js
__webpack_public_path__ = isDev ? `localhost://127.0.0.1:${port}` : 线上地址
```

或者将图片上传图床，使用绝对地址加载

**Comment by MrKAries** [comment]
vite不支持[webpack_public_path](https://webpack.js.org/api/module-variables/#__webpack_public_path__-webpack-specific)，所以只有使用绝对地址加载了？

**Comment by catcheesetail** [comment]
> vite不支持[webpack_public_path](https://webpack.js.org/api/module-variables/#__webpack_public_path__-webpack-specific)，所以只有使用绝对地址加载了？
> 
> vite 支持 public path

遇到了同样的问题 请问怎么解决的？
