### ISSUE TITLE
文档能否更新下 props这个的属性的使用方法

### ISSUE THREAD

**Issue by theecn** [ice-lab/icestark#492]
**Do you want to request a *feature* or report a *bug*?**
无法官方文档、官方实例，得知props的真正用法，文档里是这么写的 
![image](https://user-images.githubusercontent.com/22100544/146918200-1d9a2b54-85b9-45b5-b1b0-87ff1a61ed2d.png)
但是实际上官方克隆出来的项目代码结构和app.tsx是这样的
![image](https://user-images.githubusercontent.com/22100544/146918280-4fd1a6f5-cc88-4a08-af4c-d5a0b8b422fb.png)
 能否更新下文档 或者 官方的demo！ 感谢
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by maoxiaoke** [comment]
https://ice.work/docs/guide/advanced/icestark#%E5%90%91%E5%BE%AE%E5%BA%94%E7%94%A8%E9%80%8F%E4%BC%A0-props

ice 应用使用插件 build-plugin-icestark 封装了改造逻辑

**Comment by theecn** [comment]
1. 上边的图是官方的克隆的容器项目，加了 props参数，
![image](https://user-images.githubusercontent.com/22100544/147021436-866b5495-feca-4223-860f-a674c22c74d8.png)
2. 子项目的打印
![image](https://user-images.githubusercontent.com/22100544/147021594-fe6b193f-0be5-44ae-bf5c-a9011cbc2f77.png)
3. 浏览器输出的内容
![image](https://user-images.githubusercontent.com/22100544/147021482-db036766-2191-41be-8d4b-1a0bcfbce2b6.png)
##### 重启容器应用和子应用都没办法拿到正确的props值

**Comment by theecn** [comment]
重新克隆了下 官方的demo，发现只有加了```loadScriptMode: 'import',```，子应用才能拿到容器传入的props参数，这个是为什么呢--

**Comment by maoxiaoke** [comment]
@theecn UMD 模式和 Vite 模式都支持
