### ISSUE TITLE
history 实例问题

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icestark#50]
## 背景

目前每个微应用的路由定义用的都是自己的 history 实例，导致跨应用跳转必须依赖 appHistory/AppLink，如果是从 A 应用跳转到 B 应用，这样是符合逻辑的。

但是这里有两个问题：

1. 当框架应用自身包含一些路由时（基于 react-router），菜单上的链接应该用 AppLink 还是 Link？AppLink 无法跳转到框架自身的页面，Link 无法跳转到微应用的页面，业务上必须得动态判断区分使用，比较繁琐。
2. 假设框架应用有 A&B 两个菜单（通过 AppLink）指向同一个微应用的两个页面，先点击 A 加载 A 页面，再点击 B，此时因为使用了 AppLink（history 实例的问题不得不使用）因此会强制触发微应用的资源重新加载一次，体验上有损。

## 方案

1. 对于框架应用包含路由的情况，支持 AppRouter 跟应用自身的 react-router 共用 history 实例
2. 提供机制让所有应用使用同一个 history 实例，业务可按需使用优化体验

**Comment by imsobear** [comment]
方案：icestark 监听到路由变化，然后主动触发 popstate

**Comment by daysai** [comment]
实际操作方案，劫持 window.addEventListener 从中记录由子应用路由添加的 popStateListener ，然后每次 pushState、replaceState 时手动触发一次 popStateListener()。达到子应用内部路由监听得到触发～
代码已实现，确实能优化体验：
1. 进一步弱化了 AppLink 的使用场景
2. 在同应用间跳动不再需要资源加载。

**Comment by daysai** [comment]
详见 #47
