### ISSUE TITLE
Could not resolve "react"

### ISSUE THREAD

**Issue by hls-1992** [ice-lab/icestark#501]
我的主应用安装@ice/stark 2.7.1的版本
主应用采用vite + vue3
运行时出现了下方报错
node_modules/@ice/stark/lib/AppLink.js:23:23: error: Could not resolve "react" (mark it as external to exclude it from the bundle)

不是很清楚原因，这个react有什么关系呢

**Comment by maoxiaoke** [comment]
https://micro-frontends.ice.work/docs/api/ice-stark-app

对于 Vue 应用，我们建议直接从 lib 下导入
