### ISSUE TITLE
微应用： 子应用中自定义生命周期函数之后收不到父应用传来的props

### ISSUE THREAD

**Issue by wumengzhuo** [ice-lab/icestark#504]
我在子应用中使用自定义的生命周期函数
![image](https://user-images.githubusercontent.com/26699882/148049906-d1fcfe59-0b7a-4524-b1de-caa68a74f0d7.png)
![image](https://user-images.githubusercontent.com/26699882/148049973-1b0edb7d-7d12-48ce-89da-a48cc687e4bf.png)

父应用是子应用模板通过手动加载的方式引入另一个子应用的
![image](https://user-images.githubusercontent.com/26699882/148050062-8d3a03b0-926e-4dd2-8549-c9f5463de74c.png)

在issues中找到别的问题， 更新build-plugin-icestark插件到最新版本还是接收不到， 加上$$props：props也不行

希望自定义生命周期的时候能正常接收到父应用传来的props

**Comment by maoxiaoke** [comment]
贴一下子应用的 build.json

**Comment by wumengzhuo** [comment]
![image](https://user-images.githubusercontent.com/26699882/148051498-c8fe49a5-39c4-4758-943f-6b73aa6dd5e2.png)

**Comment by maoxiaoke** [comment]
我大概明白了。不需要自定义生命周期，ice 微应用默认内置透传 props 

https://ice.work/docs/guide/advanced/icestark#%E5%90%91%E5%BE%AE%E5%BA%94%E7%94%A8%E9%80%8F%E4%BC%A0-props

现在你需要做的是

1. 移除微应用的自定义生命周期
2. 通过页面组件的 props 获取到，参文档
