### ISSUE TITLE
支持blazor webassembly框架吗？.net 系的

### ISSUE THREAD

**Issue by bingxueyinlian** [ice-lab/icestark#513]
请问一下：
支持blazor webassembly框架吗？.net 系的
还有现有老系统怎么接入，jquery,asp.net,jsp开发的。

**Comment by huangyungeng** [comment]
> 对于较老的系统，我们建议 iframe [接入](https://micro-frontends.ice.work/docs/guide/use-layout/react/#%E5%BE%AE%E5%BA%94%E7%94%A8%E5%85%A5%E5%8F%A3-entryentrycontenturl)。
> 
> ```js
> <AppRoute
>   activePath="/foo"
>   render={() => {
>     return <iframe src="" />;
>   }}
> />
> ```

主应用使用Vue3的如何使用
