### ISSUE TITLE
跑项目的时候，报错Uncaught Error: Current page does not exist <div id="ice-container"></div> element.

### ISSUE THREAD

**Issue by vouis** [ice-lab/icestark#516]
![image](https://user-images.githubusercontent.com/28481991/150107065-e73651e8-fc04-4970-a677-c230f2faf3f2.png)
这个是报错截图
同样的代码，我同事跑得起来，但是我跑不起来:(
从报错上来看是在尝试获取ice-container元素，但是页面没有这个元素
那怎样才能有这个元素呢

**Comment by maoxiaoke** [comment]
具体项目是怎么启动呢？单独启动，还是集成在主应用启动？
