### ISSUE TITLE
主应用接入微应用，切换路由后微应用样式消失，刷新页面样式出现，再切换又会消失

### ISSUE THREAD

**Issue by shenaicong** [ice-lab/icestark#517]
主应用为官方提供的demo         npm init ice icestark-layout @vue-materials/icestark-layout-app
微应用也是官方提供的demo     https://github.com/maoxiaoke/icestark-vite-vue
和                                               npm init ice icestark-child @vue-materials/icestark-child-app

主应用接入微应用，切换路由后微应用样式消失，刷新页面样式出现，再切换又会消失
![image](https://user-images.githubusercontent.com/80328599/150246331-60f03351-ea73-4a2d-9401-321a69f17ffa.png)

我就改了entry的地址，其他的都没改，但是看主应用中默认引用的地址却没有这个问题，切换路由样式并不会消失

这个需要做什么才可以让样式保留，不消失

**Comment by Gitchengjiqiang** [comment]
路由中引入页面不要使用component: () => import('@***),

**Comment by shenaicong** [comment]
> 路由中引入页面不要使用component: () => import('@***),

都是官方的demo并没有使用component: () => import('@***),
