### ISSUE TITLE
子应用如何重定向到主应用

### ISSUE THREAD

**Issue by edc-hui** [ice-lab/icestark#523]
前提：
用的是icejs模板创建的主应用和子应用。icejs版本是2.4.3

描述：
登录页放在主应用里面，子应用里面有个退出按钮，点击之后，退回到主应用的登录页面。我这边采用 appHistory.push('/')重定向到主应用（主应用的路由配置中 / 对应的就是登录页），退回之后再进入子应用就会报下图错误。
![image](https://user-images.githubusercontent.com/33356467/150930754-26a8cdc3-035f-4ec3-a418-3a6013608a2f.png)

问题：
请问子应用应该怎么样重定向到主应用中。

**Comment by maoxiaoke** [comment]
从错误栈来看，似乎并非是 icestark 的问题

**Comment by edc-hui** [comment]
@maoxiaoke 嗯嗯 感谢  刚刚测试把项目中的一个包移除即可通过appHistory.push('/')进行跳转。不是icestark 的问题。麻烦了，我看下为什么这个第三方包会引起这个问题
