### ISSUE TITLE
切换子应用应用后，vue2-ace-editor 组件样式丢失

### ISSUE THREAD

**Issue by hashwing** [ice-lab/icestark#524]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

切换子应用应用后，vue2-ace-editor 组件样式丢失

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by maoxiaoke** [comment]
https://micro-frontends.ice.work/docs/faq#%E5%88%87%E6%8D%A2%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B8%BB%E5%BA%94%E7%94%A8%E6%A0%B7%E5%BC%8F%E4%B8%A2%E5%A4%B1 

这个原因导?

**Comment by hashwing** [comment]
你好，你的邮件已收到，祝你身体健康，学业进步

**Comment by hashwing** [comment]
> 是否是这个原因导致的
> 
> https://micro-frontends.ice.work/docs/faq#%E5%88%87%E6%8D%A2%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B8%BB%E5%BA%94%E7%94%A8%E6%A0%B7%E5%BC%8F%E4%B8%A2%E5%A4%B1

应该不是，vue2-ace-editor 是在子应用引入的，切换到别的子应用，再切换回来就出现样式丢失

**Comment by maoxiaoke** [comment]
@hashwing 这个 vue2-ace-editor 的样式是单独加载的？

**Comment by hashwing** [comment]
> @hashwing 这个 vue2-ace-editor 的样式是单独加载的？

@maoxiaoke 不是的，组件内部加载的

**Comment by xiaoxintang** [comment]
[主应用带路由](https://micro-frontends.ice.work/docs/guide/use-layout/react/#%E4%B8%BB%E5%BA%94%E7%94%A8%E4%B8%AD%E5%A6%82%E4%BD%95%E5%8C%85%E5%90%AB%E8%B7%AF%E7%94%B1%E9%A1%B5%E9%9D%A2)这种方式，切换到子应用，然后切换回主应用，点击浏览器的前进后退，切来切去，发现主应用的路由页面样式没有加载进来

**Comment by maoxiaoke** [comment]
https://micro-frontends.ice.work/docs/api/ice-stark#shouldassetsremove @hashwing 这个字段应该
