### ISSUE TITLE
子应用跳转到框架应用的页面失败

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icestark#53]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
- 框架应用通过 react-router 定义了一些路由
- 子应用通过 window.history 跳转到框架应用的路由，此时会出现 404 的情况，初步判断是对 `addEventListener.popstate` 的劫持时机问题，导致无法触发框架应用中 react-router 监听 popstate 的回调
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by ClarkXia** [comment]
fixed in version 1.4.0
