### ISSUE TITLE
通过脚手架创建 react 微应用接入，框架应用采用的是vue3+vite，进入该微应用时提示index.html 404

### ISSUE THREAD

**Issue by pyj063** [ice-lab/icestark#531]
通过脚手架创建 react 微应用接入，框架应用采用的是vue3+vite，进入该微应用时提示index.html 404

**Comment by pyj063** [comment]
handleAssets.js:470 GET http://localhost:3000/micro-react/index.html 404 (Not Found)

**Comment by maoxiaoke** [comment]
意思是：http://localhost:3000/micro-react/index.html 没有找到，确认下 url 地址是否正确

**Comment by pyj063** [comment]
你好  我分别用vue3与react作为子应用进入  vue3的是可以的，react是引用不一样吗？






















在 2022-02-17 16:54:56，"那吒" ***@***.***> 写道：

意思是：http://localhost:3000/micro-react/index.html 没有找到，确认下 url 地址是否正确

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pyj063** [comment]
{
      name: 'seller',
      activePath: '/seller',
      title: '商家平台',
      loadScriptMode: 'fetch',
      // React app demo: https://github.com/ice-lab/react-materials/tree/master/scaffolds/icestark-child
      // entry:
      // 'http://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-seller-ice-vite/index.html',
      entry: 'http://localhost:3000/micro-react/index.html',
      container
    },
    {
      name: 'waiter',
      activePath: '/waiter',
      title: '小二平台',
      loadScriptMode: 'import',
      // entry:
      //   'http://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-vue3-vite/index.html',
      entry: 'http://localhost:3000/mirco-vue3/index.html',
      container
    }

**Comment by maoxiaoke** [comment]
@pyj063 你访问下 entry 的链接，如果访问正常就是可以的

**Comment by pyj063** [comment]
大佬  http://localhost:3000/micro-react/index.html这个确实不能访问，但是http://localhost:3333/micro-react/  是可以的，而且vue3的一直ok  我还是不太明白  哪里配置的有问题

proxy: {
      "/mirco-react": {
        target: "http://localhost:3333",
        changeOrigin: true,
      },
      "/mirco-vue3": {
        target: "http://localhost:4007",
        changeOrigin: true,
      },
    },

**Comment by maoxiaoke** [comment]
@pyj063 那配置 http://localhost:3333/micro-react/ 这个地址呢，network 可以看下这个地址访问了哪个 html 地址

**Comment by pyj063** [comment]
@maoxiaoke    http://localhost:3333/micro-react/  这个是react微应用的项目，所以这个本地没问题，上面的代理代码是主应用中的配置，你的意思是 entry直接改成3333的端口地址？

**Comment by pyj063** [comment]
![image](https://user-images.githubusercontent.com/38978029/154449181-bf88e983-5a62-47d9-a9fb-dbe17e0f6003.png)

@maoxiaoke

**Comment by pyj063** [comment]
![image](https://user-images.githubusercontent.com/38978029/154450631-e414ba9e-74cf-4bb8-905b-274414aefd85.png)

换成3000的主应用  端口  就一直没有finish

**Comment by maoxiaoke** [comment]
@pyj063 
![image](https://user-images.githubusercontent.com/13417006/154471534-0db471ff-f800-42ce-ba9b-ae7ec5f387b2.png)
看下这个地址

**Comment by pyj063** [comment]
@maoxiaoke   大佬  1、react微应用可以了  解决方案是  build之后，采用url的引入css\js方式  --   这个没办法像vue3本地运行与主应用联调吗？

2、vue2+webpack微应用的方式 有点不行，报异常
![image](https://user-images.githubusercontent.com/38978029/154612942-dc70cd09-6446-4073-b20a-0ee825adedda.png)

![image](https://user-images.githubusercontent.com/38978029/154613067-2b6c02b2-c2b4-46d5-bea1-ef241e920cd0.png)

**Comment by maoxiaoke** [comment]
@pyj063 应该都是可以的，只是可能跟你 proxy 的配置有关。比如上面的那个错误，就是说返回的地址，类型不是 javascript 脚本，而是 html 类型。这些问题可以自己排查下的。
