### ISSUE TITLE
主应用（vite）和微应用（webpack）都用ice脚手架搭建，开发联调时 微应用的lazy加载js文件 访问到主应用上导致加载不了

### ISSUE THREAD

**Issue by weilaiqishi** [ice-lab/icestark#535]
主应用1333端口，微应用1334端口
![123](https://user-images.githubusercontent.com/22250972/155058116-56232e4d-07e7-4f46-a78a-181adf8dad2a.jpg)

**Comment by maoxiaoke** [comment]
https://ice.work/docs/config/about/#devpublicpath-

**Comment by weilaiqishi** [comment]
> https://ice.work/docs/config/about/#devpublicpath- 配置下这个参数，锁定下在 dev 下开发的 path

子应用配置这个可以了

**Comment by xmsz** [comment]
现在需要配置devPublicPath才能通过，好麻烦
