### ISSUE TITLE
子应用本地调试使用proxy，若主框架链接本地场景访问接口地址拼接问题

### ISSUE THREAD

**Issue by loydLee** [ice-lab/icestark#54]

**Comment by daysai** [comment]
子应用嵌入主框架调试时，请求接口没有 proxy 到子应用配置的后端服务上？

**Comment by loydLee** [comment]
子应用已经proxy了，独立运行正常  但是从主框架访问的时候接口访问不了

**Comment by daysai** [comment]
> 子应用已经proxy了，独立运行正常 但是从主框架访问的时候接口访问不了

这类问题，我们希望是框架应用对应的后端服务有一层“统一网关”。应用上线以后，接口一样会被转发到框架应用上。本地调试，可以通过主框架再一次 proxy 过去。
