### ISSUE TITLE
请问使用umi 2.x 为子应用应当如何配置子应用

### ISSUE THREAD

**Issue by mimimamahaoduozi** [ice-lab/icestark#542]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by maoxiaoke** [comment]
https://micro-frontends.ice.work/docs/guide/use-child/others#umi-%E5%BA%94%E7%94%A8 @mimimamahaoduozi 可以参考下这个，可能有些稍微不一样
