### ISSUE TITLE
主应用加载子应用，重复加载子应用，导致加载不成功

### ISSUE THREAD

**Issue by edc-hui** [ice-lab/icestark#544]
环境：
使用官方命令行创建出来的主应用和子应用
ice.js版本2.5.1

问题：
在主应用的app.tsx里面配置了一个子应用（path是/web），主应用有登录页面，登录成功后，直接使用history.push('/web/template-library')跳转到子应用里面的一个页面，主应用中监听了appLeave和app  enter,  此时控制台发现先是leave主应用然后enter子应用，立马又leave子应用，接着再次enter子应用，这样导致加载子应用报错。如下图所示：
![image](https://user-images.githubusercontent.com/33356467/156353068-2614ad39-cd42-4f01-8b16-74ed6b895a41.png)

图中错误出现后，其路径在/web/template-library下面，如果此时我点击浏览器刷新按钮，子应用就可以正常加载了。但是从登录页点击按钮加载子应用就会报上图的错误。

找了一天的原因，各种方法都试了  实在没思路，大佬给个思路，产品马上上线了

**Comment by edc-hui** [comment]
![image](https://user-images.githubusercontent.com/33356467/156353767-fe8d71aa-0af2-4e94-80f2-19d2ae3e342a.png)
补充说明：如果在FrameworkLayout中，我不用三元表达式去判断更换布局方式，全程只使用一种布局，那么子应用也可以正常加载，只要加上这个布局的判断，子应用就会报上图的错误。两个布局组件里面的代码全是一样的。如下图所示：
![image](https://user-images.githubusercontent.com/33356467/156354169-6bddc020-5733-4226-af07-2c831cb8410e.png)

**Comment by maoxiaoke** [comment]
@edc-hui 是不是 Framework 的 useEffect 导致重渲染了？

**Comment by edc-hui** [comment]
@maoxiaoke 感谢提供思路，目前已排查到是我这边的子应用导致的Framework 的 useEffect重复执行，新建的子应用是可以正常加载的，还在看子应用为什么会导致主应用重新渲染

**Comment by edc-hui** [comment]
@maoxiaoke 大佬  经过这几天的测试  我这边遇到的问题其根本原因是和https://github.com/ice-lab/icestark/issues/521 描述的是一样的，请问这个大概什么时候可以解决。

**Comment by maoxiaoke** [comment]
> @maoxiaoke 大佬  经过这几天的测试  我这边遇到的问题其根本原因是和https://github.com/ice-lab/icestark/issues/521 描述的是一样的，请问这个大概什么时候可以解决。

好的，这个应该已经修复好了。我尽快发布版本

**Comment by edc-hui** [comment]
@maoxiaoke 好的  感谢 静候佳音
