### ISSUE TITLE
[bug]MicroModule.moduleInfo.name  with the symbol `.` will appears error

### ISSUE THREAD

**Issue by radeon8** [ice-lab/icestark#546]
***bug***
when I use MicroModule , if moduleInfo'name has the symbol `.` ,  then navigate to another page，this error appears

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/5610115/156574673-1403f64e-b9ef-4821-b05a-69d0d3d63730.png)
![image](https://user-images.githubusercontent.com/5610115/156574795-39bbc783-f55a-4f49-ab59-bbf1baed1b2c.png)
```
const moduleInfo = {
    name: 'suite-isv.kkk.sss',
    url: [
      'https://upck.com/0.4/mobile/index.js',
    ],
    mount(ModuleComponent, mountNode, props) {
      console.log('ModuleComponent', ModuleComponent);
      ReactDOM.render(<ModuleComponent />, mountNode);
    },
  };
  return (
    <div>
      <MicroModule moduleInfo={moduleInfo} sandbox={{ multiMode: true }} />
    </div>
  );
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**
make moduleInfo`name. supports the symbol  `.`

**Comment by maoxiaoke** [comment]
It is rare to pass a module name like this. You can send me a pr if someone would do it actually.
