### ISSUE TITLE
ie11官网demo加载子应用空白，无任何报错提示

### ISSUE THREAD

**Issue by lolipop99** [ice-lab/icestark#547]
问题：
在ie11环境下，子应用加载空白，无任何报错提示。已做了fetch和includes等polyfill（用ie11单独访问主应用、子应用都正常）

chrome访问正常。

复现仓库
主应用：https://github.com/maoxiaoke/icestark-framework-vue2.x
微应用：https://github.com/maoxiaoke/icestark-child-vue2.x

@maoxiaoke 麻烦大佬看看

**Comment by maoxiaoke** [comment]
@lolipop99 ie 下没有错误提示吗

**Comment by lolipop99** [comment]
![image](https://user-images.githubusercontent.com/6138899/157195284-abd42fe1-61d2-4b7d-a34b-af8b2a8322b8.png)

@maoxiaoke 看了下好像是@ice/stark调用的start加载子应用url报错了，我polyfill直接在main.js引用`import 'babel-polyfill'`解决的

**Comment by lolipop99** [comment]
解决了大佬，我到时提个pr到这两个仓库吧

**Comment by maoxiaoke** [comment]
@lolipop99 好的，问题是什么呢
