### ISSUE TITLE
icestark 无法正确获取到生命周期函数

### ISSUE THREAD

**Issue by fengjingwork** [ice-lab/icestark#548]
按照官方文档配置，将已有React项目改造为微应用，配置代码都写在了react项目index.js入口文件中，且两种声明生命周期的方式都试过了，但主应用中一直报错提示Unable to retrieve lifecycles of react-app after loading it，请问具体应该如何解决

**Comment by fengjingwork** [comment]
另外还想问一下  在已有vue或react项目基础上改造为微应用，只需要安装依赖@ice/stark-app吗，是否还需要其它依赖

**Comment by maoxiaoke** [comment]
@fengjingwork 第一个还存在问题吗？

**Comment by maoxiaoke** [comment]
微应用默认是不依赖 @ice/stark-app。@ice/stark-app 提供了接入的 utils 方法，仍然是建议的选择。详细的方法列表 ：https://micro-frontends.ice.work/docs/api/ice-stark-app
