### ISSUE TITLE
资源访问问题

### ISSUE THREAD

**Issue by loydLee** [ice-lab/icestark#55]
Refused to apply style from 'http://localhost:4444/static/css/4.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by daysai** [comment]
> Refused to apply style from 'http://localhost:4444/static/css/4.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

此资源能否直接通过浏览器访问？icestark 对资源的处理是动态创建 link/sctipt 标签加载资源的。逻辑上不应该有这些问题。

**Comment by loydLee** [comment]
将本地8080端口运行的vue项目作为icestark的子服务，css文件通过localhost:8080/static/css/4.css能够直接访问，但是通过主框架访问的时候（即localhost:4444/static/css/4.css）无法访问，想请问下这是什么原因呢，子服务资源配置有什么特殊要求么？

**Comment by daysai** [comment]
> 将本地8080端口运行的vue项目作为icestark的子服务，css文件通过localhost:8080/static/css/4.css能够直接访问，但是通过主框架访问的时候（即localhost:4444/static/css/4.css）无法访问，想请问下这是什么原因呢，子服务资源配置有什么特殊要求么？

看着文件的命名上，是开启了懒加载机制？懒加载机制下，确认框架应用获取资源的完整 url 是否符合预期，可能需要配置 publicPath/devPublicPath，保障懒加载资源的请求路径。

**Comment by loydLee** [comment]
这里应该是子服务的组件采用了懒加载的原因，您说的publicPath配置指的是主框架还是子服务呢？

**Comment by daysai** [comment]
> 这里应该是子服务的组件采用了懒加载的原因，您说的publicPath配置指的是主框架还是子服务呢？

子应用的懒加载资源，应该配置在子应用上

**Comment by loydLee** [comment]
子服务配置了publicPath 但是组件懒加载产生的2.js.... 子服务下引用文件路径为/2.js  这对于子服务来说是没有问题的但是主框架下引用会出现找不到的问题  若要在主框架下访问，子服务的publicPath要修正为子服务的全地址吗？

**Comment by loydLee** [comment]
- -、感谢。 我修正为全地址后引用正常啦
