### ISSUE TITLE
将已有的Vue2改造成子前端的时候，子前端的分片JS请求错误

### ISSUE THREAD

**Issue by RandyZ** [ice-lab/icestark#554]
**Do you want to request a *feature* or report a *bug*?**
应该是个Bug
**What is the current behavior?**
按照[官方的文档](https://micro-frontends.ice.work/docs/guide/use-child/vue#%E5%B7%B2%E6%9C%89-vue-%E9%A1%B9%E7%9B%AE%E6%94%B9%E9%80%A0%E4%B8%BA%E5%BE%AE%E5%BA%94%E7%94%A8)改造了现有的工程，
想当作子前端引用，但是script加载并没有按照预期请求。

工程目前是是vue2的工程直接用`vue-cli-service serve`启动

父应用的地址是localhost:3000，改造的子应用为8000端口，但是父应用请求的分片JS地址不太对

父应用使用`npm init ice icestark-layout @vue-materials/icestark-layout-app`创建的

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
![image](https://user-images.githubusercontent.com/9149366/159274307-e209d2ca-c8a1-4653-bd58-e6daa76cbef8.png)

**What is the expected behavior?**

**Comment by joshualzb** [comment]
应该是你子应用的publicpath的问题

**Comment by RandyZ** [comment]
> 应该是你子应用的publicpath的问题

意思是子应用的publicpath？这个机制我有点不太明白。我的子应用单独运行的时候publicpath应该就是本应用的`/`。
被加载成子应用的时候才需要按照父应用注册的路径进行访问。
这种场景访问应该怎么配置能？麻烦给点详细的信息可以吗？感谢

**Comment by maoxiaoke** [comment]
Feel free to reopen if you are still in trouble.
