### ISSUE TITLE
子应用切换的时候，第二次切换到子应用的时候，子应用资源 disk cache了，但是没有生效. 

### ISSUE THREAD

**Issue by chencs-19950208** [ice-lab/icestark#575]
![image](https://user-images.githubusercontent.com/71002903/163980010-4fee6a17-89f2-4259-b266-7ded90ed5cde.png)

二次切换到的时候，资源在disk cache 中 
![image](https://user-images.githubusercontent.com/71002903/163981328-32dbcf29-0393-420c-83e9-f8187ff055a4.png)

项目demo地址：https://github.com/chencs-19950208/cool-front-container

**Comment by maoxiaoke** [comment]
错误一: 使用 AppRouter 的 React 方式接入，无需二次调用 start 方法
错误二：AppRoute 是 AppRouter 的直接子组件，使用方式：

```jsx
<AppRouter>
  <AppRoute />
</AppROuter>
```

下面的这种用法是错误的：

```jsx
<AppRouter>
  <>
    <AppRoute />
    <AppRoute />
  </>
</AppROuter>
```
