### ISSUE TITLE
使用useLocation报错

### ISSUE THREAD

**Issue by gdc1998** [ice-lab/icestark#579]
import { useLocation } from 'ice';
const a = useLocation();
报错
Cannot read properties of undefined (reading 'location')
function useLocation() {
  if (true) {
    !(typeof useContext === "function") ?  true ? (0,tiny_invariant__WEBPACK_IMPORTED_MODULE_11__["default"])(false, "You must use React >= 16.8 in order to use useLocation()") : 0 : void 0;
  }

  return useContext(context).location; 错误位置
}

**Comment by maoxiaoke** [comment]
@gdc1998 具体的错误信息是什么。请确认是否跟 icestark 相关。
