### ISSUE TITLE
cors

### ISSUE THREAD

**Issue by cube3power** [ice-lab/icestark#58]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by daysai** [comment]
哪方面的跨域问题？

**Comment by cube3power** [comment]
Access to font at 'http://ice.alicdn.com/icestark/fonts/element-icons.woff' from origin 'http://localhost:4444' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by daysai** [comment]
> Access to font at 'http://ice.alicdn.com/icestark/fonts/element-icons.woff' from origin 'http://localhost:4444' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

请描述下完整的操作路径，比如框架应用配置，启动方式，问题现场截图等等。
单这些描述不足以定位问题，可能是 publicPath 配置问题，可能是子应用配置问题

**Comment by daysai** [comment]
描述信息太少，sorry～

**Comment by BestDI** [comment]
> 描述信息太少，sorry～

你好, 你这个问题最后怎么解决的?怎么配置的publicPath, 我在主工程引用子工程的静态文件时404
