### ISSUE TITLE
fetch cdn 资源优化建议

### ISSUE THREAD

**Issue by chencs-19950208** [ice-lab/icestark#585]
jsList fetch的时候，目前源码中使用的promise.all，建议能否替换成 promise.allSettled （对每个cdn做监控，错误就抛出，正常的继续进行）

目前我们的业务中存在很多的cdn（不管是 urls 还是 htmlSrc 的方式），我们可能存在十个cdn地址，目前只有一个失败，九个是成功的，但是这一个失败的cdn，对于业务渲染是没有影响的。 所以在源码中如果使用 promise.all 一个fetch 失败了，则代表全部都失败了。并且阻塞渲染。

期待的结果:
对于每个cdn监控起来，失败的抛出错误，成功的继续进行，继续挂载，不阻塞渲染，页面正常渲染。

**Comment by maoxiaoke** [comment]
可以考虑针对某些资源设计一个额外处理的逻辑。

**Comment by chencs-19950208** [comment]
![image](https://user-images.githubusercontent.com/71002903/166860018-807095a9-1598-4962-a2eb-ad0407091fee.png)

诸如这种资源fetch错误（当然需要业务去解决），可以继续像这样，输出出来，但是这种资源在业务中对渲染是没有任何影响的，由于使用 promise.all  出现了一个错误，直接rejected ,  阻塞渲染，如果替换成 promise.allSettled 成功的收集起来继续挂载 （script or link 方式，以及或者 new Function ）。失败的也收集起来抛出，页面继续渲染。

**Comment by chencs-19950208** [comment]
出现一个fetch失败的资源，框架层面不应该一棒子打死，直接阻塞所有，框架层面继续资源挂载，页面渲染，出现的错误抛出，让业务处理。

**Comment by maoxiaoke** [comment]
@chencs-19950208 嗯嗯，我这边简单设计个方案

```js
url: [
 ['www.cdn/unblock.js', { block: false }],
 'www.cdn/index.js'
]
```

**Comment by chencs-19950208** [comment]
block 的设计是什么思路呢，具体含义。大佬

**Comment by chencs-19950208** [comment]
大佬的意思，是想通过block 的参数来解除失败的拦截是吗，分开fetch的意思？

**Comment by maoxiaoke** [comment]
@chencs-19950208 是的，其他 url 保持原有逻辑，标记为 block 的资源不阻塞，亦不报错

**Comment by chencs-19950208** [comment]
设计上虽然是可行的，也能解决问题，对于现有的底层设计侵入也比较小，但是需要业务自己去选择了，在接入上或许有点成本在里面，对于没有这个问题的情况，这个参数或许有点干扰以及迷惑，在业务第一次调试接入的时候，出现问题才会需要这个参数，我个人觉得还是框架内部自己去消化掉这个参数作用会比较好（这样或许对现有的底层设计影响比较大），但是对于接入方非常的友好。😄

**Comment by chencs-19950208** [comment]
而且对于html的接入方式不是特别友好，html的方式按道理只有一个html cdn地址，html模板上会挂载 N 多个cdn的js 以及 css，这时候无法对模板上 cdn 资源打上 block

**Comment by maoxiaoke** [comment]
@chencs-19950208 对于 html 的使用方式，可以在不 block 的脚本资源加上 async 标识符，这样 icestark 进一步处理成 unblock 资源

**Comment by chencs-19950208** [comment]
哦 哦，为了解决这个问题，成本陡然上升 😂

**Comment by maoxiaoke** [comment]
> 哦 哦，为了解决这个问题，成本陡然上升 😂

需要考虑向前向前兼容的，而且这毕竟也是一个小场景
