### ISSUE TITLE
如何实现类似于ALL/A，/ALL/B的路由

### ISSUE THREAD

**Issue by Sanmws** [ice-lab/icestark#587]
需求：主应用中的按二级菜单打包，部署时将二级菜单当成一个子应用引入。
目前在项目中碰到一个场景，就是一整个应用分模块开发，单个目录为一个模块。如下图：
![image](https://user-images.githubusercontent.com/96769836/167062466-eb5522f4-69a1-47ed-82e8-88151365b234.png)
其中数据中心单独打包，服务中心单独打包。他们的路由的形式在主应用中是A/B/C、A/D/F的形式，但是单个模块开发时是B/C、D/F的形式。这样的模式在主应用应该如何集成，，我尝试了多种方式都无法实现。有一些方式能渲染，但无法切换，一切换就显示匹配不到路由。
以下是我尝试过的方案：
1. 主应用增加basename，activity使用函数返回布尔值形式。结果：只能渲染一次，切换后再次点击显示路由无匹配或找不到页面。
2. 主应用的activityPath设置为：A/B，A/C，形式。结果：当路由时A/B/B/C的时候正常渲染，但是必须多一层B

想问下，碰到这种场景，应该如何设置主应用的basename和activityPath才能实现需求？

**Comment by maoxiaoke** [comment]
1. 你这种设计下，菜单不应该跟微应用耦合
2. 若数据中心对应一个微应用，可以统一为微应用分配一个 basename

**Comment by Sanmws** [comment]
> 1. 你这种设计下，菜单不应该跟微应用耦合
> 2. 若数据中心对应一个微应用，可以统一为微应用分配一个 basename

因为我们这个项目比较复杂，一个平台项目到时候会集成多个中台，比如业务安全只是其中一个。菜单如果不和微应用耦合的话，就要采取A/B/B/C这路由，因为后期会加入其他的平台，我们希望通过A这一层来区分那个中台，B这一层区分哪个菜单项。这样我们不需要再重新为微应用指定一个唯一的路由前缀。然后因为在一个中台下面的菜单项，名字是唯一的，比如数据中心，可能就是DataCenter，如果框架支持的话，我们希望不需要有那么多的唯一命名。

一个完整的平台格式差不多是这样：
业务安全- 数据中心（微应用方式）- 数据概览
                  服务中心（微应用方式）- 设置
数据安全 - 数据保护（微应用方式）- xxx
                   数据检测（微应用方式）- xxxx

开发是业务安全是一个项目
        数据中心- 数据概览
        服务中心- 设置
打包采用多页打包，数据中心、服务中心

数据安全亦然。

不知道我的这个能不能表述的清楚。如果框架能支持这种方式的话，我们就不需要再找其他方法去解决。

主要是怕自己对这块不是很清楚，所以提前问问，少走一些弯路。

**Comment by maoxiaoke** [comment]
```jsx
[{
  activePath: ['A'],
  entry: '应用 A'
}, {
  activePath: ['B/c'],
  entry: '应用 c'
}, {
  activePath: ['B/d'],
  entry: '应用 d'
}]
```

对应的应用 A 的 basename: A/
应用 c 的 basename: B/c/
应用 d 的 basename: B/d/

这样， 主应用的 A/a/xxx 访问子应用 A 的 a/xxx 路由
这样， 主应用的 A/b/xxx 访问子应用 A 的 b/xxx 路由

这样，对应的 A 应用的 base

**Comment by Sanmws** [comment]
activityPath和basename同时设置吗？

**Comment by Sanmws** [comment]
activityPath和basename同时设置吗？

**Comment by maoxiaoke** [comment]
@Sanmws 可以通过 getBasename 获取当前加载应用的 basename

**Comment by Sanmws** [comment]
这个我知道的，我再试试，感谢耐心解答！！
