### ISSUE TITLE
Examples of ice-stark with angularjs

### ISSUE THREAD

**Issue by horrylala** [ice-lab/icestark#59]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
Is there any angular examples of ice-stark?

I have a problem with my project.
![image](https://user-images.githubusercontent.com/12706476/71948044-ba4e2780-3209-11ea-9ccd-956181b3a02d.png)

I am seeking some ways to solve this.
Except using  **iframe**, although it can solve my problem.
I just want to know is there any elegant way.

**What is the expected behavior?**

**Comment by daysai** [comment]
angular 因为有重 html 的逻辑，逻辑上需要通过 entry/entryContent 配置。

**Comment by ClarkXia** [comment]
example for angularjs with icestark @horrylala 

```jsx
<AppRouter>
  <AppRoute
    hashType
    path="/contact"
    title="angular"
    entry="https://lidahuisoftware.github.io/pcReact/angular/index.html"
  />
</AppRouter>
```
