### ISSUE TITLE
主应用访问带参数地址丢失参数

### ISSUE THREAD

**Issue by ythlibo** [ice-lab/icestark#598]
访问http://localhost:3000/about?libo=1111时，？后面的参数全部丢失，请各位大佬帮忙看一下。
访问前截图：
<img width="703" alt="image" src="https://user-images.githubusercontent.com/7719044/173271150-a430f051-fca3-4b4c-93a6-a85ba37645aa.png">
访问后截图：
<img width="761" alt="image" src="https://user-images.githubusercontent.com/7719044/173271173-00c08929-43f3-4408-a64d-c25a4bf03e01.png">

**Comment by ClarkXia** [comment]
duplicate with https://github.com/alibaba/ice/issues/5353
