### ISSUE TITLE
icestark ts代码中的 interface 都没有以 I 开头

### ISSUE THREAD

**Issue by tao1991123** [ice-lab/icestark#61]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
按照ts的推荐规范 所有的interface 应该以 大写的 I + 驼峰命名 进行

![](https://img.alicdn.com/tfs/TB1wrE6tAT2gK0jSZFkXXcIQFXa-721-100.png)

期望按照这个来

**Comment by alvinhui** [comment]
ts 推荐的规范是指？

据我观察，TypeScript 的官网上 interfaces 章节的示例也没有用 I 字母开头：http://www.typescriptlang.org/docs/handbook/interfaces.html
