### ISSUE TITLE
error occurs when execute script in sandbox: Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by hashwing** [ice-lab/icestark#615]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

切换两个子应用出现错误`error occurs when execute script in sandbox: Error: only one instance of babel-polyfill is allowed`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

需要怎么避免

**Comment by ClarkXia** [comment]
这个错误是 babel-polyfill 抛出的，需要确保 babel-polyfill 的代码只执行一次，即可以将 babel-polyfill 仅在主应用中执行

**Comment by hashwing** [comment]
确实两个子应用都执行 babel-polyfill ，但这个被包含在第三组件无法修改，通过更换组件解决了
