### ISSUE TITLE
umi微应用：icestark 无法正确获取到生命周期函数

### ISSUE THREAD

**Issue by yizhifeimao** [ice-lab/icestark#623]
umi项目是下载的示例 Repo：icestark-umi-child
主应用入口代码：{
        path: '/seller',
        title: '商家平台',
        loadScriptMode: 'import',
        entry: 'http://localhost:8001',
      }, 
http://localhost:8001是umi子应用链接。
报错：Cannot read properties of null (reading 'mount')
打包成UMD 应用
打包的代码拷贝至 Console 面板执行报错：Target container is not a DOM element.
请问有主应用接入umi子应用链接的示例吗

**Comment by ClarkXia** [comment]
https://micro-frontends.ice.work/docs/guide/use-child/others/#umi-%E5%BA%94%E7%94%A8 可以参考下这个 demo
