### ISSUE TITLE
高频子应用支持不卸载

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icestark#63]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

- 进入 A 应用
- 切换到 B 应用
- 再切换到 A 应用，此时加载 A 应用资源后需要再次执行，在低性能的设备上 js 解析执行时间可能会比较久

![image](https://user-images.githubusercontent.com/2505411/73814096-0bf3cd00-481d-11ea-9465-634b9d4ace0a.png)

**What is the expected behavior?**

- 进入 A 应用
- 切换到 B 应用
- 再切换到 A 应用，此时 A 应用资源无需再次加载 -> 解析 -> 执行

**方案?**

- 子应用上加对应标识，加上标识后从该子应用被切换时，只执行 `registerAppLeave`，不卸载资源
- 再次切换回来的时候，只需要从缓存里找到子应用信息并执行对应的 `registerAppEnter` 即可

因为加了标识的子应用资源不会被卸载，所以可能存在的问题：

1. 内存占用
2. 与其他子应用样式冲突

改造的成本：

目前子应用的运行时信息没有放在队列里，因此实际只会缓存当前子应用的信息，这块需要统一放到队列里，这样才不会被 replace 丢失。

**Comment by ClarkXia** [comment]
## 实现方案

### 子应用缓存策略

高频子应用由具体框架应用中的逻辑决定，比如认为 A、B 子应用会是常用子应用，需主动开启缓存这两个子应用资源。

`AppRoute` 组件支持 `cache` 属性，默认为 false

### 子应用标识

以子应用的 path 属性作为缓存标识，缓存信息包括：registerAppEnter 、registerAppLeave 和 url/entry/entryContent

### 缓存更新策略

- cache 属性由 true -> false，子应用卸载时删除对应缓存
- 子应用切换回来匹配缓存标识，但 url/entry/entryContent 等信息发生变化，更新对应缓存信息

**Comment by ClarkXia** [comment]
已支持 AppRoute 的 cache 参数
```js
<AppRoute cache />
```

开启 cache 后，对子应用节点需实时获取：
```js
if (isInIcestark()) {
  registerAppEnter(() => {
    ReactDOM.render(router(), getMountNode());
  });
  // make sure the unmount event is triggered
  registerAppLeave(() => {
    ReactDOM.unmountComponentAtNode(getMountNode());
  });
} else {
  ReactDOM.render(router(), document.getElementById('ice-container'));
}
```
