### ISSUE TITLE
[QUESTION]有什么办法解决应用间CDN冲突？

### ISSUE THREAD

**Issue by xmsz** [ice-lab/icestark#638]
背景
- 我有3个应用，都用CDN引入了react
- 然后运行的时候，第一次正常，但是刷新页面，或者第二次进来就提示
```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

因为windows/global里的react重复加载了

请问这种情况怎么解决？

如果只有父应用引入CDN，那子应用单独就跑不了

**Comment by maoxiaoke** [comment]
react 打包进子应用中，或者使用主应用公用的 react

**Comment by xmsz** [comment]
> react 打包进子应用中，或者使用主应用公用的 react

我现在子应用index.html就先没有引入react了。


我还有一个想法，其实index.html没什么问题，主要是我主应用是通过[entry](https://micro-frontends.ice.work/docs/api/ice-stark/#entry)方式引入，所以会重复加载react。

有没有可能有一个entryFilter，流程就是父应用通过entry请求到了
1.js
react.js
两个地址
然后我可以通过entryFilter过滤掉react，这样就不会重复加载，而子应用直接也能独立跑

**Comment by xmsz** [comment]
> react 打包进子应用中，或者使用主应用公用的 react

我现在子应用index.html就先没有引入react了。


我还有一个想法，其实index.html没什么问题，主要是我主应用是通过[entry](https://micro-frontends.ice.work/docs/api/ice-stark/#entry)方式引入，所以会重复加载react。

有没有可能有一个entryFilter，流程就是父应用通过entry请求到了
1.js
react.js
两个地址
然后我可以通过entryFilter过滤掉react，这样就不会重复加载，而子应用直接也能独立跑

**Comment by xmsz** [comment]
> react 打包进子应用中，或者使用主应用公用的 react

我现在子应用index.html就先没有引入react了。


我还有一个想法，其实index.html没什么问题，主要是我主应用是通过[entry](https://micro-frontends.ice.work/docs/api/ice-stark/#entry)方式引入，所以会重复加载react。

有没有可能有一个entryFilter，流程就是父应用通过entry请求到了
1.js
react.js
两个地址
然后我可以通过entryFilter过滤掉react，这样就不会重复加载，而子应用直接也能独立跑

**Comment by maoxiaoke** [comment]
https://github.com/ice-lab/icestark/issues/331 跟这个诉求有点像

**Comment by xmsz** [comment]
> #331 跟这个诉求有点像

没错 一样的需求
