### ISSUE TITLE
快速频繁切换AppRoute重绘导致appLifeCycle报错而崩溃

### ISSUE THREAD

**Issue by jixiangac** [ice-lab/icestark#64]
**Do you want to request a *feature* or report a *bug*?**
![image](https://user-images.githubusercontent.com/1684563/74002157-222e9400-49a9-11ea-9aaa-9bc8d6e322ef.png)

**What is the current behavior?**
快速切换导航，导致崩溃
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
快速切换导航，具体栗子见内网aone
**What is the expected behavior?**
不报错
![image](https://user-images.githubusercontent.com/1684563/74002218-65890280-49a9-11ea-9657-fa2eb580ddd5.png)
代码上可以在这里加try catch可以防止这个问题，具体优化可以再看

**Comment by ClarkXia** [comment]
### 问题定位
子应用快速切换，会导致大量资源加载任务堆积，而在子应用卸载的时候，会将子应用渲染节点的 root 信息删除，子应用在 `AppRoute` 卸载的情况下，堆积的js 加载完成后执行相应脚本，会导致错误判断在非容器环境下渲染，最终导致报错
问题常见于子应用信息异步获取，获取过程中 `AppRoute` 不进行渲染

```js
// isInIcestark() 在 AppRoute 组件卸载掉的情况下返回 false
if (isInIcestark()) {
  const mountNode = getMountNode();

  registerAppEnter(() => {
    ReactDOM.render(router(), mountNode);
  });
  registerAppLeave(() => {
    ReactDOM.unmountComponentAtNode(mountNode);
  });
} else {
  // 容器应用下 不存在 #ice-container 节点，直接 render 会报错
  ReactDOM.render(router(), document.getElementById('ice-container'));
}
```

**Comment by ClarkXia** [comment]
1.4.0 版本目前在 AppRouter 存续期间 isInIcestark 始终判断为 true，应该不会再出现渲染到非容器环境节点的错误
