### ISSUE TITLE
不维护了吗？

### ISSUE THREAD

**Issue by CX330-jiuxi** [ice-lab/icestark#644]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by wisdomofgod** [comment]
邮件已收到~~

**Comment by wssgcg1213** [comment]
没有发布过中止维护的相关信息
