### ISSUE TITLE
[enhancement] 增加 basename 配置，支持二级(子)目录

### ISSUE THREAD

**Issue by fanybook** [ice-lab/icestark#66]
需求：我现在在改造老的后台应用，因为老的没精力全部重构，所以打算把老的全部套进 iframe，icestark 为了和老的使用相同的 session 所以不单起域名了，需要把 icestark 先放入二级(子)目录先和老的共存

我的解决：我做了一个 config 配置，然后通过对 icestark-layout(父应用) 进行修改实现的这个需求

这个需求我也去群里提问了，群里大佬让我提个 issue，说官方会支持的，希望支持了以后@我一下，让我能知道进展

另一个建议：icestark-layout(父应用) 在 build 时，生成的 index.html 最好用绝对路径加载 js 和 css，这样我做 history 后端支持的时候，可以直接读这个 html，否则还要粘出来，手改成绝对路径

**Comment by ClarkXia** [comment]
需求：框架应用需要支持统一 basename 的设置

构建时 js 和 css 的绝对路径可以通过工程配置上配置 publicPath 解决

**Comment by fanybook** [comment]
@ClarkXia 好的 publicPath 我试试
