### ISSUE TITLE
微模块如何支持沙箱

### ISSUE THREAD

**Issue by ultranana** [ice-lab/icestark#668]
业务上试用了一下微模块@ice/stark-module，但是发现没有对js做沙箱隔离。我也没有找到启用沙箱的对应api，能否提供下

**Comment by ClarkXia** [comment]
https://github.com/ice-lab/icestark/blob/ec2d44244a2b4ebd7af0e0ff0a10f528b33b8a64/packages/icestark-module/src/MicroModule.tsx#L83

组件传入 `sandbox` 就行，文档后续补充下这块的说明

**Comment by ultranana** [comment]
沙箱不生效怎么办

第一个模块组件：
`import * as React from 'react';

type ComponentProps = {
  title: string,
};

第二个模块组件：

export default function Ask(props: ComponentProps) {
  const { type, ...others } = props;
  window.a = 1
console.log("ask", a)
  
  return (
    <div className="Ask" {...others}>Hello Ask</div>
  );
}
`



`import * as React from 'react';

type ComponentProps = {
  title: string,
};

export default function Examle(props: ComponentProps) {
  const { type, ...others } = props;
  console.log(window.a)
  return (
    <div className="Examle" {...others}>Hello Examle</div>
  );
}
`
![image](https://user-images.githubusercontent.com/24351515/224960707-cd594256-5582-40f6-b2e7-9dd410327c71.png)
部分情况下是这样的，加上sanbox了，感觉和js加载顺序有关系
