### ISSUE TITLE
主应用，在本地开发环境下，可以设置多个代理地址？

### ISSUE THREAD

**Issue by pangxianfei** [ice-lab/icestark#672]
![图片](https://user-images.githubusercontent.com/9346931/230524296-385310ba-f145-4ff4-ab7f-af0499dd08b0.png)
配置两个代理，后面的没有生效。

**Comment by ClarkXia** [comment]
这个 proxy 就是 webpack-dev-server 的 proxy，如果有问题 可以到 https://github.com/alibaba/ice 提 issue
