### ISSUE TITLE
unable to retrieve lifecycles of webDataSupervision after loading it.

### ISSUE THREAD

**Issue by SimonChen233** [ice-lab/icestark#681]
![image](https://user-images.githubusercontent.com/27402920/236427083-28c97bdb-4526-49bf-a5f2-a7122a6947f3.png)
现有vue项目作为微前端接入，主应用找不到其生命周期
![image](https://user-images.githubusercontent.com/27402920/236427390-6ace9d32-a384-41ad-8b8c-014369786bac.png)
现有vue项目接入的方法如上

**Comment by ClarkXia** [comment]
在 #683 中跟进
