### ISSUE TITLE
使用模版创建主子应用，将本地子应用接入本地主应用，子应用/页面可正常显示，/list报unkLoadError: Loading chunk p_list-index failed.

### ISSUE THREAD

**Issue by wwb1021925026** [ice-lab/icestark#684]
所有代码都为模版默认代码 只在主应用getApps中添加了    
{
      path: '/child',
      title: 'child',
      sandbox: true,
      entry: '//localhost:3001',
 },
/child对应的子应用/页面可正常显示
/child/list 对应子应用的 /list页面 报 Loading chunk p_list-index failed.

**Comment by ClarkXia** [comment]
参考 https://micro-frontends.ice.work/docs/faq#%E5%BA%94%E7%94%A8%E5%90%AF%E7%94%A8-lazy-%E5%90%8Echunk-%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5

**Comment by evle** [comment]
@ClarkXia 我也遇到了同样的问题，子应用打包后是多个HTML页面: index.html, list.html, detail.html，在主应用中通过下面方式注册子应用

```
   {
      path: "/seller",
      title: "商家平台",
      sandbox: true,
      entry: "https://f2e.blob.core.windows.net/fuhao/index.html",
      loadScriptMode:'fetch'
    },
```
路由是这样的

```
  children: [
      {
        path: '/seller/',
        name: '首页',
      },
      {
        path: '/seller/list',
        name: '列表',
      },
      {
        path: '/seller/detail',
        name: '详情',
      },
      {
        path: '/seller/404',
        name: '404',
      },
    ],
```

但是无法加载 list.html 和 detail.html
