### ISSUE TITLE
[bug] Nav 的 triggerType 写 click 无法弹出下拉

### ISSUE THREAD

**Issue by fanybook** [ice-lab/icestark#69]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Nav 的 triggerType 写 click 无法弹出下拉（官网例子写的是 hover，在我这是能弹出下拉的，改成 click 后不行了，删掉 triggerType 同样，点击后无法弹出下拉）

使用
"@alifd/next": "^1.x",
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
```javascript
      <Nav className="basic-nav" direction="hoz" type="normal" header={header} footer={footer} defaultSelectedKeys={['home']} triggerType="click">
        <Item key="home">Home</Item>
        <SubNav label="Component" selectable>
          <Item key="next">Next</Item>
          <Item key="mext">Mext</Item>
        </SubNav>
        <Item key="document">Document</Item>
      </Nav>
```
**What is the expected behavior?**
当然是能正常弹出下拉

**Comment by ClarkXia** [comment]
fusion 组件问题可以在 https://github.com/alibaba-fusion/next 进行反馈
