### ISSUE TITLE
主子应用同一域名，刷新的问题

### ISSUE THREAD

**Issue by zhtx8090** [ice-lab/icestark#692]
问题描述：主子应用单独部署在nginx，刷新后跳转到了子应用document，不再显示主应用的菜单，且无法返回主应用。

一、项目配置：
主应用：
https://examleSite/main
> 子应用path: '/subApp'
> 路由:  /login

子应用：
https://exampleSite/subApp/
> basename: /subApp
>  路由:  /a    /b

二、部署说明：
1. 主子应用都在同一台机器；
2. 主子应用有各自的nginx容器；

三、现象说明：
1. 从主应用登录 `https://examleSite/main/login` 后进入 `https://examleSite/subApp/a` 页面；
2. 主应用内可以进行菜单的跳转，如从 `/a` 跳转 `/b`, 浏览器地址栏表现为 `https://examleSite/subApp/a` => `https://examleSite/subApp/b`；
3. 如若刷新当前页面 `/b` ，页面跳转到子应用document，浏览器地址栏仍为`https://examleSite/subApp/b`；

四、猜测： 不同于IP地址通过端口(如主8000，子8001，浏览器地址栏表现为 `127.0.0.1:8000/subApp/b` )可以识别主子应用，如果主子应用同一个域名，刷新后主应用document丢失，浏览器自动跳转到子应用。

**Comment by ClarkXia** [comment]
刷新后主应用 document 的问题可以看下 nginx 配置，在域名下的所有路径都应该渲染主应用的内容，由前端路由判断加载子应用

**Comment by zhtx8090** [comment]
我这边采用主子应用通过相对路径的部署方案解决问题了
