### ISSUE TITLE
htmlPlugin is not a function

### ISSUE THREAD

**Issue by homestylew** [ice-lab/icestark#702]
"vite-plugin-index-html": "^2.0.2"

import htmlPlugin from "vite-plugin-index-html";
plugins: [
  react(),
  htmlPlugin({
    input: "src/main.tsx",
    preserveEntrySignatures: "exports-only",
  }),
],
报错htmlPlugin is not a function

**Comment by wisdomofgod** [comment]
邮件已收到~~

**Comment by ClarkXia** [comment]
未能复现这个问题，另外 vite-plugin-index-html 的源码上默认导出就是函数，你可以打印下 htmlPlugin 看是不是存在 default 属性

**Comment by homestylew** [comment]
我能私底下联系下你吗，我这边项目运行不起来

**Comment by homestylew** [comment]
> 未能复现这个问题，另外 vite-plugin-index-html 的源码上默认导出就是函数，你可以打印下 htmlPlugin 看是不是存在 default 属性

import { defineConfig, loadEnv } from "vite";
import react from "@vitejs/plugin-react-swc";
import tailwindcss from "tailwindcss";
import autoprefixer from "autoprefixer";
import { handleEnv } from "./build/utils/helper";
import path from "path";
import htmlPlugin from "vite-plugin-index-html";

// https://vitejs.dev/config/
// command,mode 在开发环境下command的值为serve，而在生产环境下为 build。
export default defineConfig(({ mode }) => {
  const root = process.cwd();
  const env = loadEnv(mode, root, "");
  const viteEnv = handleEnv(env);
  const { VITE_SERVER_PORT } = viteEnv;
  return {
    resolve: {
      alias: {
        "@": path.resolve(__dirname, "src"),
        z: path.resolve(__dirname),
      },
    },
    plugins: [
      react(),
      htmlPlugin({
        input: "src/main.tsx",
        preserveEntrySignatures: "exports-only",
      }),
    ],
    css: {
      postcss: {
        plugins: [tailwindcss, autoprefixer],
      },
    },
    server: {
      open: true,
      port: VITE_SERVER_PORT,
      // 跨域处理
      proxy: {
        "/api": {
          target: "http://127.0.0.1:3000",
          changeOrigin: true,
          // rewrite: (path) => path.replace(/^\/api/, ""),
        },
      },
    },
    base: "./",
    build: {
      outDir: "dist",
      minify: "esbuild",
      rollupOptions: {
        preserveEntrySignatures: "exports-only",
        output: {
          chunkFileNames: "assets/js/[name]-[hash].js",
          entryFileNames: "assets/js/[name]-[hash].js",
          assetFileNames: "assets/[ext]/[name]-[hash].[ext]",
        },
      },
    },
  };
});

**Comment by homestylew** [comment]
> 未能复现这个问题，另外 vite-plugin-index-html 的源码上默认导出就是函数，你可以打印下 htmlPlugin 看是不是存在 default 属性

import htmlPlugin from "vite-plugin-index-html";
console.log(htmlPlugin);
console.log(htmlPlugin?.default);
打印出来怎么是这样呢
{
  removeHtmlEntryScript: [Function: removeHtmlEntryScript],
  default: [Function: htmlPlugin]
}
[Function: htmlPlugin]

**Comment by ClarkXia** [comment]
跟你配置文件执行规范有关，跟插件本身没关系
