### ISSUE TITLE
加载子应用报错

### ISSUE THREAD

**Issue by homestylew** [ice-lab/icestark#705]
vite构建之后，主应用加载子应用报错
main.tsx:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

apps.js:287 Error: icestark minified message #5: The script resources loaded error: http://127.0.0.1:3000/src/main.tsx. See https://micro-frontends.ice.work/error?code=5&arg=http://127.0.0.1:3000/src/main.tsx
    at HTMLScriptElement.<anonymous> (handleAssets.js:230:20)

**Comment by ClarkXia** [comment]
确认下 vite 服务启动后返回的头信息，理论上更应该返回 js 类型，看报错是返回了 html 类型
