### ISSUE TITLE
使用官方提供的子应用脚手架，生成子应用加载失败

### ISSUE THREAD

**Issue by M-ike** [ice-lab/icestark#709]
使用官方提供的脚手架生成的主应用和子应用，加载子应用失败。
<img width="545" alt="image" src="https://github.com/ice-lab/icestark/assets/5945562/16a7cba4-6fbd-42a0-8772-7c259a928591">

复现地址，主应用： https://dev.g.alicdn.com/tunion/tunion/0.0.1/index.html, 点击 “微应用1”。 子应用资源https://dev.g.alicdn.com/tunion/busywork/0.0.1/index.html

使用npm init ice icestark-child @icedesign/stark-child-scaffold， 是ice2版本的，这个没有问题。

用最新的 npm init ice icestark-child @icedesign/stark-child生成的ice3的工程，就出现刚才的问题了。

**Comment by ClarkXia** [comment]
路径匹配原因，内部对焦

**Comment by DavidWuJay** [comment]
这个问题是如何解决的？
