### ISSUE TITLE
主应用拉不到子应用的静态资源

### ISSUE THREAD

**Issue by Gallado** [ice-lab/icestark#721]
主应用端口3000 ，子应用端口3007（使用vue3+vite）
单独子应用启动，没问题
![image](https://github.com/ice-lab/icestark/assets/34369109/6a17bb96-d5b2-4bc1-89f2-182ba1af6926)
 集成进主应用后 获取不到资源。主应用是3000. 没有去3007子应用上拉资源
![image](https://github.com/ice-lab/icestark/assets/34369109/aa0fd513-2f74-4cb8-a58b-607b167ce44e)
有什么配置可以拉取子应用的镜头资源吗

**Comment by ClarkXia** [comment]
https://micro-frontends.ice.work/docs/faq/#%E5%BE%AE%E5%BA%94%E7%94%A8-bundle-%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5 参考设置 publicPath
