### ISSUE TITLE
根据官方demo操作，无法挂载ice子应用

### ISSUE THREAD

**Issue by DavidWuJay** [ice-lab/icestark#722]
主应用代码
![image](https://github.com/ice-lab/icestark/assets/24268244/039b7f38-5a55-4f1a-b0de-44ba78063a19)
子应用代码
<img width="614" alt="image" src="https://github.com/ice-lab/icestark/assets/24268244/6d938e7f-9ff1-45e2-80ef-0969f82de380">
最后呈现的结果
<img width="1283" alt="image" src="https://github.com/ice-lab/icestark/assets/24268244/3539b297-4a0b-4745-b475-9b57fbd5314b">
请问这个如何解决

**Comment by ClarkXia** [comment]
关注下关于 loadScriptsMode 的注释，修改成 fetch
