### ISSUE TITLE
<img width="1740" alt="image" src="https://github.com/ice-lab/icestark/assets/24268244/1d1e269b-a3e0-4246-bad9-0b0ed44a555d">

### ISSUE THREAD

**Issue by DavidWuJay** [ice-lab/icestark#723]
![image](https://github.com/ice-lab/icestark/assets/24268244/73d9da7f-288f-4ac6-96e9-4240f5e2a614)

配置后已经可以访问但是报错了

_Originally posted by @DavidWuJay in https://github.com/ice-lab/icestark/issues/722#issuecomment-1972343194_

**Comment by ClarkXia** [comment]
确认下 chunk 加载地址是不是有问题 https://micro-frontends.ice.work/docs/faq#%E5%BA%94%E7%94%A8%E5%90%AF%E7%94%A8-lazy-%E5%90%8Echunk-%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5
