### ISSUE TITLE
是否支持ie？能否与umijs集成？

### ISSUE THREAD

**Issue by wittech** [ice-lab/icestark#73]
是否支持ie？能否与umijs集成？

**Comment by chenbin92** [comment]
@wittech  已支持与 icejs 集成，详见：

* 仓库：https://github.com/ice-lab/icejs
* 文档：https://ice.work/docs/guide/advance/icestark

**Comment by imsobear** [comment]
IE 支持度跟 React 一致；支持 umi 的子应用，如果遇到具体问题了可以在答疑群里反馈。
