### ISSUE TITLE
使用脚手架创建主应用和子应用，主应用无法正常加载子应用

### ISSUE THREAD

**Issue by H5DevHoward** [ice-lab/icestark#733]
报错：Cannot read properties of null (reading 'mount')

![image](https://github.com/ice-lab/icestark/assets/17853595/dcab85e6-9ba5-4b5c-8632-01aa6b074a9a)

主应用配置：
![image](https://github.com/ice-lab/icestark/assets/17853595/fc414fd9-df36-4655-bcad-b23837a7a0d2)
![image](https://github.com/ice-lab/icestark/assets/17853595/76e788f3-1ed7-424f-ab2b-6c467df3f8e8)
![image](https://github.com/ice-lab/icestark/assets/17853595/eeb87306-5566-4808-9c80-47e622a8d427)

子应用配置：
![image](https://github.com/ice-lab/icestark/assets/17853595/9c645899-3b45-4bed-ac8e-e238c74a5e13)
![image](https://github.com/ice-lab/icestark/assets/17853595/d8f6ac1d-4eae-4281-bf3b-e96c067a577b)
![image](https://github.com/ice-lab/icestark/assets/17853595/2bd40e95-0977-4991-b2c5-46736ce265ca)

**Comment by ClarkXia** [comment]
https://micro-frontends.ice.work/docs/api/ice-stark/#loadscriptmode- 注意下 loadScriptMode 的配置
