### ISSUE TITLE
文档案例存在 bug 哦

### ISSUE THREAD

**Issue by lxzy-yun** [ice-lab/icestark#734]
<img width="649" alt="image" src="https://github.com/ice-lab/icestark/assets/26783322/374719b4-bccd-4b6f-acd2-08fbddd82012">

useEffect的 return 方法内renderNode.current肯定是 null 了，导致微模块不会被正确卸载
解决方式：
在 useEffect return 之前先用变量暂存下renderNode.current，再统一使用此变量
```
useEffect(() => {
    const dom=renderNode.current
    mountModule(moduleInfo, dom, {});
    return () => {
      unmoutModule(moduleInfo, dom);
    }
  }, []);
```

**Comment by ClarkXia** [comment]
欢迎直接 PR 修复，文档在 website 目录

**Comment by lxzy-yun** [comment]
已提 pr
