### ISSUE TITLE
[enhancement] 怎么在 icestark-layout 里做登录页面

### ISSUE THREAD

**Issue by fanybook** [ice-lab/icestark#74]
需求：怎么在 icestark-layout 里做登录页面，改怎么路由
> 这个需求很常见吧，能否提供一个这种路由的例子

现在情况：都被 AppRouter 路由了
> 是否应该拿 react-router 再套一层，然后把 path: '*' 交给 AppRouter

**Comment by imsobear** [comment]
`npm init ice icestark-layout @icedesign/stark-layout-scaffold`

这个模板里就有，参考一下，红框两个页面就是做到框架里的：

![image](https://user-images.githubusercontent.com/2505411/75413268-0b53df80-5960-11ea-86a9-d226d58aa091.png)

**Comment by fanybook** [comment]
@imsobear 感谢，但这两个还是在 右侧的 main-contents 区域

是要去 BasicLayout 根据 pathname 返回不同的 Shell 结构，还是有什么更好的办法
