### ISSUE TITLE
[bug?] NotFoundComponent 组件没有如预期显示

### ISSUE THREAD

**Issue by fanybook** [ice-lab/icestark#75]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
环境：
  "name": "@icedesign/stark-layout-scaffold",
  "version": "3.0.7",

我刚安装了新版，然后再url输入一个没有的地址，一直显示主页，我去 routes.ts 加了 exact
```js
const routes = [{
  path: '/about',
  component: About,
},{
  path: '/login',
  component: About,
}, {
  path: '/',
  exact: true,
  component: Home,
}];
```
产生了一些变化，不再显示主页，main-contents 区域变成了白页，而不是预期的404 NotFoundComponent 组件里的内容
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
如上
**What is the expected behavior?**
正常显示 NotFoundComponent 组件

**Comment by ClarkXia** [comment]
@icedesign/stark-layout-scaffold 中 routes 的配置是主应用的 react-router 配置，在 AppRouter 中默认设置了子应用不支持的路由，类似
```js
<AppRoute
  path="/"
  component={<Router routes={routes} type="browser" />}
/>
```
所以如果希望显示 404 需要在路由配置上增加一项 404 页面兜底，比如：

```js
const routes = [
...
  {
    path: '*',
    exact: true,
    component: NotFoundComponent
  }
]
```

**Comment by imsobear** [comment]
@ClarkXia 模板需要改一下
