### ISSUE TITLE
icestark 支持资源预加载机制？

### ISSUE THREAD

**Issue by woaizimmy** [ice-lab/icestark#76]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**Comment by imsobear** [comment]
@woaizimmy 目前没有，这个可以结合业务诉求来完善。

**Comment by imsobear** [comment]
@ClarkXia 可以评估下

**Comment by maoxiaoke** [comment]
same as #188
