### ISSUE TITLE
新的基于icejs的主框架 + 旧的飞冰项目改造而成的子应用，联合开发的问题

### ISSUE THREAD

**Issue by woaizimmy** [ice-lab/icestark#78]
（注：以下的图都需要点开看，不支持直接上图，只好添加link了）
新的基于icejs的主框架 + 旧的飞冰项目改造而成的子应用，联合开发的问题，报错信息如下：
[报错信息图](https://img-blog.csdnimg.cn/20200309172619260.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzE3ODUwNDQ5,size_16,color_FFFFFF,t_70)
主框架注册子应用的代码，如下如：
[注册代码图](https://img-blog.csdnimg.cn/20200309172633995.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzE3ODUwNDQ5,size_16,color_FFFFFF,t_70)
旧的飞冰项目参照官方文档进行了子应用改造，如下两图：
[1. 应用入口适配](https://img-blog.csdnimg.cn/20200309172649204.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzE3ODUwNDQ5,size_16,color_FFFFFF,t_70)
[2. 定义基准路由](https://img-blog.csdnimg.cn/2020030917265947.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzE3ODUwNDQ5,size_16,color_FFFFFF,t_70)
以上，按照文档说的方式来改造了，不知道改造代码是否有错？求解如何解决这个问题

**Comment by ClarkXia** [comment]
dev 调试的时候可以在 build.json 中添加 devPublicPath 来指定资源加载链接 https://ice.work/docs/guide/basic/build#devPublicPath

**Comment by woaizimmy** [comment]
> dev 调试的时候可以在 build.json 中添加 devPublicPath 来指定资源加载链接 https://ice.work/docs/guide/basic/build#devPublicPath

填的是子应用的端口么？填了 http://localhost:3333 和没设置时一样，填了 http://localhost:4444 （子应用的），报错信息变成了：Target container is not a DOM element，如下图：
[报错图](https://img-blog.csdnimg.cn/2020030918044047.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzE3ODUwNDQ5,size_16,color_FFFFFF,t_70)

**Comment by ClarkXia** [comment]
devPublicPath 保证子应用资源成功加载，最好可以提供下子应用的复现 demo

**Comment by woaizimmy** [comment]
> devPublicPath 保证子应用资源成功加载，最好可以提供下子应用的复现 demo

你好，复现demo地址：https://github.com/woaizimmy/iceDemo

**Comment by ClarkXia** [comment]
项目我试了下有两点：
1. ice.config.js 中调试过程中需要增加 devPublicPath: 'http://localhost:4444/'
2. index.jsx 中 registerAppEnter 中和默认 ReactDOM.render 内容有差异会导致报错（主要是 LanguageProvider ）
基于两点改着完后，应该可以作为子应用正常运行

**Comment by woaizimmy** [comment]
> 项目我试了下有两点：
> 
> 1. ice.config.js 中调试过程中需要增加 devPublicPath: 'http://localhost:4444/'
> 2. index.jsx 中 registerAppEnter 中和默认 ReactDOM.render 内容有差异会导致报错（主要是 LanguageProvider ）
>    基于两点改着完后，应该可以作为子应用正常运行

感谢！回头我试试

**Comment by woaizimmy** [comment]
> 项目我试了下有两点：
> 
> 1. ice.config.js 中调试过程中需要增加 devPublicPath: 'http://localhost:4444/'
> 2. index.jsx 中 registerAppEnter 中和默认 ReactDOM.render 内容有差异会导致报错（主要是 LanguageProvider ）
>    基于两点改着完后，应该可以作为子应用正常运行

试了还是不行，我在想，会不会构建后有多个css和js 的原因？！
不知道有没有什么方法能让项目构建后只有一个css和一个js？我试了很久没找到方法
