### ISSUE TITLE
结合 icejs 使用支持动态修改子应用列表

### ISSUE THREAD

**Issue by jallens** [ice-lab/icestark#80]
用icestark-layout模板进行开发。
但是我们有这么一个需求，是根据用户登录后，从后端获取该用户下的（子）应用服务。 
所以工程的第1个入口可能是先登录，登录完了之后再注册子应用。

模板中代码大致如下：
```
// src/app.tsx
....

const appConfig = {
  ...
  icestark: {
    ...
  }
};

createApp(appConfig);
```

问题来了，在用户正常登录后，获取到子应数据，我如何重新刷新`appConfig`？
有没有类似`updateApp(newAppConfig);`的操作api？

我尝试过重新执行`createApp(newAppConfig);`，但是会有React的警告。如图：
![image](https://user-images.githubusercontent.com/3937706/76238996-bb342180-626b-11ea-90a3-1846a61a18e8.png)

最后贴上`src/app.tsx`的完整代码：

```
import * as React from 'react';
import { createApp } from 'ice'
import { ConfigProvider } from '@alifd/next';
import PageLoading from '@/components/PageLoading';
import BasicLayout from '@/layouts/BasicLayout';

const appConfig = {
  app: {
    rootId: 'icestark-container',
    addProvider: ({ children }) => (
      <ConfigProvider prefix="next-icestark-">{children}</ConfigProvider>
    ),
  },
  router: {
    type: 'browser',
  }
};

setTimeout(() => {
  const appConfig2 = {
    app: {
      rootId: 'icestark-container',
      addProvider: ({ children }) => (
        <ConfigProvider prefix="next-icestark-">{children}</ConfigProvider>
      ),
    },
    router: {
      type: 'browser',
    },
    icestark: {
      type: 'framework',
      Layout: BasicLayout,
      getApps: async () => {
        const apps = [{
          path: '/seller',
          title: '商家平台',
          // React app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-seller-react-16
          url: [
            '//ice.alicdn.com/icestark/child-seller-react/index.js',
            '//ice.alicdn.com/icestark/child-seller-react/index.css',
          ],
        }, {
          path: '/waiter',
          title: '小二平台',
          url: [
            // Vue app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-waiter-vue-2
            '//ice.alicdn.com/icestark/child-waiter-vue/app.js',
            '//ice.alicdn.com/icestark/child-waiter-vue/app.css'
          ],
        }, {
          path: '/angular',
          title: 'Angular',
          // Angular app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-common-angular-9 
          entry: '//ice.alicdn.com/icestark/child-common-angular/index.html',
        }];
        return apps;
      },
      appRouter: {
        LoadingComponent: PageLoading,
      },
    },
  };
  console.log('before appConfig2');
  createApp(appConfig2);
  console.log('after appConfig2');
}, 4000);

createApp(appConfig);

```

**Comment by jallens** [comment]
@imsobear 帮忙看看，谢谢。

**Comment by ClarkXia** [comment]
createApp 目前不支持多次调用，登录后再获取子应用信息，可以类似如下操作：

```
const appConfig = {
  ...
  icestark: {
    ...
    getApps: async () => {
      // 1.检查登录权限，如果尚未登录，可以返回 null，并跳转登录页面，登录页面可以在 src/routes.ts 中设置
      // 2.如果已登录，返回对应接口的 apps 信息
   }
  }
};
```
登录完成后重新跳转会首页，页面跳转后重新执行 getApps 中的逻辑，走已登录逻辑获取 apps 信息

**Comment by jallens** [comment]
> createApp 目前不支持多次调用，登录后再获取子应用信息，可以类似如下操作：
> 
> ```js
> const appConfig = {
>   ...
>   icestark: {
>     ...
>     getApps: async () => {
>       // 1.检查登录权限，如果尚未登录，可以返回 null，并跳转登录页面，登录页面可以在 src/routes.ts 中设置
>       // 2.如果已登录，返回对应接口的 apps 信息
>    }
>   }
> };
> ```
> 
> 登录完成后重新跳转会首页，页面跳转后重新执行 getApps 中的逻辑，走已登录逻辑获取 apps 信息


谢谢回复！
看你回复的意思是，getApps上会被icejs多次调用吗？
是这样子吗：

```js
getApps: async () => {
  if (isLogin) {
    return null;
  } else {
    return someApps;
  }
}
```

**Comment by imsobear** [comment]
@jallens 登录逻辑大概是怎样的？描述一下~~

**Comment by jallens** [comment]
> @jallens 登录逻辑大概是怎样的？描述一下~~

在同主应用框架工程上，至少有两个页面（login、portal)，一个登录页(login），一个是登录后的首页（portal)。

应用的第1个页是login（只是仅仅是做一个用户登录），登录后，会进入portal(首页）。
此时portal才是真正微前端的组织页（有顶部栏，左侧菜单栏，中间子应用内容区），但是我portal页的子应用是根据用户的权限决定拉取不同的子应用数据。

所以我主应用框架启动的时候（createApp）我无法知道子应用数据，无法注册子应用。按现ice-stark的模板，子应用只能在createApp的时候注册。

所以在此请教一下如何处理。

**Comment by imsobear** [comment]
登录成功了刷新一下页面是不是就可以了？

**Comment by jallens** [comment]
> 登录成功了刷新一下页面是不是就可以了？

`window.location.reload()` ？这也许是一个实现的思路，目前我也准备这样子尝试。

框架模板层面有没有其它思路，或者后面是否会新增支持类似刷新子应用注册的操作？

**Comment by imsobear** [comment]
1. 登录这个场景我觉得刷新是合理的
2. 动态改变 Apps 这个能力需要 @ClarkXia 评估下，类似提供 `import { updateApps } from 'ice';` 这样的能力

**Comment by jallens** [comment]
谢谢 @imsobear 解答，目前暂时用了`window.location.reload()`实现了，虽然可能不是最佳实践。

同时也期待后面框架上支持动态刷新子应用的配置。 @ClarkXia

**Comment by ClarkXia** [comment]
> 类似提供 import { updateApps } from 'ice'; 这样的能力

子应用 apps 维护在一个组件中，可以在 Layout 层提供 updateApps 的 props 来动态修改子应用列表

**Comment by jallens** [comment]
> > 类似提供 import { updateApps } from 'ice'; 这样的能力
> 
> 子应用 apps 维护在一个组件中，可以在 Layout 上提供 updateApps 的 props 来动态修改子应用列表

你意思是现模板上就可以这样实现吗？ 不是特别明白，可否具体一些？
