### ISSUE TITLE
通过 entry 加载子应用样式丢失

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/icestark#82]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

通过 entry 加载子应用，js 正常执行，css 样式丢失

**What is the expected behavior?**

css 样式正常显示

**Comment by ClarkXia** [comment]
## 问题原因

js 中通过 registerAppEnter 方式注册子应用挂载，而目前 entry 加载后所有的内容都放入子应用的节点上面，一旦执行 registerAppEnter 中的方法，将会将当前 子应用 html 内容覆盖，包括 css 内容

## 解决方案

加载完 entry 后，分析其中的 css 和 js 资源，在非子应用挂载点插件对应资源，同 urls 方式加载保持一致

## 注意事项

entry 方式加载情况下，需要注意是通过 registerAppEnter 注册子应用的话，需要主要除了css 和 js 资源外，其他 html 结构依旧会被覆盖

**Comment by hfuuss** [comment]
mark

**Comment by ClarkXia** [comment]
@ice/stark@1.4.2 版本已修复
