### ISSUE TITLE
iceStark框架 加载 vue子项目时，icon组件库样式冲突

### ISSUE THREAD

**Issue by guananny2** [ice-lab/icestark#83]
![image](https://user-images.githubusercontent.com/22285339/76492159-7d511c00-646a-11ea-8be0-04b28d4f8d94.png)
icestark 框架项目 
vue子项目（element 组件库）
从框架项目访问子项目时，子项目的下拉框中的 箭头图标变成方块，icon渲染冲突

**Comment by imsobear** [comment]
子应用 publicPath 配置问题导致 icon 资源加载失败

**Comment by BestDI** [comment]
@imsobear 冒昧的问一下, vue 子项目的publicPath怎么指定?

**Comment by imsobear** [comment]
@BestDI vue.config.js 里有 publicPath 的配置项

**Comment by BestDI** [comment]
@imsobear 有没有配置的示例？现在配置的就是 publicPath ：’./’
