### ISSUE TITLE
新模板中如何AppRouter监听onRouteChange配置？

### ISSUE THREAD

**Issue by jallens** [ice-lab/icestark#88]
新模板中关于icestark使用文档说明太少了。
现模板是能过createApp(config)来配置注册子应用，关于config.icestark说明太少，只有下面两篇说明
icejs介绍如下：https://ice.work/docs/guide/advance/icestark
icestark介绍如下：https://ice.work/docs/icestark/reference/api

参考了上两外链接说明，如下图：在appRouter中这样配置了，但是并没有起作用。
![image](https://user-images.githubusercontent.com/3937706/76734473-f23f9100-679d-11ea-8ea2-2d1f304625df.png)

请问如何设置监听？还有，什么时候可以完善一下icestark在icejs上的配置说明。

**Comment by ClarkXia** [comment]
这两个配置目前是不支持的，关于 pathname 和 appEnter 等信息的变更，在新的模版中目前可以 layout 中进行处理，可以参考：https://github.com/alibaba-fusion/materials/blob/master/scaffolds/ice-stark-layout/src/layouts/BasicLayout/index.tsx

关于文档的问题近期我们再优化补充下相关内容

**Comment by ClarkXia** [comment]
可以先参考下这篇文档 https://github.com/alibaba/ice/blob/docs/plugin-icestark/docs/guide/advance/icestark.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by jallens** [comment]
> 可以先参考下这篇文档 https://github.com/alibaba/ice/blob/docs/plugin-icestark/docs/guide/advance/icestark.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

好的，晚点我验证一下。
多问一句，是否现在 `icejs` 1.0.0 版本就已支持。

**Comment by jallens** [comment]
@ClarkXia 您好。关于你说到在`Layout`中动态更新子应用的方法`updateApps`。
![image](https://user-images.githubusercontent.com/3937706/77070885-0a294600-6a26-11ea-88dd-4aed281a7c8e.png)

如上图，我在项目工程中打扰`Layout`的`props`，并不存该属性。请教这个方法在哪个版本的中，还是未来待实现的？

**Comment by ClarkXia** [comment]
https://github.com/ice-lab/icejs/pull/125 会在下个版本添加

**Comment by ClarkXia** [comment]
使用 icejs 最新版可以使用 updateApps 的相关能力
