### ISSUE TITLE
Vue项目改造后接入主框架报错：webpackJsonp is not defined at app.js:1

### ISSUE THREAD

**Issue by woaizimmy** [ice-lab/icestark#90]
如题，把现成的一个 Vue 项目改造后（独立运行和构建均正常），接入主框架时提示：
Uncaught ReferenceError：webpackJsonp is not defined at app.js:1
在 webpack.prod.conf.js 中添加 chunks: ['manifest', 'vendor', 'app'] 后问题依然，特来请教如何解决

**Comment by ClarkXia** [comment]
具体接入方式和构建出来的资源是什么样的，webpackJsonp 应该是 webpack 打包的时候会注入的，最好是能够把内部逻辑代码移除，提供一个复现 demo

**Comment by woaizimmy** [comment]
构建出来的资源主要如下目录，接入 `url` 用了其中的 `js/app.js` 和 `css/vendor.css`，另外抱歉提供不了复现 demo ……
```md          
├── dist/                
│   └── css/
│       ├── vendor.css
│   └── js/
│       ├── [0~20].js
│       ├── app.js
│       ├── manifest.js
│       ├── vendor.js
├── favicon.ico
└── index.html
```

**Comment by ClarkXia** [comment]
基于 vue 项目 https://github.com/ice-lab/icestark-child-apps/tree/master/child-waiter-vue-2 试了下打出 vendor 及分包，应该是没问题的
url 接入需要两个包括 vendor 和  app，另外可以看着 manifest 是否是页面初始化必须，可以通过查看独立运行时入口页面源码查看

**Comment by ClarkXia** [comment]
按上述的说明先试下，有问题再重开 issue
