### ISSUE TITLE
微前端在框架里面嵌入子框架，子框架的接口请求不了，多个子框架切换，切换不成功

### ISSUE THREAD

**Issue by xqt888** [ice-lab/icestark#91]
1、微前端在框架里面嵌入子框架，子框架的接口请求不了，
2、多个子框架在主框架切换，切换不成功
github地址：https://github.com/xqt888/micoDemo.git

**Comment by ClarkXia** [comment]
框架应用代码中 https://github.com/xqt888/micoDemo/blob/master/icestark-layout/src/App.jsx 仅定义了 url 没有设置子应用对应的 path 属性
子应用开发是 mock 问题可以参考：https://ice.work/docs/icestark/guide/child-app#%E5%AD%90%E5%BA%94%E7%94%A8%E5%BC%80%E5%8F%91%E6%97%B6%E8%AF%B7%E6%B1%82%E6%9C%AC%E5%9C%B0%20Mock%20%E6%8E%A5%E5%8F%A3%EF%BC%9F

**Comment by xqt888** [comment]
> [代码](https://github.com/xqt888/micoDemo/blob/3c0c0510c254580a264ca3487726c242e41b9c47/icestark-layout/public/data.jsx#L13)中通用子页面的匹配规则放到最后，不然会往通用页面上进行匹配
> 
> 子应用开发是 mock 问题可以参考[文档](https://ice.work/docs/icestark/guide/child-app#%E5%AD%90%E5%BA%94%E7%94%A8%E5%BC%80%E5%8F%91%E6%97%B6%E8%AF%B7%E6%B1%82%E6%9C%AC%E5%9C%B0%20Mock%20%E6%8E%A5%E5%8F%A3%EF%BC%9F)

那子应用接口请求不了，怎么办

**Comment by ClarkXia** [comment]
看下 mock 问题的那篇文档，子应用在框架应用下发起请求域名是框架应用的域名
如果需要使用子应用的域名或者 mock 数据，需要单独再设置下 baseURL 等请求配置

**Comment by xqt888** [comment]
> 看下 mock 问题的那篇文档，子应用在框架应用下发起请求域名是框架应用的域名
> 如果需要使用子应用的域名或者 mock 数据，需要单独再设置下 baseURL 等请求配置

mock数据是可以啊，但是我想请求的是后端接口，但是显示没有接口请求

**Comment by xqt888** [comment]
> [代码](https://github.com/xqt888/micoDemo/blob/3c0c0510c254580a264ca3487726c242e41b9c47/icestark-layout/public/data.jsx#L13)中通用子页面的匹配规则放到最后，不然会往通用页面上进行匹配
> 
> 子应用开发是 mock 问题可以参考[文档](https://ice.work/docs/icestark/guide/child-app#%E5%AD%90%E5%BA%94%E7%94%A8%E5%BC%80%E5%8F%91%E6%97%B6%E8%AF%B7%E6%B1%82%E6%9C%AC%E5%9C%B0%20Mock%20%E6%8E%A5%E5%8F%A3%EF%BC%9F)
通用子页面的匹配规则放在了最后，切到其他子系统，再切回来，切不回来了

**Comment by ClarkXia** [comment]
> mock数据是可以啊，但是我想请求的是后端接口，但是显示没有接口请求

看下控制台里的接口请求，简单 debug 下是没有发起请求还是其他原因

**Comment by xqt888** [comment]
> > [代码](https://github.com/xqt888/micoDemo/blob/3c0c0510c254580a264ca3487726c242e41b9c47/icestark-layout/public/data.jsx#L13)中通用子页面的匹配规则放到最后，不然会往通用页面上进行匹配
> > 子应用开发是 mock 问题可以参考[文档](https://ice.work/docs/icestark/guide/child-app#%E5%AD%90%E5%BA%94%E7%94%A8%E5%BC%80%E5%8F%91%E6%97%B6%E8%AF%B7%E6%B1%82%E6%9C%AC%E5%9C%B0%20Mock%20%E6%8E%A5%E5%8F%A3%EF%BC%9F)
> > 通用子页面的匹配规则放在了最后，切到其他子系统，再切回来，切不回来了


> > mock数据是可以啊，但是我想请求的是后端接口，但是显示没有接口请求
> 
> 看下控制台里的接口请求，简单 debug 下是没有发起请求还是其他原因
> 
> > 通用子页面的匹配规则放在了最后，切到其他子系统，再切回来，切不回来了
> 
> github 仓库可以更新下复现的 case
子系统部分接口是mock数据，部分又请求后端接口，切换子系统再切回来，请求后端接口的接口请求不了了，报堆栈溢出，是mockjs在判断使用mock模板还是请求后端接口那里报出来的，这个要怎么解决

**Comment by ClarkXia** [comment]
在子应用中使用 mockjs，mockjs 会堆栈溢出

**Comment by ClarkXia** [comment]
1.5.0 版本也支持了沙箱隔离的执行，可以尝试下，原则上还是需要保证框架应用的逻辑尽量简单，子应用逻辑执行可以隔离开
