### ISSUE TITLE
使用 ice-scripts  创建的飞冰项目，想要把px转换为rem,配置了之后，报Found non-callable @@iterator 

### ISSUE THREAD

**Issue by xqt888** [ice-lab/icestark#95]
配置如下图 
<img width="826" alt="WechatIMG1409" src="https://user-images.githubusercontent.com/25101390/77607568-bb176f80-6f55-11ea-8124-e2d67b78d429.png">

**Comment by ClarkXia** [comment]
先确定下增加 webpack plugin 的配置方式是不是正确，错误提示中 webpack-chain 抛错了，应该是添加方式不对。
ice-scripts 问题可以到对应仓库提问
