### ISSUE TITLE
快速上手是不是写错了

### ISSUE THREAD

**Issue by csywweb** [ice-lab/icestark#97]
![image](https://user-images.githubusercontent.com/3185567/77822404-4a2ab000-712d-11ea-9f70-063558196e18.png)
执行完之后安装不了

**Comment by ClarkXia** [comment]
看下具体输出的错误，我试了下应该是可以的

**Comment by xyeric** [comment]
> ![image](https://user-images.githubusercontent.com/3185567/77822404-4a2ab000-712d-11ea-9f70-063558196e18.png)
> 
> 执行完之后安装不了


升级一下npm就应该就可以了

**Comment by csywweb** [comment]
ok 可以了
