### ISSUE TITLE
entry inline script 解析存在错误

### ISSUE THREAD

**Issue by liunian** [ice-lab/icestark#99]
使用 entry 方式来加载子应用，子应用内有 inline script，假设是以下内容，那么在主应用中加载子应用时将无法预期输出

```html
<script>
    console.log('1 < 2');
</script>
```

初步看上去和 https://github.com/ice-lab/icestark/blob/master/src/util/handleAssets.ts#L9 有关

```js
const SCRIPT_REGEX = /<script\b[^>]*>([^<]*)<\/script>/gi;
```

**Comment by ClarkXia** [comment]
fixed in @ice/stark 1.5.0
